### ISSUE TITLE
Worldline Rendering Issue

### ISSUE THREAD

**Issue by i0lytte** [stakira/OpenUtau#1016]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

So, I've been using OpenUtau for a few weeks now and I haven't been having any issues using the program and what not. But now every time I try to make a singer sing something, it doesn't work. I'll wait for the singers' vocals to render and then press the play button, only for me to be greeted with a pop-up that says, "Unable to load DLL 'worldline' or one of its dependencies: The specified module could not be found." I don't know what I did wrong, so I'm hoping someone can help me.

### Explains how to reproduce the bug

1. Load a singer
2. Put down random midi notes
3. Change the notes to something random (ie. a --> lie)
4. Press play and wait to see if it'll actually play or put up a warning thing

### OS & Version

Windows 11

### Logs

[log20240119_001.txt](https://github.com/stakira/OpenUtau/files/13994472/log20240119_001.txt)

**Comment by oxygen-dioxide** [comment]
Install the [latest Visual C++ Redistributable](https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170).

See documentation: https://github.com/stakira/OpenUtau/wiki/FAQ#on-windows-it-says-unable-to-load-dll-worldline-or-one-of-its-dependencies-or-dll-was-not-found
