### ISSUE TITLE
Openutau error

### ISSUE THREAD

**Issue by pig-eon** [stakira/OpenUtau#103]
![2021-10-14_192823](https://user-images.githubusercontent.com/61450450/137309038-9d89dc77-d661-4906-8b78-69b1fe51593a.png)

**Comment by pig-eon** [comment]
An error occurred when I dragged the Midi file to the view

**Comment by Astel123457** [comment]
Currently doesn't support drag and drop to open. You must import as midi.
For future issues join our discord!
