### ISSUE TITLE
Block sequence entries are not allowed in this context.

### ISSUE THREAD

**Issue by cipschip** [stakira/OpenUtau#1040]
### Acknowledgement

- [x] I have read Getting-Started and FAQ

### 🐛 Describe the bug

When i was trying to reopen my ustx i was greeted with this error
i also used teto english in the project
Block sequence entries are not allowed in this context.

(Line: 234, Col: 13, Idx: 3833) - (Line: 234, Col: 13, Idx: 3833): Block sequence entries are not allowed in this context.

0.1.384.0

![Screenshot 2024-02-15 081613](https://github.com/stakira/OpenUtau/assets/151246945/b09d32cd-5e94-46d3-b2bd-dd2a4cb5d2ba)

### Explains how to reproduce the bug

if u have created a ustx and closed the program reopening the sequence will get u to this error

### OS & Version

Windows 11

### Logs

[log20240215.txt](https://github.com/stakira/OpenUtau/files/14292790/log20240215.txt)
02/15/2024 08:44:00 +01:00 : Error : Failed to open files C:\Users\altex\OneDrive\Documents\midnight.ustx

**Comment by oxygen-dioxide** [comment]
Does this bug happen to all the ustx files you saved? Could you provide a ustx file that causes this bug?

**Comment by cipschip** [comment]
here 
[midnight.zip](https://github.com/stakira/OpenUtau/files/14307958/midnight.zip)

**Comment by oxygen-dioxide** [comment]
It seems to be caused by tab character in lyrics. OpenUtau has a bug that makes it unable to load lyrics with tab character from ustx

**Comment by oxygen-dioxide** [comment]
Also how did you create this ustx file? Is this file imported from another format (like ust, vsqx or midi) or produced by third-party tools (like utaformatix)? Have you used classic plugin? since we can't type tab characters directly in openutau.

**Comment by oxygen-dioxide** [comment]
Also how did you create this ustx file? Is this file imported from another format (like ust, vsqx or midi) or produced by third-party tools (like utaformatix)? Have you used classic plugin? since we can't type tab characters directly in openutau.

**Comment by oxygen-dioxide** [comment]
You can use EN DELTA phonemizer, then you'll be able to input English words.

**Comment by cipschip** [comment]
this issue must be fixed

**Comment by cipschip** [comment]
> You can use EN DELTA phonemizer, then you'll be able to input English words.

where can i get the phonemizer

**Comment by oxygen-dioxide** [comment]
oh it's called EN X-SAMPA
![image](https://github.com/stakira/OpenUtau/assets/54425948/ed6ede89-157b-4b13-aafb-d94bff0338af)

**Comment by cipschip** [comment]
thanks also i was reporting the bug beacuse im also a music producer so if u have a discord we can chat privately

**Comment by oxygen-dioxide** [comment]
This issue is related to https://github.com/aaubry/YamlDotNet/issues/732
