### ISSUE TITLE
OpenUtau crashes after clicking menu(both file, tools, help)

### ISSUE THREAD

**Issue by NewBieCoderXD** [stakira/OpenUtau#1062]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

After downloading openUtau extract it in a folder
double click OpenUtau.exe
Nothing wrong **except** I can't click on the file/tools/help menu
After clicking menu, it crashes
**Versions tried: 0.1.397 Beta, 0.1.327 both didn't work**

https://github.com/stakira/OpenUtau/assets/93028567/a0410fc8-a297-4865-8932-050f908c7058

### Explains how to reproduce the bug

1. download open utau
2. double click OpenUtau.exe
3. click on file menu
4. crashes

### OS & Version

x64 based Windows 10

### Logs

sorry, but I don't see a file related to log, and I can't click on Help menu

**Comment by oxygen-dioxide** [comment]
You can find log files inside the "Logs" folder under your OpenUtau folder 
![image](https://github.com/stakira/OpenUtau/assets/54425948/b3880b6e-da20-4e76-a23d-0c551148bb13)

**Comment by oxygen-dioxide** [comment]
Try running OpenUtau as admin

**Comment by NewBieCoderXD** [comment]
> Try running OpenUtau as admin

This worked!
And it also created the log folder(It didn't create log folder before)
Thanks, oxygen-dioxide(pretty cool name btw)
Also please consider adding information about running as admin for windows in readme

**Comment by oxygen-dioxide** [comment]
The reason of your problem is that you put your openutau to program files, which is a restricted folder. You can put it to somewhere else so that you won't need to launch it as admin each time.

**Comment by oxygen-dioxide** [comment]
You can also try using the .exe installer in github release.

**Comment by NewBieCoderXD** [comment]
Thanks :)
