### ISSUE TITLE
Singer won't work

### ISSUE THREAD

**Issue by SpaceboyYT** [stakira/OpenUtau#1119]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

When I try to play a VSQX with a singer, it won't work. Even if I have moresampler and wavtool2, the singer won't work. Am I doing something wrong?

### Explains how to reproduce the bug

1. Go to File > Open
2. Click the VSQX I sent in the link below.
3. Choose the singer I sent in the 2nd link below.
4. Change WORLDLINE-R to CLASSIC.
5. Click on the settings next to CLASSIC.
6. Change Resampler to moresampler.exe and wavtool to wavtool2.exe.
7. Press the play button.

VSQX Link: https://drive.google.com/file/d/1co6_zGkyRKLVDZKFPIG7ZKBtbthKE_6i/view?usp=sharing

Singer Link: https://drive.google.com/file/d/1eT70b722j1pa3R8jUavHdjRe3HH9ghrm/view?usp=sharing

wavtool2 Link: https://drive.google.com/drive/folders/1e0Gfy5mfbEhXAiSec4WP23xKafuc00N0?usp=sharing

moresampler Link https://drive.google.com/drive/folders/1fdw4U8dm4gW_iYIhiY3ZjNf8o6VUosVn?usp=sharing

### OS & Version

Windows 10

### Logs

IDK the logs.

**Comment by BagelHero** [comment]
Make 100% sure you have a moreconfig file, and within that config file "resampler compatibility" is set to "on".

If you don't, or are worried yours isn't correct, please try adding the attached file to your `resamplers` folder manually.
[moreconfig.txt](https://github.com/stakira/OpenUtau/files/15143225/moreconfig.txt)

You may also need to check and make sure you're using the correct Phonemizer (`DEFAULT` or `JA VCV and CVVC` for a CV voicebank), and you may want to check that the song lyrics are converted to hiragana (this depends on the singer, I'm guessing from the files you linked). The lyric converter can be found in the batch edits menu.
![image](https://github.com/stakira/OpenUtau/assets/9185335/8e48fbbd-4477-4816-a2cf-649d3d47913b)


In the future, there is a folder above the Resampler folder in the OpenUtau directory that is called Logs-- log files will automatically be placed there for you to share; or you can screenshot any error pop up :)

**Comment by lottev1991** [comment]
There's also the "Open log folder" button under Help at the top.
