### ISSUE TITLE
I don't have the Worldline database

### ISSUE THREAD

**Issue by pliplop1** [stakira/OpenUtau#1151]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

hello, 
I installed the zip program on Windows 10 to test it, I unzipped it, launched the program and I thought I had singers in the basic program but I got nothing. all my wavtools, singers etc.. files are empty.
I uninstalled the program, I downloaded the program several times but I still have nothing.

### Explains how to reproduce the bug

install the program

### OS & Version

windows 10

### Logs

[log20240520_002.txt](https://github.com/stakira/OpenUtau/files/15371033/log20240520_002.txt)

**Comment by oxygen-dioxide** [comment]
Openutau doesn't load singers, resamplers and wavtools installed in your Ameya UTAU autometically. You need to install them in Openutau. See [here](https://github.com/stakira/OpenUtau/wiki/Getting-Started#install-a-resampler) for how to install them.

**Comment by lottev1991** [comment]
It is possible to add classic UTAU's voice folder as an additional singers folder to OpenUtau to load the singers from there. This setting can be found in Preferences. It only counts for singers though.

**Comment by oxygen-dioxide** [comment]
> It is possible to add classic UTAU's voice folder as an additional singers folder to OpenUtau to load the singers from there. This setting can be found in Preferences. It only counts for singers though.

Note: This method only works if your system's locale is Japanese or all your voiceabanks use only ASCII characters. Otherwise you will find your voicebanks garbled.

**Comment by pliplop1** [comment]
I would like to use French voices, if I understand correctly to make open utau work I need to find a French phonetics dictionary then after utau voices on the web.

**Comment by BagelHero** [comment]
> I would like to use French voices, if I understand correctly to make open utau work I need to find a French phonetics dictionary then after utau voices on the web.

There's no need to find a phonetic dictionary. If you're looking to use standard UTAU french vocals, OpenUtau supports CVVC and VCCV french voicebanks, they should specify somewhere in their information, You might also see the names _Gyroflex_, _Petit Mot_ or _M2RUG_-- I believe these are supported with inbuilt Phonemizers. You can just download any french vocal that uses one of those. :)

![image showing the French language phonemizers in OpenUtau](https://github.com/stakira/OpenUtau/assets/9185335/27754bdd-4037-4f8c-a6f7-446946e8a822)

However, if you're trying to use Diffsinger french vocals, see [the Millefeulle usage guide found here](https://utaufrance.com/millefeuille-diffsinger/).

**Comment by pliplop1** [comment]
ok I think I understood I managed to make a voice say hello/Bonjour on the software
Thank you for your cooperation, if I have any questions I will get back to you.
So I will close the topic
