### ISSUE TITLE
track not playing

### ISSUE THREAD

**Issue by TetoLover** [stakira/OpenUtau#1159]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

when track done, doesnt play when you press the play button

### Explains how to reproduce the bug

press play when done the track.

### OS & Version

windows 7

### Logs

it just... cannot play

**Comment by oxygen-dioxide** [comment]
Windows 7 isn't supported by OpenUtau. It might run on your PC, but we can't ensure that all functionality works successfully. Please upgrade to Windows 10 or later.
