### ISSUE TITLE
Track won't play.

### ISSUE THREAD

**Issue by EsareOfficial** [stakira/OpenUtau#1200]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

The track won't play when play button is pressed. Yes, I have tried to test with the playback button. Yes, I have a track with notes. The sounds of the notes come out fine, but the singer just... won't sing.

Downloaded Linux, singer is Fandroid. OS is ChromeOS.

### Explains how to reproduce the bug

Make a new track
Put notes and lyrics with singer
Press play
it doesn't play??

### OS & Version

ChromeOS, Linux developer environment (Debain 11 (Bullseye))

### Logs

![image](https://github.com/stakira/OpenUtau/assets/147788173/2beadd41-0ca3-42c5-bc7a-04adf6bfe79d)

**Comment by EsareOfficial** [comment]
![image](https://github.com/stakira/OpenUtau/assets/147788173/e3a61c60-49a7-4847-808c-f55f6423cd37)
I think I found the issue! I'll be back with updates

**Comment by BagelHero** [comment]
For what its worth, it would be good to see a screenshot of the piano roll window with notes and phonemes showing in cases like this, as well as a screenshot of the track header.

**Comment by EsareOfficial** [comment]
Ever since me opening it, I switched to a different singer. Same issue.![image](https://github.com/stakira/OpenUtau/assets/147788173/70bb2159-2400-470e-afb9-a15385743cc0)

**Comment by BagelHero** [comment]
> Ever since me opening it, I switched to a different singer. Same issue.![image](https://private-user-images.githubusercontent.com/147788173/346745985-70bb2159-2400-470e-afb9-a15385743cc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1Mjg2MzQsIm5iZiI6MTcyMDUyODMzNCwicGF0aCI6Ii8xNDc3ODgxNzMvMzQ2NzQ1OTg1LTcwYmIyMTU5LTI0MDAtNDcwZS1hZmI5LWExNTM4NTc0M2NjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQxMjMyMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMmE4MmM3MjhkZTk2NzIxNjk4YzBkY2M5ZGRmOTQ4MjM0YTUwMDA1ZjkwYjI4NmMwMGIyMDcyZGM4OWE1NmQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bF_rSDlQUBx1L6LQMBvdUVleGEGnjeu9cEeMvf6mkmA)

I apologise, but we need to see the notes and, as I mentioned in my last reply, the track header as well.

**Comment by SheldonHCheers** [comment]
I have the same issue

**Comment by Tenko29** [comment]
I also have the same issue, whenever i try to play a track it wont work. i tried to redownload OpenUTAU and it still doesn't play a sound. 
<img width="1440" alt="Screenshot 2024-07-24 at 9 55 27 PM" src="https://github.com/user-attachments/assets/08f94e90-aa27-4430-a167-d361f190d0b9">
![Uploading Screenshot 2024-07-24 at 9.55.33 PM.png…]()

**Comment by Tenko29** [comment]
<img width="1440" alt="Screenshot 2024-07-24 at 9 55 33 PM" src="https://github.com/user-attachments/assets/bc4c6122-ee57-43c9-898f-4c13c914870e">

**Comment by BagelHero** [comment]
> I also have the same issue, whenever i try to play a track it wont work. i tried to redownload OpenUTAU and it still doesn't play a sound.

For you, your phonemizer is correct and its rendering, so I would check in preferences to see if the correct audio device is set

> I have the same issue
Please post screenshots as outlined here. This issue is fairly nonspecific and requires more details as it can be several user errors or settings.
