### ISSUE TITLE
Make openutau equal to synthesizer V 

### ISSUE THREAD

**Issue by mishav78** [stakira/OpenUtau#1201]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

How can I do that? 

### Explains how to reproduce the bug

What high quality voicebanks, and where do I purchase them, and what settings do I need? 

### OS & Version

Windows 10

### Logs

none

**Comment by oxygen-dioxide** [comment]
If you need more realistic voice, use diffsinger voicebanks. You can get diffsinger voicebanks for free from https://docs.google.com/spreadsheets/d/1fQX-NlFIvfmZJ-S19L86jGPOH_EIJEIygtJqLTUJPfU/edit?usp=sharing
You can also search for "diffsinger release" on youtube

**Comment by mishav78** [comment]
will it match synthesizer V or be worse? Do I have to use any particular settings?

**Comment by oxygen-dioxide** [comment]
I don't know much about synthV. You can watch videos on youtube to see how diffsinger voicebanks will sound.

**Comment by mishav78** [comment]
In openutau do I need to supply the lyrics and pitches and notes or I can supply just the vocal stem of the song, for example I want it to sing living on a prayer by Bon Jovi the way Bon Jovi sings it, what do I do?

**Comment by mishav78** [comment]
does it try to match the words you put in to the Words in the  vocal stem it analyzes with the transcription function?

**Comment by oxygen-dioxide** [comment]
> does it try to match the words you put in to the Words in the vocal stem it analyzes with the transcription function?

No, it doesn't understand the lyrics. It only gives you musical notes. You have to manually input the lyrics and ensure that they match with the notes.
