### ISSUE TITLE
OpenUtau won't open after updating to v0.1.529 from v0.1.327

### ISSUE THREAD

**Issue by crazyspidr** [stakira/OpenUtau#1224]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

OpenUtau isn't opening after updating to v0.1.529 from v0.1.327. I installed it two days ago (so I'm an absolute noob, I know) and everything was working fine then.

It seems to be in a loop of checking whether or not it needs to autosave.

### Explains how to reproduce the bug

I don't exactly know how to reproduce the bug so this is just a guess?
1. Install OpenUtau v0.1.327
2. Run OpenUtau
3. Press Update when prompted
4. Close OpenUtau when update is finished
5. Reopen OpenUtau

### OS & Version

Windows 10 x64

### Logs

[log20240726.txt](https://github.com/user-attachments/files/16390124/log20240726.txt)
For the log attached, I reopened OpenUtau and left it open for 10 minutes before closing it again because it wasn't loading.

**Comment by BagelHero** [comment]
So sorry for missing this, the audio handler was changed and a bug got introduced. If you update to the latest stable version this should be fixed! You'll have to download the update and merge the contents of your existing install with the contents of the new folder if you want to keep your settings and such. Please let us know if it fixes after that; I think there may be a bug remaining that means some people still have issues after updating to the latest beta :( Not sure if that's present in stable too.
