### ISSUE TITLE
VCs disappear when changes voicecolor

### ISSUE THREAD

**Issue by MinusDeath** [stakira/OpenUtau#1226]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Can't change VCs' suffixs
This is a VB fully supported by CVVC, but when I tried to change the voicecolor, VCs just disappeared and notes are turned into CV.

https://github.com/user-attachments/assets/5017530d-8c7f-4b3a-aae6-8cbaba5bbb3b

![cap](https://github.com/user-attachments/assets/f3a1769e-2363-4749-8d99-3026b645ebcf)

### Explains how to reproduce the bug

1. Update OpenUtau to ver.0.1.529
2. Load a CVVC VB
3. Set voicecolors
4. Change CLR

### OS & Version

Windows 10

### Logs

[log20240727-err.txt](https://github.com/user-attachments/files/16400190/log20240727-err.txt)

**Comment by MinusDeath** [comment]
Every voice color has VC transitions, and their oto have no difference except for the suffixs.

**Comment by MinusDeath** [comment]
I've noticed similar problems in the past, but it hasn't been solved.
The former one: https://github.com/stakira/OpenUtau/issues/970
This VB has every voice color with VC transitions.

**Comment by BagelHero** [comment]
Huge apologies for the inconvenience on this.

It does seem to be a fairly complex issue regarding how the phonemizer applies expressions and colors... certainly it seems several phonemizer developers have attempted to rewrite and fix the issue, but currently it seems no fix was found.

I've gone ahead and added it to the known bugs page now, and linked back here. Hopefully someone can pick it up and fix it properly soon, not being able to use multiexpression CVVC vbs seems pretty basic.
