### ISSUE TITLE
Please add instructions how to build OpenTau on Linux/BSD

### ISSUE THREAD

**Issue by yurivict** [stakira/OpenUtau#1228]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

I would like to port OpenTau to FreeBSD.

The Getting Started section doesn't explain how to build OpenUtau.
Is there a CMakeLists.txt file?

### Explains how to reproduce the bug

n/a

### OS & Version

FreeBSD 14.1

### Logs

n/a

**Comment by SoulMelody** [comment]
According to this issue [Avalonia/6990](https://github.com/AvaloniaUI/Avalonia/issues/6990), the Avalonia framework is currently not supported by FreeBSD
