### ISSUE TITLE
Track Aint Playing

### ISSUE THREAD

**Issue by EnderBlaze7879** [stakira/OpenUtau#1229]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

so this issue has been asked a lot but from what I've seen nobody is having it on iMac so I'm putting this up. when I press the. play button on a track, it wont play

### Explains how to reproduce the bug

Pressing the play button on a track 

### OS & Version

macOS Ventura 13.4.1

### Logs

I can't figure out why it won't show up on the log

**Comment by BagelHero** [comment]
Can you screenshot the track header as well as piano roll with notes and expressions panel showing?

**Comment by EnderBlaze7879** [comment]
Uh i don’t know what you mean by that 😅
Not saying you don't know if you are doing, I just don't really understand music programs and stuff well enough

**Comment by BagelHero** [comment]
Hopefully a diagram will help! I need a screenshot that shows all these things.
![image](https://github.com/user-attachments/assets/ceda3e06-c10f-4fe6-9d29-eab421f29323)

**Comment by EnderBlaze7879** [comment]
![Screenshot 2024-08-05 at 10 34 22 AM](https://github.com/user-attachments/assets/6bf7eebd-88bc-4791-b4b8-0d2c411ff8f5)
![Screenshot 2024-08-05 at 10 35 22 AM](https://github.com/user-attachments/assets/4855b13b-6f25-44d2-a46f-70f380c965c2)

**Comment by BagelHero** [comment]
Hm, I was tempted to ask you to try other lyric input methods (it should stick to romaji or hiragana) but even using your example, my copy of Teto gives this result:
![image](https://github.com/user-attachments/assets/08485fcc-5110-4ab5-b8a1-051b49bcc30a)

Would you be able to go to Help>Open Logs Location, and attach the latest log file available in that folder? Also, could you share the method you used to install this voicebank?

**Comment by EnderBlaze7879** [comment]
[log20240806.txt](https://github.com/user-attachments/files/16512082/log20240806.txt)
By Method, You Mean Like What Website Or Whatever, Right? https://kasaneteto.jp/utau/ 
![Screenshot 2024-08-06 at 9 01 49 AM](https://github.com/user-attachments/assets/90fbb785-b243-4dc0-9c89-8018555450d9)
![Screenshot 2024-08-06 at 9 03 02 AM](https://github.com/user-attachments/assets/df27b100-a15b-4382-aa4f-846c36f36f3e)

**Comment by BagelHero** [comment]
Thank you, the log helps. It looks like her file pathing or encoding has become corrupted? 

![Screenshot_20240807_060627_HTML Viewer](https://github.com/user-attachments/assets/4b7df591-8377-4ac4-b8fd-10996177fe09)

For install method, I meant how you _installed_ the voicebank-- ie, did you drag and drop the .zip onto the program window, did you use the install singer menu option, or did you extract directly into the singer directory?

**Comment by EnderBlaze7879** [comment]
heh.... I did use safari... I did compress the file myself because I used the install singers menu and it just opens the folder, so I compressed it so it would work

**Comment by BagelHero** [comment]
Sorry for the late reply. Please set your Safari to **not** automatically unzip files on download-- either Safari or you re-compressing the file has effectively corrupted some of the encoding! Unfortunately in this case, at that point it's easiest to redownload (after turning off that Safari "feature" to obtain the actual original compressed file of course).

To remove the broken copy of Teto, you will need to remove the folder manually. You can get to the singers folder by clicking this:
![image](https://github.com/user-attachments/assets/0dbdf5df-dd43-46b9-b18c-97db2d693f0b)
 Then simply delete the folder.
 
 You can also try pasting the un-compressed Teto folder into this location if you _really_ don't want to redownload, but I can't guarantee it will work out of the gate that way 👍🏽

**Comment by EnderBlaze7879** [comment]
ok so i reinstalled it and turned off the auto decompressor and the play button still won't play. 

https://github.com/user-attachments/assets/295f53de-5baa-46ae-863e-588114708f30

**Comment by BagelHero** [comment]
I would need to see your piano roll again to see the issue, a new log would likely also help. 
I assume you already A) removed the old broken Teto as well as B) turned off the decompression and redownloaded before reinstalling, so will need those before anything else!

**Comment by EnderBlaze7879** [comment]
ok so I pulled up OpenUTAU to get the piano roll and stuff sent, and of course it decides to work now. thanks for your help!

**Comment by EnderBlaze7879** [comment]
all fixed

**Comment by EnderBlaze7879** [comment]
ok nvm for some reason it only worked for a specific set of notes or something  but idk. the piano roll has the notes that did work
![Screenshot 2024-08-12 at 5 19 17 PM](https://github.com/user-attachments/assets/b7a1d53c-893b-4e87-a8b9-23a3b71e5ee5)
[log20240812.txt](https://github.com/user-attachments/files/16592681/log20240812.txt)

**Comment by EnderBlaze7879** [comment]
messed around and ended up fixing it
