### ISSUE TITLE
Track is not playing

### ISSUE THREAD

**Issue by IsmailMid** [stakira/OpenUtau#1238]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

When I click the play button the track doesn't play.

### Explains how to reproduce the bug

1. Click on the play button.
2. It doesn't work.
3. Check the speakers if they work.
4. s t i l l  n o .

### OS & Version

macOS 14.0

### Logs

<img width="1680" alt="Screenshot 2024-08-12 at 06 42 05" src="https://github.com/user-attachments/assets/efa5ffac-04a4-4b36-91d8-7e95c84ebb8c">
The above screenshot shows my personal work.

**Comment by BagelHero** [comment]
It's likely you need to change the Phonemizer. Teto uses the EN X-Sampa phonemizer.
![image](https://github.com/user-attachments/assets/1e24637f-893a-4dde-aea6-6fbc2210cb91)
