### ISSUE TITLE
Could we have a linux version

### ISSUE THREAD

**Issue by ghost** [stakira/OpenUtau#124]
Sorry for the annoyance, could you please compile the app for linux. I am using box86 and wine to run OpenUtau on a raspberry pi and compiling as a song isn't supported. So please could we have a linux version, and maybe for ARM processors.
Ty

**Comment by stakira** [comment]
A test build for Linux (x86_64 only)
https://github.com/stakira/OpenUtau/releases/download/OpenUtau-Latest/OpenUtau-prerelease-x86_64.AppImage

**Comment by Vector-frame** [comment]
Amazing! The Open Source community appreciates the initiative! Can't wait to start testing, I'll do it as soon as I can! ^_^

**Comment by Alexmitter** [comment]
Sadly the appimage was not working for me, seems not everything on shared objects that should be included ended up included. Here the log for good messure: 
```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libdl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl: cannot open shared object file: No such file or directory
   at OpenUtau.LibraryLoader.dlopen(String fileName, Int32 flags)
   at OpenUtau.LibraryLoader..ctor(String path, String library) in /media/sf_Code/OpenUtau/OpenUtau.Core/Util/LibraryLoader.cs:line 28
   at OpenUtau.Audio.AudioOutput..ctor() in /media/sf_Code/OpenUtau/OpenUtau.Core/Audio/AudioOutput.cs:line 36
   at OpenUtau.App.Program.InitAudio() in /media/sf_Code/OpenUtau/OpenUtau/Program.cs:line 67
   at OpenUtau.App.Program.Main(String[] args) in /media/sf_Code/OpenUtau/OpenUtau/Program.cs:line 28
Aborted (core dumped)
```




@stakira It should be fairly simple to get old style resampler working on both OSX and Linux via Wine from within the native OpenUtau client. If that is of interest, I can give support in that.

**Comment by stakira** [comment]
libdl should be from the OS. However Ubuntu don't have it. See https://github.com/mellinoe/veldrid/issues/143#issuecomment-446096640 for solution.

Regarding resamplers, you can contribute to https://github.com/stakira/OpenUtau/wiki/Resamplers#linux if you have more to add.

**Comment by Alexmitter** [comment]
>libdl should be from the OS. However Ubuntu don't have it. See https://github.com/mellinoe/veldrid/issues/143#issuecomment-446096640 for solution.

I am on Fedora. I am in the believe quite a few distros do not ship a libdl.so. Seems distros ship libdl.so.2 with their glibc, so it makes sense to link to that.

>Regarding resamplers, you can contribute to https://github.com/stakira/OpenUtau/wiki/Resamplers#linux if you have more to add.

Sorry, completely missed that, that's basically everything I would have had to add.

**Comment by Vector-frame** [comment]
> libdl deve ser do sistema operacional. No entanto, o Ubuntu não o possui. Veja [mellinoe/veldrid#143 (comentário)](https://github.com/mellinoe/veldrid/issues/143#issuecomment-446096640) para solução.
> 
> Em relação aos reamostradores, você pode contribuir para https://github.com/stakira/OpenUtau/wiki/Resamplers#linux se tiver mais a adicionar.

It's a curious case. I installed this version of Ubuntu Studio on my Desktop a few weeks ago. In the previous version (21.04) the program had opened normally. Because of this, I don't believe it to be a library issue inherent in Ubuntu.
