### ISSUE TITLE
English VCCV Phonemizer error for the word "desktop"

### ISSUE THREAD

**Issue by Myuqou** [stakira/OpenUtau#1259]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

When the word "desktop" is entered into a note when using the English VCCV Phonemizer, the word is unable to be phonemized which results in an error.

I messed around a bit with the code and it looks like the issue can be fixed by adding {"skt", "sk"} to the vcccExceptions list in the EnglishVCCVPhonemizer.cs file.

It seems like something that makes an "skt" phoneme is pretty rare in English as "desktop" and "desktops" were the only words I could find that has this problem, which is why it may have been overlooked up to this point.  That said, I don't fully understand the logic behind the phonemizer so someone who knows what they are doing should probably take a closer look at this.

### Explains how to reproduce the bug

1. Load a English VCCV Singer and set the phonemizer to EN VCCV.
2. Make a note and set the lyric to "desktop" without the quotes

### OS & Version

Windows 10

### Logs

2024-08-27 16:23:07.582 -07:00 [ERR] phonemizer error desktop
System.Collections.Generic.KeyNotFoundException: The given key 'skt' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at OpenUtau.Plugin.Builtin.EnglishVCCVPhonemizer.ProcessSyllable(Syllable syllable) in C:\projects\openutau\OpenUtau.Plugin.Builtin\EnglishVCCVPhonemizer.cs:line 413
   at OpenUtau.Plugin.Builtin.SyllableBasedPhonemizer.Process(Note[] notes, Nullable`1 prev, Nullable`1 next, Nullable`1 prevNeighbour, Nullable`1 nextNeighbour, Note[] prevNeighbours) in C:\projects\openutau\OpenUtau.Plugin.Builtin\SyllableBasedPhonemizer.cs:line 164
   at OpenUtau.Api.PhonemizerRunner.Phonemize(PhonemizerRequest request) in C:\projects\openutau\OpenUtau.Core\Api\PhonemizerRunner.cs:line 168

**Comment by BagelHero** [comment]
Woah, good catch! That phonemizers' author is currently on a break I believe, but that sounds like you've found the correct solution.
If you still have the fork, feel free to send through a pull request and it'll go through to beta in a week or three (we just have a bit of a slow turn around), else one of our regular contributors (or myself) will make sure it gets fixed if you don't have the time :)

**Comment by Az-Neter** [comment]
> Woah, good catch! That phonemizers' author is currently on a break I believe, but that sounds like you've found the correct solution.
> If you still have the fork, feel free to send through a pull request and it'll go through to beta in a week or three (we just have a bit of a slow turn around), else one of our regular contributors (or myself) will make sure it gets fixed if you don't have the time :)

Try seven.

Thanks for the kick while I was asleep. Now I'm going to ruin your life and the lives of everyone who has ever touched this software. Grats. Good job.
