### ISSUE TITLE
I cant open it after downloading for the first time

### ISSUE THREAD

**Issue by skibidi1234567899** [stakira/OpenUtau#1261]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

it doesn't say that the app is damaged, it says it cant open because it cant check for malware  
<img width="1440" alt="Screenshot 2024-09-01 at 4 13 06 PM" src="https://github.com/user-attachments/assets/f284f91a-a75c-4f08-8edd-7a458ebdaaf6">

### Explains how to reproduce the bug

go to safari
press download
try to open it
and then it shows the the picture I linked

### OS & Version

MacOS sonoma 14.5

### Logs

<img width="1440" alt="Screenshot 2024-09-01 at 4 13 23 PM" src="https://github.com/user-attachments/assets/ac9904a6-cc08-47af-bfac-81bff839ed1a">

**Comment by Az-Neter** [comment]
Don't bother. This software is trash, everyone online hates it and the community is vile and worthless.

Your issue request will be left unanswered for months and that's if you're lucky.

**Comment by BagelHero** [comment]
This was resolved via the discord! The user had to navigate to their security settings to allow unsigned apps, then they could follow the [FAQ instructions](https://github.com/stakira/OpenUtau/wiki/FAQ#on-macos-when-i-try-to-run-openutau-it-says-this-app-is-damaged) for bypassing the next warning.
