### ISSUE TITLE
macOS Sequoia / OSX15 | ARM64 / MBA2024.13in | Track edit window / view has no content. 

### ISSUE THREAD

**Issue by bedm4n** [stakira/OpenUtau#1283]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Self explanatory: The track edit window has no content. 

Screenshot one: A multitrack project with several ust files. The Track editing window is not the active window in this screenshot.
![1](https://github.com/user-attachments/assets/565a65f0-fe40-436e-bcce-0f1c49d0a867)
Screenshot two: A brand new project, as a control variable to show that this error also occurs with new blank projects and new blank tracks when opening the track editing window. The Track editing window IS the active window in this screenshot, the colour of this active window is greyed out.
![2](https://github.com/user-attachments/assets/eb76bea8-621e-4261-a78a-61d6e65d13e6)
 

### Explains how to reproduce the bug

1. Open OpenUtau on OSX15 on ARM64 architecture.
2. Create a new project or open an existing project.
3. Open the Track editing window / view.

### OS & Version

macOS Sequoia / OSX15 | ARM64

### Logs

As this is a display error, there was no log error generated or associated with the issue.

**Comment by BagelHero** [comment]
This is a persistent and unfortunate known bug. It can be bypassed by resizing the window a little bit, but we're aware that's not exactly friction-less. Would you mind if I mention this issue and use crops of your screenshots on our [Known Bugs page](https://github.com/stakira/OpenUtau/wiki/Known-Bugs#known-bugs), for easy developer reference?

**Comment by bedm4n** [comment]
Yes! That’s fine by me! Go right ahead!
