### ISSUE TITLE
Voice not rendered/played on macOS

### ISSUE THREAD

**Issue by sdercolin** [stakira/OpenUtau#129]
# Issue information
 **Nothing happens when I click the `play` button or press `space` key.**
- The playback test succeeds, and the default tone wav when note is added also works right
- Lyrics input/selection works right so I think the singer is loaded correctly
- `Export All` creates silent wav files

# Environment
- OS: MacOS Catalina 10.15.7
- CPU: Intel
- Version: OpenUtau.0.0.386.dmg

# Settings
<img src="https://user-images.githubusercontent.com/7665216/139402381-086898d6-6231-4608-b628-dd399857f329.png" alt="Girl in a jacket" width="400">

**Comment by stakira** [comment]
Have you taken a look at the release note?

**Comment by sdercolin** [comment]
Yes. Both mac release note and the Get Started page.
I have done chmod +x on the .sh files.
Singer the correct lyric type (JP VCV) are chosen.

**Comment by sdercolin** [comment]
Ok, I need a `macres_mac64` executable together with the `macres_mac64.sh`. Not it works!!
