### ISSUE TITLE
i cant hear anything in open utau

### ISSUE THREAD

**Issue by gencxt** [stakira/OpenUtau#1291]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

i checked everything including my head phones and other apps work but open utau doesn't I also checked the phenominaforgotwhatitscalled and it worked last time and it doesn't work now I also reinstalled but it doesn't work it also doesn't work in the other windows of openutau
<img width="1280" alt="Screenshot 2024-09-24 at 11 22 27 AM" src="https://github.com/user-attachments/assets/16baacce-672b-47eb-af54-855012d03966">
<img width="1280" alt="Screenshot 2024-09-24 at 11 22 56 AM" src="https://github.com/user-attachments/assets/531498ec-812a-4baa-9059-23fd5705955c">

### Explains how to reproduce the bug

im not sure it just happend one day

### OS & Version

mac 14.6.1

### Logs

09/24/2024 11:23:59 +08:00 : Information : Autosave skipped.
09/24/2024 11:23:57 +08:00 : Information : Publish notification Part rendered.
09/24/2024 11:23:57 +08:00 : Warning : Part rendered. not on main thread
09/24/2024 11:23:57 +08:00 : Information : StartPlayback at 00:00:00

**Comment by BagelHero** [comment]
Please check the audio device settings _inside_ OpenUtau's preferences, here:
![image](https://github.com/user-attachments/assets/b8a07c3e-a8ea-484c-9329-bc28a00a9ffd)

**Comment by gencxt** [comment]
thank you it worked!

> Please check the audio device settings _inside_ OpenUtau's preferences, here: ![image](https://private-user-images.githubusercontent.com/9185335/370347316-b8a07c3e-a8ea-484c-9329-bc28a00a9ffd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDI2NTYsIm5iZiI6MTcyNzM0MjM1NiwicGF0aCI6Ii85MTg1MzM1LzM3MDM0NzMxNi1iOGEwN2MzZS1hOGVhLTQ4NGMtOTMyOS1iYzI4YTAwYTlmZmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjZUMDkxOTE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGVkZWQ2ZGUzMTZiN2FjNjJiZmY1Y2U4NzU5ZWRmZmUwNGJkYjhlYmYzNDJhNGFkMjQ0NGQxNzc0NjE3NTMxMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.wu70a-6Qz7khqsJESf-M-Hxx2m2HW2Ie8aujpqkC5r4)
