### ISSUE TITLE
Open Utau closes when changing voicebank

### ISSUE THREAD

**Issue by pseudo-producer** [stakira/OpenUtau#1294]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Open Utau closes spontaneously when changing voicebanks in the same UST. Before you think it's something from OTO or the voicebank, I tested the same bank in another project and it didn't close spontaneously. Below is the generated LOG file and a demonstration video.

### Explains how to reproduce the bug

1. Open a UST or create your own.
2. Choose a voicebank to work with.
3. Replace that voicebank with another one.

### OS & Version

UBUNTU STUDIO 24.04

### Logs

[log20241005.txt](https://github.com/user-attachments/files/17267721/log20241005.txt)

https://github.com/user-attachments/assets/d30086cc-fd17-4646-a416-33a8eb7be3b3

**Comment by oxygen-dioxide** [comment]
Is your pre-rendering on? If yes, turn of pre-rendering and see if it still crashes

**Comment by pseudo-producer** [comment]
Hello! I disabled it in preferences and I can change the voice bank, but I can't play the new voice bank. When I click play, Open Utau closes like other times. Here is the new log:

[log20241007.txt](https://github.com/user-attachments/files/17284930/log20241007.txt)

**Comment by oxygen-dioxide** [comment]
Then this might be an oto or audio format issue. You can run a singer error check on your latter voicebank. (In "Tools → Singer", choose the singer you're using, "⚙→ Generate Singer Error Report")

**Comment by pseudo-producer** [comment]
I checked the errors pointed out in the voice bank reports and it does not close by itself when changing the singer. However, the project closes if I start playing the sound using the WORLDLINE resampler. Here is the new LOG file:
[Uploading log20241007.txt…]()

**Comment by pseudo-producer** [comment]
> Then this might be an oto or audio format issue. You can run a singer error check on your latter voicebank. (In "Tools → Singer", choose the singer you're using, "⚙→ Generate Singer Error Report")

I checked the errors indicated in the voice bank reports and, even though I solved these problems, the software closes by itself when changing the singer. However, the project closes if I start playing the sound using the WORLDLINE resampler. Here is the new LOG file:

[log20241007.txt](https://github.com/user-attachments/files/17286812/log20241007.txt)

**Comment by oxygen-dioxide** [comment]
What does the singer error report say?

**Comment by pseudo-producer** [comment]
> O que diz o relatório de erros do cantor?

I fixed the errors that were in the voice bank reports. Most of them were the same thing (duplicate aliases). It still kept crashing.

**Comment by pseudo-producer** [comment]
> Pode ser (pelo que eu pude vagamente dizer no log) que certas amostras no seu voicebank estejam causando o travamento. Verifique a taxa de bits nas amostras e veja se há alguma inconsistência. É recomendado que todas as amostras estejam em 44100Hz 16 bits.
> 
> Além disso, verifique se há algum problema no oto. Eu faria isso no Vlabeler ou em qualquer outro lugar com o qual você se sinta confortável.

Thanks for the suggestion, but I have doubts about this really being the problem. I recently configured this bank and when rendering the notes I pre-configured everything to 44100/16 bits (utau's default). 

The error report doesn't show anything about voice samples, on the contrary, it generates 0 errors.

**Comment by pseudo-producer** [comment]
> O que diz o relatório de erros do cantor?

[log20241006_001.txt](https://github.com/user-attachments/files/17387554/log20241006_001.txt)

I performed the same procedure on Windows and the same problem occurred, but this log file seems to have something else.
