### ISSUE TITLE
No mountable file systems

### ISSUE THREAD

**Issue by axel61311** [stakira/OpenUtau#1302]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

I just downloaded openutau and when i open the dmg, it says no mountable file systems. I have allow unsigned apps turned oun, and I have tried a lot of guides.

### Explains how to reproduce the bug

I don't know how to reproduce it.

### OS & Version

macOS 10.11.6

### Logs

There was no log

**Comment by BagelHero** [comment]
Just so we all have the same information, is one of the guides you've checked this one? It seems pretty well thought out:
https://deciphertools.com/blog/2017-10-02-no-mountable-file-systems/

Potentially, your operating system might be a tad old if you're actually still running El Capitan. Personally, I'm not certain enough of OpenUtau's mac compatibility to say for sure if that's the case though.
