### ISSUE TITLE
Frequent crashes resulting in file destruction.

### ISSUE THREAD

**Issue by gluustix** [stakira/OpenUtau#1304]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

I've had a problem for a while that other users seem to have reported but seems to have not been resolved, though since the most recent update it has gotten worse. 
When I attempt to render anything using WORLDLINE-R (which, unintentionally happens frequently since it is what the program defaults to), the program will crash. I've had this issue for about a year. The program will also frequently crash if I attempt to or accidentally make another edit while it is in the process of rendering. Oddly enough, voicebanks written entirely in hiragana are exempt from this. They work completely fine.
I've gotten used to this and simply work around it by saving *extremely* frequently, but ever since the last update, when the program crashes, my file is corrupted, either by half of it being completely wiped or by some other means that I can't understand by looking at it. I've begun making backups just in case, but I've lost hours of work to this more than once. As seen in this screenshot, when viewing the file in text format, it ends abruptly in the middle of a line. (If necessary, I can provide some of my files recently corrupted by the program, but I wouldn't see much use in it as other than the abrupt stop, there isn't anything abnormal)
![A screenshot of the file PINK_SAM-PAPA-autosave.ustx open in visual studio code. It ends abruptly in the middle of a line formatting a note/phoneme](https://github.com/user-attachments/assets/8c2ad7cb-56fe-46b2-9f7d-361d2b5267e7)

### Explains how to reproduce the bug

1. Load any file
2. Attempt to render using WORLDLINE-R using any voicebank, with the exception of completely hiragana voicebanks
3. Program locks up, crashes about two seconds later.
4. Reload program, attempt to open USTX. Will throw an error of either a null object reference, or missing expected syntax in the file.

In the instance of the null object reference, the file seems to be intact when viewing in text format, but corrupted in some way which doesn't allow it to open. The missing expected character applies to the abruptly ending file.
"[lotl_lisa.ustx](https://drive.google.com/file/d/1oQX4ymn7UQGtQuo42D4i9JWRjco6Tgd0/view?usp=drive_link)", "[PINK_SAM-PAPA-autosave.ustx](https://drive.google.com/file/d/1ao4CnvZ3NyHzIUmnt11nyJ6sWjWK3u4Q/view?usp=drive_link)", are the abruptly ending files.
"[PINK_SAM-PAPA.ustx](https://drive.google.com/file/d/1evc_NRZCoXqEdUqzqijZ75FdGAIf5K5t/view?usp=drive_link)", is the files that raises a null object exception. There was one more, but I seem to have deleted it. (Files shared through drive links due to being unsupported by Github)

### OS & Version

Windows 11 Home

### Logs

[log20241017_002.txt](https://github.com/user-attachments/files/17413485/log20241017_002.txt)

**Comment by gluustix** [comment]
Not certain if it has anything to do with the differences in the function of hiragana and non-hiragana banks, but also being a user of classic UTAU my system locale is set to Japanese. I'm not certain that could be responsible for any bugs related to English, Romaji, or other non-kana banks, but it might be useful to mention. Additionally my "MTSAM" and "MTKATHY" banks used in the attached files are written in a slightly custom phoneme format that as far as I'm aware isn't standard to or supported by any of the settings in OU. I wouldn't think this would be an issue either, but you never know. May be worth mentioning.

**Comment by BagelHero** [comment]
For right now, you can switch to another resampler by default in preferences in more recent versions!

Worldline-R crashes happen for two reasons: 
1. faulty oto.ini entries being used
2. faulty audio files being used

Both can be found to fix by running a singer error check via `Tools` > `Singers...`, then pressing the ⚙ icon and `Singer Error Check`. It'll generate a .txt file and tell you what files have issues, and what issues. Typically any duplicate warnings are benign but you're looking for invalid oto.ini formats and invalid audio formats particularly. UTAU resamplers and thus OpenUtau generally call for **WAV files that are 44.1k sample rate, 16bit, and mono**. Hiragana/romaji/novel formatting should not be an issue! The exclamation points in your file path may or may not be an issue for a few programs, though-- it's probably not the problem here but if you ever have an opportunity to change that source folder name without breaking lots of links, I'd recommend it.

Do you know what phonemizer you were selecting when this error occurred?
![image](https://github.com/user-attachments/assets/8a25e1b8-baf5-4d85-ab5c-0e7f13d2f238)

**Comment by gluustix** [comment]
The phonemizer was just left at default, you can see that in the USTX track info.
![image](https://github.com/user-attachments/assets/4943d65f-e944-49b6-937c-b05a62b52d43)
Not quite certain why it'd be having problems between Papa and the phonemizer, I've never had any issues with him, no crashes, lag, audio problems, etc. Works like a charm. 

I should have also specified, the crashes also occur while using the Classic renderer. Worldline produces an instant crash regardless of what I'm doing, and Classic produces crashes seemingly at random, though typically when editing lyrics and note parameters. 

As for my singers, it seems the more frequent recent crashes may have been corrupt .wav files? I moved everything to a new hard drive recently, actually around the same time of the latest update, and I think some files were damaged in the process? But the close link in timing lead me to believe it was some update related problem.

The singer reports cited invalid oto settings, which is odd because I'd been oto-ing singers in the same way for a pretty long time and never had an issue with it before. I looked and found the oto was completely fine, but some of my samples were 0 ms long. That also explains an issue that randomly popped up after I moved all my files, where one of my singers would fail to render certain phonemes due to "invalid audio format". I fixed the issue by replacing the samples and it is no longer reported in the singer report, but the crashes still persist.

As for my silly looking folder name, it was only supposed to be temporary but I unfortunately forgot about it and yes, I can't change it without breaking a *lot* of links. Though it's never caused me problems and should be perfectly fine to keep.
I've tested it with a lot of intentional crashes in the past few hours, and it seems to no longer corrupt files when it crashes. It's funny how just 3 or so corrupt wav files can cause that much of an issue.

For the other random crashes, though, I can probably chalk it up to my computer being sort of a piece of junk. The issue happens not only with my singers but with any other fairly commonly used singers that other users seem to not have a problem with(This seems to be a problem brought up in a different issue, where two users experience Worldline crashes using a certain version of TETO, while others using the same version had no problem). It's likely something odd on my end and nothing wrong with the application itself, it's been happening since I begun using it about a year and a half - two years ago. The issue only happening with non-kana singers is likely just coincidence, but I figured it would be worth mentioning just in case.

Also, thank you for letting me know that I can set the default renderer! I guess I didn't notice that when it was added.

My bad for opening an issue over nothing haha, but it never occurred to me that something could have screwed my files up when I moved them to a new drive.

Thanks!
