### ISSUE TITLE
Compatibility with EN CVVC

### ISSUE THREAD

**Issue by jikyusan** [stakira/OpenUtau#133]
I would like to see phonemizer support for EN CVVC so I can use Kasane Teto's English Voice Library easily. Is that possible?

**Comment by shiibeh** [comment]
i am currently working on a phonemizer specific to teto's english, i'll post here when finished

**Comment by jikyusan** [comment]
> i am currently working on a phonemizer specific to teto's english, i'll post here when finished

Alright, Thank You very much!

**Comment by Lauren042** [comment]
> 
> 
> i am currently working on a phonemizer specific to teto's english, i'll post here when finished

oh wow! I haven't made a phonemizer before, but is there any way I or others can help?

**Comment by nagotown** [comment]
> > i am currently working on a phonemizer specific to teto's english, i'll post here when finished
> 
> oh wow! I haven't made a phonemizer before, but is there any way I or others can help?

i think i've got it right now, thanks for asking :)

**Comment by TrikiNya** [comment]
@nagotown any updates? for now, I'm trying my best and experimenting with the Japanese CVVC phonemizer

**Comment by nagotown** [comment]
> @nagotown any updates? for now, I'm trying my best and experimenting with the Japanese CVVC phonemizer

teto's part is done but me and @HeidenBZR are trying to add compatibility for all delta English reclists. i'm fine with releasing a wip now though, i'll check with heiden.

**Comment by nagotown** [comment]
should be out now. if your version is stuck on 553, you might need to reinstall.
all voicebanks that are in teto's voicebank format currently work. (ex. Peiton)

**Comment by jikyusan** [comment]
Cool! Can I close this then?

**Comment by nagotown** [comment]
i suppose, but it's not finished.

**Comment by jikyusan** [comment]
Thank you so much! :D
