### ISSUE TITLE
OpenUtau immediately crashes

### ISSUE THREAD

**Issue by DreamyFlowerz** [stakira/OpenUtau#1347]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

If I click on any of the buttons at the top (files, tools, help, etc) and it crashes. No error message or anything, it just crashes.

https://github.com/user-attachments/assets/7dd3f9a3-3ad5-4ec5-9932-8dd9fdf9d098

### Explains how to reproduce the bug

1. Download OpenUtau-win-x64
2. Launch OpenUtau
3. Click on any of the buttons at the top of the screen

### OS & Version

Windows 10

### Logs

i don't see a logs folder??

**Comment by oxygen-dioxide** [comment]
Where do you put your OpenUtau? It seems that you put it into a place where it can't access. Try putting it to another drive. If you only have C:, put it directly under C drive (like C:\OpenUtau\)

**Comment by BagelHero** [comment]
Additionally, just in case, if you downloaded the .zip version please ensure you have extracted the archive and aren't trying to launch from inside of the .zip.

**Comment by DreamyFlowerz** [comment]
> Where do you put your OpenUtau? It seems that you put it into a place where it can't access. Try putting it to another drive. If you only have C:, put it directly under C drive (like C:\OpenUtau)

moving it fixed the issue! thanks c:

**Comment by DreamyFlowerz** [comment]
> Where do you put your OpenUtau? It seems that you put it into a place where it can't access. Try putting it to another drive. If you only have C:, put it directly under C drive (like C:\OpenUtau)

moving it fixed the issue! thanks c:
