### ISSUE TITLE
having issues pressing play with certain voicebanks

### ISSUE THREAD

**Issue by KUR0MICHAN** [stakira/OpenUtau#138]
I can hit play with Uruha and Mayabu but Not Ritsu Strong and normal please help!

**Comment by stakira** [comment]
GitHub issues are for reporting bugs and crashes. Vague help requests are not efficiently handled here. For help request please read https://github.com/stakira/OpenUtau/wiki/Getting-Started, https://github.com/stakira/OpenUtau/wiki/FAQ. If still not resolved, help requests are better handled by the community in the Discord server.
