### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by kuwoh** [stakira/OpenUtau#16]
I'm sorta lost on the resampling engine/resampler part. Can you give any examples or maybe write a tutorial?

**Comment by stakira** [comment]
Here is a website that lists some resamplers. http://utau.us/resample.htmlExperience with UTAU would help

**Comment by kuwoh** [comment]
Hopefully a tutorial would be up soon on the wiki. Looking at some videos how to import voicebanks hasn't worked for me yet.

**Comment by Vector-frame** [comment]
Olá! Possuo um OS baseado em Linux. Como faço pra usar no meu notebook sem precisar do Wine ou Virtual Box?
