### ISSUE TITLE
macOS | Making/Editing expressions currently broken.

### ISSUE THREAD

**Issue by chouchorps** [stakira/OpenUtau#161]
**Describe the bug**
When making or editing any expression, it will refuse to work.

**To Reproduce**
1. Go to 'Tools > Expressions'.
2. Make or edit any expression.
3. Hit "Apply".

**Expected behavior**
When making or editing any expression, and hitting apply, a window saying "Error: No options specified" will appear.

**Screenshots**
<img width="639" alt="Captura de Pantalla 2021-11-17 a la(s) 21 36 47" src="https://user-images.githubusercontent.com/91445907/142317467-37594fba-4dcf-4c14-93a1-47690ad8915e.png">

**Environment:**
 - OS: macOS
 - Version: v0.0.475.0
 - Voicebank used: doesn't apply
 - Ust used: doesn't apply

**Comment by stakira** [comment]
Should be fixed with 0.0.503 release.
