### ISSUE TITLE
Can't update OpenUtau

### ISSUE THREAD

**Issue by katiehedrick** [stakira/OpenUtau#165]
When I try to update OpenUtau I get a message that says this: 
![error](https://user-images.githubusercontent.com/91288575/142464156-a899aade-87e2-4172-b64c-b622ee938af2.png)

I clicked on "Yes" and I have installed both the 32bit and 64bit version of .NET core 3.1 Desktop Runtime but it still gives me that message.
I need help with this. Thanks in advance!

**Comment by unknownLinguist** [comment]
How did you fix this?  I am having the same problem now!  Is that feature just not working yet?
