### ISSUE TITLE
Software wont read oto.ini data

### ISSUE THREAD

**Issue by LH762** [stakira/OpenUtau#185]
**Describe the bug**
The software doesn't read the oto.ini file for my voice bank, it works fine in regular UTAU but not in OpenUtau

**Expected behavior**
For the Software to play with the oto.ini file working

**Environment:**
 - OS: Windows
 - Version [e.g. 0.0.547.0]
 - VB: FYE Cherry (Un released)
 - UST: Vampire (Deco *27)

Video of my issue
https://user-images.githubusercontent.com/74991447/144174767-0ee68127-2c94-4103-8d60-3c0fdd550a5f.mov

**Comment by lcpdecastro** [comment]
Would it be possible for you to share the VB and the UST? I'll try to replicate it to see if it's a program-side error or just something with the installation.

**Comment by voizuu** [comment]
I'm getting the same issue, my voicebank is here: https://drive.google.com/file/d/1zbx1tWXIy12T5ZMwbMa2hAXpVVPWjVoM/view?usp=sharing I'm having problems with ta, sa, and a few more but in utau it's fine. maybe it has to do with CV?

**Comment by lcpdecastro** [comment]
> I'm getting the same issue, my voicebank is here: https://drive.google.com/file/d/1zbx1tWXIy12T5ZMwbMa2hAXpVVPWjVoM/view?usp=sharing I'm having problems with ta, sa, and a few more but in utau it's fine. maybe it has to do with CV?

I just installed the VB on my build and tested `あかさたなはまやらわ` in both romaji and hiragana since the bank supports both; the romaji worked correctly, while the hiragana had problems. This happened on both UTAU and OpenUTAU.

 Looking through the oto.ini, it seems that some of the parameters were not saved correctly and defaulted to 0. For example, `sa` and `さ` have different parameters:

![image](https://user-images.githubusercontent.com/40616595/144550167-b9a5e3b8-90ff-45f8-a298-9ca979b2879a.png)
![image](https://user-images.githubusercontent.com/40616595/144550192-e00ce87a-b621-42ae-98ba-a6ed13482d2c.png)

**Comment by voizuu** [comment]
thank you!

**Comment by voizuu** [comment]
> > I'm getting the same issue, my voicebank is here: https://drive.google.com/file/d/1zbx1tWXIy12T5ZMwbMa2hAXpVVPWjVoM/view?usp=sharing I'm having problems with ta, sa, and a few more but in utau it's fine. maybe it has to do with CV?
> 
> I just installed the VB on my build and tested `あ か さ た な は ま や ら わ` and `a ka sa ta na ha ma ya ra wa` since the bank supports both; the romaji sounded right, while the hiragana had problems. This happened on both UTAU and OpenUTAU.
> 
> Looking through the oto.ini, it seems that some of the parameters of the hiragana aliases don't match with their romaji counterparts. For example, `sa` and `さ` have different parameters:
> 
> ![image](https://user-images.githubusercontent.com/40616595/144550192-e00ce87a-b621-42ae-98ba-a6ed13482d2c.png) ![image](https://user-images.githubusercontent.com/40616595/144550167-b9a5e3b8-90ff-45f8-a298-9ca979b2879a.png)
> 
> At first I thought all of the problematic parameters defaulted to 0 (as above), but it looks to just be inconsistency between hiragana and romaji aliases. For example, here are the parameters of `na` and `な` as viewed from within OpenUTAU:
> 
> ![image](https://user-images.githubusercontent.com/40616595/144647114-f8177ee8-f3e4-4b43-bc27-0bf8225d61c4.png)
> 
> Fixing the parameters in the oto.ini file should make the VB work properly.

Turned out to be an issue with the cache, I deleted the cache and reinstalled the program and the vb was completely fixed. (fixing the oto aliases also helped a lot!) Thank you!
