### ISSUE TITLE
Help offered

### ISSUE THREAD

**Issue by mooncat69** [stakira/OpenUtau#19]
Do you need any help? I've been working in C# for many years and am keen to assist.

I know a little Japanese, but probably not enough to provide localization.

**Comment by MinamiYuu** [comment]
Hi
Uh, I tried to compile and run the program but when I try to import a file (or do almost anything) the program crashes. I opened it as debugging in Visual Studio and looks some lines are incorrect or a .cs file is missing.
Actually I dunno a lot of programming so I don't know what to do
help please

**Comment by mooncat69** [comment]
It might be complaining about a missing resampler. Do you have one of those, or any messages shown when it crashes?

**Comment by MinamiYuu** [comment]
I've added moresampler (maybe it doesn't works with it). I compiled it as release (since debug doesn't creates the file for adding resamplers).
When I tried depuration, there was an error and in Visual Studio a couple of lines were highlighted (I suppose those are wrong(?)

**Comment by MinamiYuu** [comment]
Okay, now it works but only opens .vsqx files, not midi nor ust.
The problem is now with the identification of graphemes (syllables). I'm testing it and only renders vowels and "n". Does it works with hiragana or romaji. and, only uses CV voicebanks or also VCV and CVVC.

**Comment by mooncat69** [comment]
Have you tried the file with another application. I'm also looking at Utsu https://github.com/titinko/utsu/releases which works better for some things, but only accepts UST files.
