### ISSUE TITLE
vcvrack compatibility

### ISSUE THREAD

**Issue by Supermagnum** [stakira/OpenUtau#195]
Hello, as vcvrack, a open source modular software synth is becoming increasingly more popular and many people are developing or maintaining plugins for it I suggest a a compatible plugin for it .

First, this must be resolved:
https://github.com/stakira/OpenUtau/issues/124

The manual for vcvrack is here:
https://vcvrack.com/manual/

Vcvrack's GitHub page is here:
https://github.com/VCVRack

**Comment by stakira** [comment]
Won't do it myself since its' out of scope. Also, I don't see how they are relevant. Contribution is welcomed, if it actually makes sense.
