### ISSUE TITLE
Can't Detect Singer Directory

### ISSUE THREAD

**Issue by gmfcd128** [stakira/OpenUtau#20]
![image](https://user-images.githubusercontent.com/32321100/67947508-c2dd1d00-fc1e-11e9-8ca9-6472af4eb7a5.png)
Already selected the proper directory.
Singer is XiaYuYao V3( https://www.voicemith.com/xiayuyao/ ),

**Comment by mooncat69** [comment]
I don't know if you have tried this, but I had to go to Tools -> Preferences -> General -> Paths and add the root folder of all my voices. In my case, this was C:\Program Files (x86)\UTAU\voice

**Note**: You'll also have to copy resampler.exe and resampler.dll from UTAU into the Resamplers folder of your OpenUTAU executable.

**Comment by dysphoricdemon** [comment]
I have this same problem, and even though I've put in the path, nothing appears.

**Comment by stakira** [comment]
Unzip installation is now deprecated. Please use Tools -> Install Singer menu instead.
