### ISSUE TITLE
No sound after latest two updates

### ISSUE THREAD

**Issue by FredrikTheFolf** [stakira/OpenUtau#206]
**Describe the bug**
The software have been working accordingly untill the last two updates. The software is completly silent even when its supposed to sing. No VB's I've used in the past work anymore. The notes light up in blue as it should but no sound is present. The software isn't muted but I can't hear a thing.

**Expected behavior**
It is supposed to sing when I use the notes that work with the VB but it doesn't work. 

**Environment:**
 - OS: [Windows 11]
 - Version [e.g. 0.0.575.0]
 - Kasane Teto, WALTT english and cute, Zuzune Ring CVC, Matsudappoiyo Light CVC
 - None

**Comment by nagotown** [comment]
have you checked which audio device is selected in preferences and tried switching resamplers?

**Comment by FredrikTheFolf** [comment]
The audio woks as it should as its set to my headphones and nothing else. I was working on a cover when the next time I booted it up after updating it, it just didn’t work.

**Comment by rugamemaker** [comment]
I'm not sure this could help, but you have to try changing the resampler. I used macres and it worked.
