### ISSUE TITLE
(Windows10) OpenUtau won't launch

### ISSUE THREAD

**Issue by Adumbwithnoknowledge** [stakira/OpenUtau#207]
I just dl'ed OpenUtau, and anytime I try to launch it, it just wont. No errors, just it wont launch

https://user-images.githubusercontent.com/96824509/147663375-da3d8801-8036-439c-8659-fbbfc1558808.mp4

[log20211229.txt](https://github.com/stakira/OpenUtau/files/7788882/log20211229.txt)

**Comment by nagotown** [comment]
check task manager to see if it's running in the background?

**Comment by nagotown** [comment]
just read log, it's a portaudio issue
