### ISSUE TITLE
A few voicebanks make odd noises that i can't do anything about

### ISSUE THREAD

**Issue by stardusttaiyaki** [stakira/OpenUtau#213]
**Describe the bug**
A few voicebanks of mine, notably more power-oriented ones, may sometimes make a weird noise in the start of a note, akin to a metal scream in an Utsu-P song.

**To Reproduce**
I don't know all the notes, but it applies to high notes, like a G#5 "da" or F5 "ka". I used HICO - CATENA (Eye) and ゲキヤク -頓服-
Here's the ustx. https://www.mediafire.com/file/j73zzfeow7wnybh/idola_circus.ustx/file

**Expected behavior**
I expected a cleaner sound

**Screenshots**
The notes look the same whether there's a noise or not, so screenshots aren't needed.

**Environment:**
 - OS: Windows
 - Version 20H2
 - HICO - CATENA (Eye)
 - Idola Circus UST by Adry Eli

**Comment by lcpdecastro** [comment]
I tested it on my end with HICO - CATENA (Eye) and it seems like that grating sound is caused by worldline, the resampler bundled with OpenUTAU. Try using a different resampler and see what you get (I personally got the best result from doppeltler64).
