### ISSUE TITLE
Cannot install voicebank

### ISSUE THREAD

**Issue by M4dOS** [stakira/OpenUtau#226]
How to fix that
![OpenUtau_G7OPB1xqyY](https://user-images.githubusercontent.com/60644076/152536187-c6e52de9-a4ba-4402-a821-90e304e5aacf.png)

**Comment by stakira** [comment]
This is Windows preventing OpenUtau from modifying C:\Program Files. Consider moving OpenUtau to somewhere else.

**Comment by M4dOS** [comment]
oh, tnx for help
