### ISSUE TITLE
Can't use certain Arpabet phonemes with the Arpasing Phonemizer 

### ISSUE THREAD

**Issue by IDKWHYHELP** [stakira/OpenUtau#228]
Could someone please add support for all phonemes in Arpabet instead of just the common ones.

**Comment by adlez27** [comment]
You can add additional phoneme symbols by editing `arpasing.yaml` in the Plugins folder or in individual voicebank folders. It will allow you to use those phonemes when typing lyrics phonetically.

**Comment by IDKWHYHELP** [comment]
OK, that seems to work. I made a repository for the new file, if you want to use it.
