### ISSUE TITLE
Can't download latest build

### ISSUE THREAD

**Issue by Cuperino** [stakira/OpenUtau#23]
AppVeyor seems to automatically delete builds after 6 months. You could use GitHub Releases or SourceForge to host your builds.

Edit: I found the project on SourceForge but there are no builds to download.
https://sourceforge.net/projects/openutau/

**Comment by 641i130** [comment]
Maybe we need to compile ourselves ;-;

**Comment by Cuperino** [comment]
I would've already done it if I wasn't uising Linux exclusively right now. My goal was to find an OpenUtau build and get it working under Wine.

**Comment by 641i130** [comment]
Aye, I use arch btw

**Comment by Cuperino** [comment]
Ubuntu 20.04 here, due to self imposed job requirements. But I love using Arch!

If anyone compiles OpenUtau or a build appears, and it works well on Wine, I can try making a Snap package of it.

**Comment by Falazi** [comment]
@Cuperino 
I have compiled it.
[OpenUtau.zip](https://github.com/stakira/OpenUtau/files/4960416/OpenUtau.zip)

**Comment by stakira** [comment]
Yes unfortunately it gets deleted after 6 months. I'll try to do some commits every now and then to keep a build on AppVeyor.
