### ISSUE TITLE
MacOS version, OpenUTAU Resamplers missing

### ISSUE THREAD

**Issue by NekoNe-P** [stakira/OpenUtau#240]
So, i just updated OpenUTAU for Mac (Intel) to V0.0.606.0, and the problem is that the audio devices won't appear neither the resamplers, here's a screenshot of what i am refering to (Sorry for my bad english qwq)
![image](https://user-images.githubusercontent.com/100492063/155858577-08ee672b-7825-4a73-8c11-813125ef1752.png)

I tried to re-lauch OpenUTAU but nothing happened, i also tried using other resamplers (Thing that absolutely didn't work), it stayed the same, so i don't know what i can do!
Can someone help me with that qwq?

OS: MacOS Big Sur
OpenUTAU Ver: V0.0.606.0

**Comment by stakira** [comment]
Please try 0.0.608 or newer

**Comment by NekoNe-P** [comment]
> Please try 0.0.608 or newer

That fixed my problem thanks :D
