### ISSUE TITLE
Ways to sort/toggle phonemizers

### ISSUE THREAD

**Issue by kokoropaint** [stakira/OpenUtau#244]
There's a lot of phonemizers available currently and more get added by the day. I think it'd be valuable to add some way to toggle the visibility of certain phonemizers, since not every OU user is using every listed language or voicebank format.
(This is a request I see somewhat often in the #ideas channel of the Discord; I'm posting it here so that more possible contributors can see it)

**Comment by HitCoder9768** [comment]
Might start dabbling on a way to implement this myself soon.

Wondering if it might be valuable to toggle phonemizers per voicebank, potentially, so that only relevant phonemizers for specified voicebanks show up in the dropdown... just some food for thought

**Comment by oxygen-dioxide** [comment]
> Might start dabbling on a way to implement this myself soon.
> 
> Wondering if it might be valuable to toggle phonemizers per voicebank, potentially, so that only relevant phonemizers for specified voicebanks show up in the dropdown... just some food for thought

OpenUTAU already remembers the phonemizer you used on a voicebank. see https://github.com/stakira/OpenUtau/commit/203118953d31cdb26c940c482bd56153e4fc8539

**Comment by HitCoder9768** [comment]
> > Might start dabbling on a way to implement this myself soon.
> > Wondering if it might be valuable to toggle phonemizers per voicebank, potentially, so that only relevant phonemizers for specified voicebanks show up in the dropdown... just some food for thought
> 
> OpenUTAU already remembers the phonemizer you used on a voicebank. see [2031189](https://github.com/stakira/OpenUtau/commit/203118953d31cdb26c940c482bd56153e4fc8539)



> so that only relevant phonemizers for specified voicebanks show up in the dropdown

I'd appreciate if you could read my full reply as opposed to skim reading it and correcting me. I am fully aware of this feature, my point was that some voicebanks may function with more than one phonemizer (see: JP -> EN phonemizer) and so maybe it would be valuable to toggle **relevant** phonemiser**s** (plural).

Thanks, and best wishes.

**Comment by stakira** [comment]
Another idea: show a top few recently used list at the top of the dropdown menu, then a separator line, then all the phonemizers. This should solve most of the problems, and does not require UI work.
