### ISSUE TITLE
playback doesn't work

### ISSUE THREAD

**Issue by Nyxlab** [stakira/OpenUtau#262]
when i try to play what i did to see how it sounds and stuff it just doesn't play, the line doesn't move nothing, i've tried to look up to see why this happens( i've tried space, manually clicking, its not that i just dont pay attention or anything, those things just genuinely don't work when i do it) but i'm finding no solutions anywhere

**Comment by stakira** [comment]
The description is too vague to be actionable. Please try get some help in Discord channel instead.

**Comment by FlashlightET** [comment]
same here and do NOT direct us to a freaking discord server
