### ISSUE TITLE
cannot change singers after update

### ISSUE THREAD

**Issue by itporl** [stakira/OpenUtau#263]
i can't change singers after updating to the latest version , my voicebanks are still installed looking through the singers window but cannot change them on the track.

**Comment by nagotown** [comment]
please try updating OpenUtau. if this doesn't solve the problem, send the log file associated with this bug. the log file should be in `/OpenUtau/Logs/`.

**Comment by stakira** [comment]
The cause seems to be singers of the same name in both the Singers folder and the additional singer path. Please delete one of them or upgrade.

**Comment by itporl** [comment]
its fixed after updating!
