### ISSUE TITLE
.XML file support

### ISSUE THREAD

**Issue by nicolalandro** [stakira/OpenUtau#267]
It is possible to import a .XML music file? 
It is open source and it have the text associated to the notes and it is possible to export it from MuseScore and similar software.

**Comment by oxygen-dioxide** [comment]
Currently OpenUTAU doesn't support MusicXML, but you can to convert it to vsqx with [utaformatix](https://sdercolin.github.io/utaformatix3/) first, then import it in OpenUTAU.

**Comment by stakira** [comment]
It's a good idea. However, MusicXML format is obscure and requires some effort. Contribution welcomed.

**Comment by nicolalandro** [comment]
I'm able to read from MusicXML file the notes pitch, duration and lirycs, how can I write an UTAU file?

**Comment by stakira** [comment]
You could refer to Ust.cs and Vsqx.cs as example.

**Comment by nicolalandro** [comment]
I'm trying to convert in that way wiht the script in this [repo](https://github.com/nicolalandro/xml2ustx). I will make streamlit demo soon. It seams OpenUtau can open it.

**Comment by nicolalandro** [comment]
[Here](https://share.streamlit.io/nicolalandro/xml2ustx/main/src/streamlit_app.py) a demo webserver to test it and try to validate the correctness.

**Comment by nicolalandro** [comment]
That issue will solve https://github.com/stakira/OpenUtau/pull/1152
