### ISSUE TITLE
Data folder on Linux and MacOS should not be visible at $HOME

### ISSUE THREAD

**Issue by Nyaacinth** [stakira/OpenUtau#268]
When OpenUtau running on linux, it will create `$HOME/OpenUtau` as data directory, but the more reasonable way to save data would be create directory at `$XDG_CONFIG_HOME/OpenUtau` or `$HOME/.config/OpenUtau`

**Comment by stakira** [comment]
Files in OpenUtau folder can easily reach Gigabytes, which seems too large to put in a hidden directory.

**Comment by Nyaacinth** [comment]
> Files in OpenUtau folder can easily reach Gigabytes, which seems too large to put in a hidden directory.

However, from the perspective of Linux's general standards, the private data folder of an application is better to be located in a non-$HOME location. If you are worried about the downward compatibility of the application, you can provide a custom option for users to decide the location of data folder, there will be many people loving it.

**Comment by Nyaacinth** [comment]
When using applications on Linux and MacOS, we usually don't want it to put non-hidden files under $HOME and treat it as an unexpected behavior then try to prevent it. And there are many other applications have similar issues, like LMMS. And these applications will generally place the data in other locations or allow the user to choose the location of the data. Really hope OpenUtau will have similar features to do it. Thanks

**Comment by HitCoder9768** [comment]
+1ing this issue

> Files in OpenUtau folder can easily reach Gigabytes, which seems too large to put in a hidden directory.

While this is the case on Windows, on Linux it is more correct and acceptable for data directories created by an application to be hidden ($HOME/.OpenUtau instead of $HOME/OpenUtau ) or to be stored in $HOME/.config or $HOME/.local/share or $HOME/.local/bin

As a point of comparison, games can take up gigabytes of space too (see Dead By Daylight, GTA5, many other games made after 2015) and Steam stores them in $HOME/.local/share/Steam/steamapps/common/

It is a generally understood and accepted practice on UNIX and Linux systems.

Thank you for understanding

**Comment by orowith2os** [comment]
Having OpenUtau would be appreciated for following not only just Linux standards, but alternative packaging methods -- If OU were to follow the appropriate environment variable (`$XDG_CONFIG_HOME`) it would allow for me to flatpak it while giving as little permissions as possible.

**Comment by stakira** [comment]
Please let me know if the change works

**Comment by leonardo-ronchi** [comment]
Linux Mint user here.

After the update, OpenUtau doesn't link to the user folder (the one w/ the Singers, Templates, etc.) anymore when I try to launch it from the Terminal, it only opens the application without any singer/cache/etc. installed, as if it were a clean copy of the program. 

Before everything was smooth, this happened only after I updated. I think that this probably has to do with the change of paths and OU is not able to locate the files anymore.

I don't know if I have to move the contents of the OpenUtau user folder to somewhere else or try to reinstall it, but I wanted to report the issue and I thought that this might be the right thread to use.

The version is the latest, 0.0.879.0.

Thanks

**Comment by stakira** [comment]
You can move the files yourself to new location:
`$XDG_DATA_HOME/OpenUtau` or `$HOME/.local/share/OpenUtau`
And you can delete the old `Cache` folder. New cache folder is at
`$XDG_CACHE_HOME/OpenUtau` or `$HOME/.cache/OpenUtau`

**Comment by Nyaacinth** [comment]
Wow, finally an official fix for this behavior, thanks to everyone involved in the development!

**Comment by leonardo-ronchi** [comment]
Thank you, now everything works as usual!
