### ISSUE TITLE
Update Tracking

### ISSUE THREAD

**Issue by Nyaacinth** [stakira/OpenUtau#269]
At the moment, the GitHub release of OpenUtau is a tag pointed to latest release and has no version number in release name, it would be better for release tracking and Linux distribution if we are using standard GitHub release feature (eg. tag all of release with the version and don't remove them when they are out of date)

PS: I'm creating a AUR package for ArchLinux distribution at https://aur.archlinux.org/packages/openutau-bin

**Comment by nagotown** [comment]
a new version is created every time a PR merges. not sure if it would be practical to have 656 versions in releases.

**Comment by Nyaacinth** [comment]
> a new version is created every time a PR merges. not sure if it would be practical to have 656 versions in releases.

Hmm... That does make sense, but it seems that the updates can only be tracked manually by viewing the latest release? Still hope that there is a way can automatically tracking updates.

**Comment by stakira** [comment]
In release page [appcast.linux-x64.xml](https://github.com/stakira/OpenUtau/releases/download/OpenUtau-Latest/appcast.linux-x64.xml) is the file used by autoupdater to check version.

**Comment by Nyaacinth** [comment]
> In release page [appcast.linux-x64.xml](https://github.com/stakira/OpenUtau/releases/download/OpenUtau-Latest/appcast.linux-x64.xml) is the file used by autoupdater to check version.

I've finally made an update tracker for it and bound it to my own api. The issue is resolved and thanks for providing the information.

**Comment by hiddeninthesand** [comment]
> a new version is created every time a PR merges. not sure if it would be practical to have 656 versions in releases.

Why not? Many other projects that version similarly also use releases/tags. I maintain the MPR package, similarly to @Nyaacinth's use case, and having to create new updating scripts specifically for this repository seems like overkill.
