### ISSUE TITLE
UST doesn't play

### ISSUE THREAD

**Issue by Nicte0019** [stakira/OpenUtau#27]
I addded the resampler and singer but the ust doesn't play. I dont know what could be the problem.

**Comment by Yxbcvn410** [comment]
Such thing can happen if lyric for the note you enter is not found in the singer's phoneme list. That could be the problem, you can look through all phonemes a singer implements in the Tools -> Singers menu.
You can try out [my fork](https://github.com/Yxbcvn410/LibreUTAU), bad lyrics are highlighted there.

**Comment by Nicte0019** [comment]
That was the problem, the singer's phenemes are incomplete. I tried another singer and it works now. Thank you!
