### ISSUE TITLE
Can't open .exe

### ISSUE THREAD

**Issue by xZlic3x** [stakira/OpenUtau#28]
I'm trying to open from the Latest Build.
The errors I had last time are still there.
![image](https://user-images.githubusercontent.com/58606134/95013938-dde0ba00-0643-11eb-9057-61ef93858817.png)

Is there any way I can use OpenUtau? Something I need to install?
I'm using Windows 10.

**Comment by Yxbcvn410** [comment]
Please show the exception stack traces you get, you can find them in the Exception tab. Judging by the left exception window there are problems with your locale - try setting it to US? I will try to create a pull request when you will show the exception traces.
Hope my advice was helpful.

**Comment by stakira** [comment]
This is pretty weird. Maybe try the latest build and make sure [.net 4.8 runtime](https://dotnet.microsoft.com/download/dotnet-framework/net48) is installed? Otherwise please paste the exception from the most recent logXXXXX.txt file.

**Comment by xZlic3x** [comment]
I made sure I have it installed. I tried with the latest build, same error.
Where is the logXXXXX.txt file? I get an Exception_XXXX(many numbers).zip, is it the same thing?

Will make sure once again I have locale correctly set up.

**Comment by stakira** [comment]
You can upload the most recent Exception_XXXX.zip here as well.

**Comment by xZlic3x** [comment]
[Here](http://www.mediafire.com/file/ri588uy3tmcsowb/Exception_132468281055313824.zip/file) you have it.

**Comment by stakira** [comment]
Just pushed a commit to fix the issue. Since I cannot reproduce the issue myself, could you help check if it is fixed?

**Comment by xZlic3x** [comment]
Still doesn't work. Error is different I think,
[Here](http://www.mediafire.com/file/0itzlw3c909gk94/Exception_132468834402139180.zip/file) is the Exception files generated.

I'm sorry if I'm making too much trouble.

**Comment by stakira** [comment]
No worries. These are issues I could not find myself, so I shall appreciate your help.
This time it's a issue about "1.23" being "1,23" in Spanish. I just made a fix. Let's see if any further issue.

**Comment by xZlic3x** [comment]
It works now! Thank you!
It might take me some time to get used to it.
Do you have any tutorial for it?
