### ISSUE TITLE
請問該如何設定聲音??

### ISSUE THREAD

**Issue by Maitreya229** [stakira/OpenUtau#3]
1.已經加入了singer，請問有辦法設定聲音嗎??
2.該專案還有再開發嗎?是否能release最新版?謝謝。

**Comment by LovelyA72** [comment]
It looks like the singer select function is not working...

**Comment by Maitreya229** [comment]
Dear Sir,
1.I can select the singer.
2.Can you give me an example? thank you.

**Comment by Maitreya229** [comment]
the singer running in UTAU is okay.

**Comment by cvronmin** [comment]
似乎是要設定singer的oto.ini......
目前這個項目還沒有實現這個功能，不過我的fork裡已經嘗試實現了

**Comment by Maitreya229** [comment]
Dear cvronmin,
    fork?on Linux or windows??
    能否分享?

**Comment by stakira** [comment]
抱歉，很久没有开发了，选择音库渲染播放功能大致都是可以用的。如果是指调整oto，没有开发相关功能。

**Comment by Maitreya229** [comment]
Dear stakira,
居然是作者大人XDDD

不會，很感謝您提供這個 :)
請問能否做個簡單的說明? 因為我不太知道如果操作Otzzz 謝謝.

**Comment by stakira** [comment]
到tools - preferences里面选择paths，Add，选择包含声库的文件夹，相当于utau的voice文件夹。然后在tools - singer应该可以看到有一些歌手。

大多数用户体验都是模仿FL Studio做的。双击左边白色区域添加轨道，单击右边添加part。part长度可以拖拽边缘调整。右键删除。双击part打开编辑。单击添加音符，拖拽边缘调整长度，右键删除。滚轮在上方时间标记那一条可以水平缩放，右上侧四方向图标拖拽可以移动可视范围，右上侧菱形图标滚轮或者上下拖拽可以纵向缩放。

然后可能不是很稳定，很多地方错误处理都没有仔细做，见谅见谅。

**Comment by Maitreya229** [comment]
Dear stakira,
感謝,等等來試試。

不會XDDD 已經很強了，不過當初怎麼會想要開發這個??

**Comment by Maitreya229** [comment]
Dear stakira,
我匯入Midi、選擇Singer之後，有辦法設定每個音符要發的音嗎?就是類似唱歌或說話那樣。

**Comment by stakira** [comment]
输入音符的功能似乎是当时因为不满意所以没有放进去…这个得再弄一下

**Comment by Maitreya229** [comment]
Dear stakira,
可以的話是否能幫我弄一下，因為我想要嘗試一些功能。
bug的話，我之後可以幫您修 ;)

**Comment by stakira** [comment]
先做了个简单的。期间遇到一个很奇怪的问题，折腾了很久还是没有解决：如果不用输入法的话，文字框只有空格退格可以输入进去。

**Comment by Maitreya229** [comment]
Dear stakira,
怪問題是如何?給我試試吧.
如果我能力所及,我會試著幫忙修好,或者會先找您討論看看.

**Comment by stakira** [comment]
已经push了

**Comment by Maitreya229** [comment]
Dear stakira,
1.有,我留言之後去看,發現你已經更新了XDD

2.我現在(a)匯入mid、(b)選了歌手，(c)把音輸入進去之後，(d)點選"播放"
會在
worker_RunWorkerCompleted(object sender, RunWorkerCompletedEventArgs e)
出現e.Result為null的情況。

請問我是少了什麼步驟嗎??

**Comment by cvronmin** [comment]
@stakira 「文字框只有空格退格可以输入进去」大概是因為MidiWindow#Window_KeyDown那裡把輸入覆蓋了，例如：當"I"鍵被按下時，會先執行Window_KeyDown，此方法會設置第1個ToggleButton的IsChecked值，然後設置e.Handled為true

**Comment by dijing** [comment]
这个项目好棒！现在才发现。支持大家把项目继续做下去w
