### ISSUE TITLE
OpenUTAU will open once, properly, but then the .exe file won't work at all.

### ISSUE THREAD

**Issue by Ashvith** [stakira/OpenUtau#30]
Only by replacing the whole binaries, can I make it work again.

Edit: it works, only with a few selected voice bank.

What's not working:
Teto Kasane English
Hana Asane Bold English
Kiinane
Kye Chinese CV

What's working:
Oscar Voice bank

**Comment by stakira** [comment]
Fixed an issue related to voicebanks that has not prefix map, which seems be to cause of this issue. Tested with Teto Kasane English. Seems to be  working fine.
