### ISSUE TITLE
Can't change the snap/quantization duration

### ISSUE THREAD

**Issue by JapanYoshi** [stakira/OpenUtau#313]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

The snap duration is stuck at 1/32, and I have no way of changing it that I can see. This is either way too small for songs with powers-of-2 subdivisions, or incompatible with those with powers-of-3 subdivisions.

I've tried clicking, right-clicking, and scrolling on the snap button here in the Piano Roll, but nothing happened.
![image](https://user-images.githubusercontent.com/8707990/164164211-c0d61c25-caf3-49be-8fe8-1ec31ad264a4.png)

I've read Getting Started, but it 1) only tells me how to toggle snap on and off, and 2) assumes that I have 1/16 snap instead of 1/32 snap, which isn't as much of an issue but it's weird.

### Explains how to reproduce the bug

1. Create a new project
2. Create a new section
3. Open piano roll
4. Try to change the snap duration

### OS & Version

Windows 10

### Logs

[log20220420.txt](https://github.com/stakira/OpenUtau/files/8518811/log20220420.txt)

**Comment by plagueworm** [comment]
Have you tried zooming in and out? OpenUTAU's snap seems to change based on zoom level rather than being independently set.
