### ISSUE TITLE
OU Crashing, Volume slider quirks and Expression Default value locking out.

### ISSUE THREAD

**Issue by chorvaqueen** [stakira/OpenUtau#314]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

I downloaded OpenUtau for the first time today and noticed 3 bugs. 2 of those which I can reproduce but I can describe the third one.
I'm not sure if these were already reported, I checked the trello and the Issues tab posts here just to make sure.

Bug 1: OpenUtau crashes if I delete the only track.
Bug 2: The volume slider does not move with the track while playing.
[I made a video demonstrating the bugs I found](https://www.youtube.com/watch?v=vp9fgreAgws)

Bug 3: The gender Expression Default value form became greyed out and impossible to edit unless I restart OpenUtau. I think it started locking up when I was repeatedly changing the Default value. Additionally trying to type in numbers (1-5) in the Default value form just toggles the pianoroll shortcuts while the Expression window is open.

### Explains how to reproduce the bug

Bug 1: 
Open one track from a UST file. Right click, select remove crashes OU

Bug 2:
Open a multitrack USTx. 
Play the tracks.
Move tracks while playing.
Volume slider is not corresponding to the right track.

Bug: 3:
I'm not sure, I think it's frequently modifying the Default value.

### OS & Version

Windows 10

### Logs

[log20220420.txt](https://github.com/stakira/OpenUtau/files/8522185/log20220420.txt)
[log20220421.txt](https://github.com/stakira/OpenUtau/files/8522169/log20220421.txt)

**Comment by nagotown** [comment]
by the way, you should probably separate each bug into their own issues. it makes it easier to track.
