### ISSUE TITLE
Can't select singer, Cannot install voicebank

### ISSUE THREAD

**Issue by xZlic3x** [stakira/OpenUtau#33]
Hello, it's me again.
I have a few problems.

**NOTE:** I was going to add that I had trouble opening the .exe, wich for some reason after the first time opening, requires moving the Singers directory that is created: OpenUtau > Content > Singer , to the OpenUtau folder.

**1) Can't select singer.**

After I install a singer, this happens:
![image](https://user-images.githubusercontent.com/58606134/104042226-7e61ef80-51da-11eb-88c5-7644cf705427.png)
No singer shows in the dropdown.

**2) Voicebank install error**

While installing CV romaji voicebanks, seems to work fine enough (even when I can't seem to be able to select a singer as mentioned above).

However I tried installing X_Hitomu's voicebanks and none of them worked. Error is as follows:
![image](https://user-images.githubusercontent.com/58606134/104042588-fa5c3780-51da-11eb-84b7-0b731680de87.png)

I'm using the Latest Build beacuse I don't have the knowledge to/I'm not able to build it myself.

**Comment by stakira** [comment]
Just had a fix and tried some X_Hitomu voicebanks. Should work now.
