### ISSUE TITLE
Installer for Windows

### ISSUE THREAD

**Issue by Nyaacinth** [stakira/OpenUtau#330]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Now, for macOS we have dmg based installer. Hope that on Windows we can get an analogue, such as an MSI/EXE installer.

### Explains how to reproduce the bug

N/A

### OS & Version

Windows 7-11

### Logs

N/A

**Comment by oxygen-dioxide** [comment]
I have created a windows installer for OpenUtau. https://github.com/oxygen-dioxide/openutau-installer/releases
