### ISSUE TITLE
How to install plugin

### ISSUE THREAD

**Issue by juanjosse** [stakira/OpenUtau#331]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Cannot install a plugin like "Presamp". There is an empty folder in the installation called "Plugins", but there are no instructions or buttons for installing them.

### Explains how to reproduce the bug

N/A

### OS & Version

Windows 10

### Logs

N/A

**Comment by kokoropaint** [comment]
Presamp is not a traditional UTAU plugin and is not supported by OpenUTAU; it uses tricks that are specific to UTAU to work. As well, all of presamp's features can be recreated using OU's phonemizer system, and a few of OU's phonemizers can read presamp.ini files, so support for it isn't necessary.

To use other plugins, you drop the folder for the plugin into the Plugins folder at the root directory, then open your UST/create a new part and click `Part`->`Legacy Plugins`.
