### ISSUE TITLE
Invalid notes are no longer grayed out

### ISSUE THREAD

**Issue by nagotown** [stakira/OpenUtau#348]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Invalid notes are no longer grayed out. This makes it hard to spot notes that aren't in the oto, and you have to double check for them with View Phonemes.

![image](https://user-images.githubusercontent.com/35883871/168412060-e9fd9bd2-ed65-4609-a495-a6a7f4ae73f8.png)

### Explains how to reproduce the bug

Create a note with an alias that isn't in the oto. It will not gray out regardless of if it is valid or not.

### OS & Version

Windows 10

### Logs

N/A, happens every time, have also seen it on other user's clients

**Comment by nagotown** [comment]
was it not originally intended for a note to be grayed out if invalid?

**Comment by stakira** [comment]
I was but became non-trivial at some point. I figure by this time people might have already gotten used to the new norm.

**Comment by nagotown** [comment]
i'm used to it by now but it makes it harder to find invalid notes... and i figure it would probably be more inconvenient to make a plugin that locates invalid notes
