### ISSUE TITLE
When installing singer with a .zip/archive file (only option) it doesn't because Japanese text isn't Unicode.

### ISSUE THREAD

**Issue by 123happily** [stakira/OpenUtau#35]
I don't have a lot of experience with this, but UTAU taught me to recognise those garbled Japanese characters, and I get an error message full of them when trying to install an UTAU bank. I see other people installing one just by selecting the 'voice' folder in UTAU, or the oto.ini file, but I only have the option to choose a .zip or a .rar, so I'm stuck with this issue.

Here's the error message.
![Capture](https://user-images.githubusercontent.com/77481373/104694773-99dd7500-575b-11eb-86c1-c8c2540ce41a.PNG)

I feel like the easiest workaround is to go back to whatever file loading system you were using before (I might go back a few versions to do this myself), but then again you're the experts here.

I hope this is ok :) and I don't mean any annoyance by it, this program looks super promising and I can't wait to use it properly.

**Comment by stakira** [comment]
Just commited a fix. Please try again.
