### ISSUE TITLE
Refuses to play?

### ISSUE THREAD

**Issue by 123happily** [stakira/OpenUtau#36]
Sadly I have less helpful information than last time. I installed the older version of OpenUTAU (the one right before the file loading change, see my other post for that issue). I've figured out how to create notes and tracks and all that, and I've inputted a note and selected a singer BUT it won't play when I hit space, or the button at the top left.

Am I missing something? My resamplers are wrapped with another program to increase their speed but they work perfectly fine in UTAU (Even in Cadencii, to my surprise). The voice I'm using is multi-bank, is that an issue? Am I inputting the lyric wrong? I assumed the lyric input mirrors UTAU's. I put in 'a R' to test an end-breath, and it's a valid file for this UTAUloid.

Kind of stumped. The playback line doesn't even move, I can move it but it won't play.

I hope I'm not being too annoying.

**Comment by fgteev4000** [comment]
how did u fix it
