### ISSUE TITLE
oto.ini being incorrectly read

### ISSUE THREAD

**Issue by LH762** [stakira/OpenUtau#365]
### Acknowledgement

- [x] I have read Getting-Started and FAQ

### 🐛 Describe the bug

the notes are showing incorrectly on VCV voicebank
![Untitled](https://user-images.githubusercontent.com/74991447/171314250-64197c1b-3bc6-42d1-94f8-5e1f66991ca3.png)

and changing the encoding in the singers tab gives me an error
(Sorry for low res)
https://user-images.githubusercontent.com/74991447/171315179-a0d1cbb0-bff0-41dc-a5ff-50eecfc1c03d.mp4

here is a link to the voicebank I'm working on so you can try to get it to work for yourself
https://drive.google.com/file/d/1aflkGhGOQq4uPjcC8KKKvu-faiXHBbgj/view?usp=sharing

### Explains how to reproduce the bug

honestly it's just happening
the oto.ini was made with moresampler

Moresampler configs
![Screenshot (255)](https://user-images.githubusercontent.com/74991447/171315961-e4f2eafb-af91-49a1-af6d-cb98efb77bc1.png)
r

### OS & Version

Windows 10 64-bit

### Logs

I don't know what to put here

**Comment by nagotown** [comment]
did you check each encoding option?

**Comment by stakira** [comment]
Notepad says your oto is utf-8. Just click the three dots button and set encoding to utf-8.
