### ISSUE TITLE
linux .tar.gz - unziped, run OpenUtau from terminal - command not found

### ISSUE THREAD

**Issue by aum7** [stakira/OpenUtau#376]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

after downloading, unpacking, and running 'OpenUtau' from terminal, i get 
'command not found'
error

the install instructions for linux version therefore do not work as expected

thx for sharing
have fun
aum

### Explains how to reproduce the bug

download the 'linux-x64' version
unpack 
open terminal
navigate to unpacked folder
write 'OpenUtau' in terminal
hit enter

### OS & Version

linux mint 20.3

### Logs

na

**Comment by aum7** [comment]
ok, mea culpa
i used
https://github.com/HitCoder9768/OpenUtau-Installer-Linux/blob/main/install.sh
to install the openutau

if i run from ~$
~/.local/lib/OpenUtau/OpenUtau
it works fine

my bad, long-term windows user

have fun
aum

**Comment by Moriarty1024** [comment]
It is not working with me. The last line text of output is "IOT instruction (core dumped)  ~/.local/lib/OpenUtau/OpenUtau"
