### ISSUE TITLE
Singer installation only imports rounded otos

### ISSUE THREAD

**Issue by overdramatic** [stakira/OpenUtau#38]
I was installing some voice banks and realized that OpenUTAU only imports otos with round numbers.
I did a test with Number Bronze -leizi, one of the otos I went through a rounding plugin in Setparam and the others are original.

My suggestion is that the singer installation auto rounds this numbers or the possibility to have non-rounded oto import
![image](https://user-images.githubusercontent.com/68165064/105176718-5b054180-5b04-11eb-9d17-dc1e229c3ba6.png)
![image](https://user-images.githubusercontent.com/68165064/105177738-d9aeae80-5b05-11eb-90f5-9e8edd2c87c6.png)

**Comment by stakira** [comment]
Thanks for reporting. Should be fixed now.
