### ISSUE TITLE
Phonemizers error

### ISSUE THREAD

**Issue by shiroxq** [stakira/OpenUtau#381]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

When I try to use any phonemizer (I tried with EN to JA, Arpasing and English VCCV), the words I input are not phonemized at all (1st image).
This happens with any voicebank.

![errorr](https://user-images.githubusercontent.com/108075462/175314410-ac32d0e0-6d07-4df9-a337-0fba59254d89.PNG)

As you can see, the phonemes space is empty. No error message displays, but you can read it in the log.

### Explains how to reproduce the bug

1. Create a new track.
2. Select a singer.
3. Select a phonemizer.
4. Try to input words.
5. The phonemizer doesn't convert the words into phonemes.
[error example ustx.zip](https://github.com/stakira/OpenUtau/files/8967907/error.example.ustx.zip)

### OS & Version

Windows 7

### Logs

[log20220623.txt](https://github.com/stakira/OpenUtau/files/8967886/log20220623.txt)

**Comment by p0pstxr** [comment]
According to the log, it could be because you dont have ONNX Runtime properly installed, which helps the AI figure out how to decode the lyrics into phonemes. And while I don't know if it fully supports Windows 7, the website does say it could be possible. https://onnxruntime.ai/docs/reference/compatibility

**Comment by shiroxq** [comment]
> According to the log, it could be because you dont have ONNX Runtime properly installed, which helps the AI figure out how to decode the lyrics into phonemes. And while I don't know if it fully supports Windows 7, the website does say it could be possible. https://onnxruntime.ai/docs/reference/compatibility

What can I do in order to fix that?
