### ISSUE TITLE
Remove track Crash

### ISSUE THREAD

**Issue by overdramatic** [stakira/OpenUtau#39]
If I remove a track with a new part inside it, I got this crash report:
![image](https://user-images.githubusercontent.com/68165064/105180835-d1f10900-5b09-11eb-8984-e52add794fa0.png)
![image](https://user-images.githubusercontent.com/68165064/105180844-d61d2680-5b09-11eb-839e-43bf22a295bb.png)

But if I remove a track with no parts inside it, it don't crash and works normally

**Comment by overdramatic** [comment]
I got the same crash creating a new file. What I did:
Open OpenUtau
Create a New Track
Create a New Part
Delete the Track or create a new file (Ctrl+N)

Apparently this only works with unsaved/new files. If you open an ust and delete their part or create a new file, the crash did not occur

**Comment by stakira** [comment]
Thanks for reporting. Will not immediately but eventually fix it.
