### ISSUE TITLE
Can't install certain voicebank archives.  

### ISSUE THREAD

**Issue by JustAnotherUsera** [stakira/OpenUtau#42]
I'm trying to install compressed WinRar archives voicebanks like Fushi Murasaki, Gahata Meiji, and Bibi Jyougasaki but I keep on getting a error message like this.
![help](https://user-images.githubusercontent.com/83102489/115943496-e1b81a80-a475-11eb-9479-7f721ea9d964.PNG)

**Comment by stakira** [comment]
Should be fixed for Fushi Murasaki Cyan and Violet.
Not sure where to download Gahata Meiji or Bibi Jyougasaki. Please provide download links if they still don't work.
