### ISSUE TITLE
Don't open on Mac

### ISSUE THREAD

**Issue by Katatumuri0519** [stakira/OpenUtau#420]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

The message displayed that "This file is broken" when I try download OpenUtau. 
(I'm a foreigner, so my English is probably wrong.)

### Explains how to reproduce the bug

Open OpenUtau on Mac

### OS & Version

macOS Monterey 12.3.1

### Logs

Error accessing <private>. <private>

Invalid launch.

**Comment by stakira** [comment]
see https://github.com/stakira/OpenUtau/wiki/FAQ#macos-error-this-app-is-damaged-
