### ISSUE TITLE
Expression default values not working for Vogen singers

### ISSUE THREAD

**Issue by DSP-8192** [stakira/OpenUtau#425]
### Acknowledgement

- [x] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Default values of expressions have no effects on rendering results of Vogen singers.
For example, it can be seen from the two screenshots below that the same waveforms are generated with different default values of dynamics (curve) (-200 for the upper one and 80 for the lower one)
![image](https://user-images.githubusercontent.com/70532341/185768181-a627d001-d246-45cb-a7da-a31881211461.png)
![image](https://user-images.githubusercontent.com/70532341/185768213-2c5b861e-dfcf-441a-b0e5-34b4cf1c7f55.png)

### Explains how to reproduce the bug

1. Create a new track with a Vogen singer
2. Draw some notes on that track
3. Modify default values of any expressions.
![image](https://user-images.githubusercontent.com/70532341/185768939-245cb713-d623-4117-9a28-418bc042a44a.png)

### OS & Version

Windows 11

### Logs

08/20/2022 23:54:04 +01:00 : Information : undoGroup started
08/20/2022 23:54:04 +01:00 : Information : ExecuteCmd Configure expressions
08/20/2022 23:54:04 +01:00 : Information : undoGroup ended
08/20/2022 23:54:04 +01:00 : Information : SchedulePreRender
08/20/2022 23:54:04 +01:00 : Information : Publish notification Pre-render notification.
08/20/2022 23:54:04 +01:00 : Information : Publish notification Phonemized
08/20/2022 23:54:04 +01:00 : Information : Publish notification Phonemized
08/20/2022 23:54:04 +01:00 : Error : Part rendered. not on main thread
08/20/2022 23:54:04 +01:00 : Information : Publish notification Part rendered.

**Comment by oxygen-dioxide** [comment]
This issue might be due to the caching machanism. You can do some minor edits to the parameter to force refresh the render cache.
<img width="827" alt="image" src="https://user-images.githubusercontent.com/54425948/203903717-c8e24b35-3446-4082-92e8-b3fd0319bcf0.png">
Still this should be considered a bug. I'm working on it.
