### ISSUE TITLE
ENUNU on OpenUtau won't render past 03:34.6 per part

### ISSUE THREAD

**Issue by nagotown** [stakira/OpenUtau#429]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

When using ENUNU voicebanks on OpenUtau, parts that exceed approximately 03:34.6 will not render.
> ![image](https://user-images.githubusercontent.com/35883871/185827215-fb799fa2-c1e5-406a-adc0-5da167a201f8.png)
> **134 BPM**
---
> ![image](https://user-images.githubusercontent.com/35883871/185827245-6ac353cf-1ca7-4751-bb90-b60fe09c0b79.png)
> **134 BPM**
---
> ![image](https://user-images.githubusercontent.com/35883871/185830398-687af1d8-bf9f-49e2-8487-cab8e400292a.png)
> **120 BPM**

### Explains how to reproduce the bug

1. Create USTX file
2. Try to go past 03:34.6

> [enunu-no-render.ustx](https://cdn.discordapp.com/attachments/990152334254411786/1011106443052728421/enunu-no-render.ustx)

### OS & Version

Windows 10

### Logs

[log20220821.txt](https://github.com/stakira/OpenUtau/files/9390794/log20220821.txt)

**Comment by stakira** [comment]
Fixed in b2c5b15
