### ISSUE TITLE
OpenUtau just won't launch

### ISSUE THREAD

**Issue by ryutsutau** [stakira/OpenUtau#430]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Hello there!
So I've been having this bug basically since I started using OpenUtau.
I can open the .exe file without any problems after a fresh installation of the software. Once I close and try to re-open it, it just won't launch. It doesn't even show up in the task manager.
I try to replace the files, then Windows gives me the error, that I don't have permission to replace the files, even though I am on an admin account.
I have to re-start Windows and re-install OpenUtau every time I want to open it up, in order for it to work.

https://user-images.githubusercontent.com/111917856/186256631-99bb63cf-407b-4e99-989d-d6a7425f0949.mp4

### Explains how to reproduce the bug

Sadly I don't have the slightest idea on how to reproduce the issue. I checked logs, but it doesn't even generate one, once I try to open it.

### OS & Version

Windows 11

### Logs

Sadly it doesn't generate any logs, when I try opening it.

**Comment by kokoropaint** [comment]
Where is OU installed for you? If it's in program files or some other system directories then you're going to run into issues with permissions even if you're using an admin account. Try moving it to your desktop or your documents folder.
Not sure if that's the issue because usually people can't run the program at _all_, not just "after first boot", but it's worth trying.
You may also need to turn off cloud saving programs like Dropbox, OneDrive, etc. If you've never used one of these before it may still be related to OneDrive because it comes preinstalled on some Windows machines.

**Comment by ryutsutau** [comment]
I thought about that too. So I installed it on my 2nd hard drive in a seperate folder from all other stuff. It still keeps on happening.
I'm at the point where I just keep it open all the time.

**Comment by lselden** [comment]
@ryutsutau try right clicking on one of the files (especially the `.exe` file) and choosing "Properties" - check if it has an option to "Unblock File" - sometimes downloads from the internet aren't usable until you manually unblock them.

**If** that is the case you can use Powershell to bulk unblock the files in that folder *(replace `C:\Path\To\OpenUtau\` with the correct path)*:
```ps
Get-ChildItem -Path 'C:\Path\To\OpenUtau\' -Recurse | Unblock-File
```

The other option is to open a command prompt, navigate to the folder where you installed OpenUtau and try running the exe from there (google it if you aren't familiar with command prompt). That may get you some kind of error message.

**Comment by eetazeeba** [comment]
This sounds like a similar issue to #555. I have not tried the method described by @lselden, but check your 'Reputaion-based protection' settings. Specifically, "Potentially unwanted app blocking". This should allow the app to remain in place and prevent the permissions errors.
