### ISSUE TITLE
ENUNU note displacement

### ISSUE THREAD

**Issue by nagotown** [stakira/OpenUtau#431]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Notes when using ENUNU are being displaced on this ustx. Pretty sure it's a thing with the ustx because it works fine when importing the ust again.
![image](https://user-images.githubusercontent.com/35883871/186271244-a10d3e35-64ab-4e0d-9a45-3c00ebc5152c.png)

### Explains how to reproduce the bug

Used Amano Naoki AI, but it doesn't matter which voicebank is used.

> [ustx here](https://files.catbox.moe/9gaccr.ustx)

### OS & Version

Windows 10

### Logs

[log20220823.txt](https://github.com/stakira/OpenUtau/files/9410863/log20220823.txt)

**Comment by oxygen-dioxide** [comment]
I'm also facing this bug. The speed of my project is 139.5 bpm, but it seems that the project is treated as 140 bpm. Timing is correct in .tmp file (generated by OpenUTAU as ENUNU's input), but it is wrong in timing.lab (output by ENUNU)
<img width="960" alt="image" src="https://user-images.githubusercontent.com/54425948/201343925-d70e5a05-0d37-46a0-972d-a1703dc17457.png">
Voicebank: KanadeShiapre30k
OS: Windows 11
[My Project.zip](https://github.com/stakira/OpenUtau/files/9990378/My.Project.zip) (Here are my ustx, .tmp and timing.lab)

Besides, there is a bug in the current version of OpenUTAU that makes the ENUNU phonemizer not responding to singer changes (see https://github.com/stakira/OpenUtau/pull/541 ), so we may have to manually clear the cache before switching the singer.

**Comment by rokujyushi** [comment]
As for the tempo shift problem, it seems that rounding is performed when ENUNU converts UST to label information.
We've already found the part that's causing the problem, so we need to see if it works after we fix it.

**Comment by rokujyushi** [comment]
大元のpythonライブラリ(utaupy)の修正はまだされていませんが非公式のENUNUサーバーはこちらにあります。
The unofficial ENUNU server is available here, although the main python library (utaupy) has not yet been modified.

https://github.com/rokujyushi/ENUNU/releases/tag/v0.6.0-openutau_v0.2
