### ISSUE TITLE
OpenUtau not opening due to damage (macOS 12 Monterey Intel)

### ISSUE THREAD

**Issue by CYNDER0017** [stakira/OpenUtau#436]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

OK whenever I open OpenUtau, it just reports it as being damaged. I've tried to fix it but nothing seems to work. An relevant image is attached below.
<img width="1280" alt="Screenshot 2022-08-27 at 20 56 20" src="https://user-images.githubusercontent.com/112278417/187046069-88ac8cb9-cc22-4f75-8877-f446465d9b37.png">

### Explains how to reproduce the bug

1. Open OpenUtau on Mac. That's it.

### OS & Version

macOS Monterey 12.5.1

### Logs

Can not attach.

**Comment by AbnormalPoof** [comment]
`Q: macOS error "This app is damaged ..."
A: Truth is the OpenUtau mac build is not codesigned by Apple, which is a paid service. As a result macOS treats the app as unsafe.

One way to solve it is open a terminal and run xattr -rc /path/to/OpenUtau.
