### ISSUE TITLE
add a "what's new page" 

### ISSUE THREAD

**Issue by yotsuuba** [stakira/OpenUtau#443]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

OpenUTAU Updates almost everyday, and it would be useful to add a "What's new" Instead of keeping users in the dark about the added features. For example, I where to update and look around, I have to actively ask other's of a feature is new or not. 

### Explains how to reproduce the bug

.

### OS & Version

Windows 10

### Logs

.

**Comment by nagotown** [comment]
you can view the changelog here: https://github.com/stakira/OpenUtau/commits/master
each time there's an update, it automatically builds the app, so an update could be a bug fix you wouldn't notice
there are posts in the discord at #updates-news, but maybe someone could mirror those to discussions

**Comment by nagotown** [comment]
would it be appropriate to make a page for this on the wiki?

**Comment by stakira** [comment]
Not inappropriate but difficult to manage I suppose.

**Comment by oxygen-dioxide** [comment]
We can provide a link to Github version comparasion webpage in OpenUtau's update dialog. For example, [what's new in 0.1.36](https://github.com/stakira/OpenUtau/compare/build/0.1.27...build/0.1.36)
