### ISSUE TITLE
Add a option to keep note editor below track edtor. 

### ISSUE THREAD

**Issue by yotsuuba** [stakira/OpenUtau#444]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Option to keep the Note view from popping out into a new window and below the track editor; similar to vocaloid. 
If not on by default; By being in UI settings would be a welcome feature. 

### Explains how to reproduce the bug

n/a

### OS & Version

n/a

### Logs

n/a

**Comment by nagotown** [comment]
try `Tools > Layout`, i believe this is what you want?

**Comment by yotsuuba** [comment]
> try `Tools > Layout`, i believe this is what you want?

it is not.

**Comment by nagotown** [comment]
then could you elaborate? not really understanding since that would take care of the exact layout of vocaloid

**Comment by yotsuuba** [comment]
> then could you elaborate? not really understanding since that would take care of the exact layout of vocaloid

I am just asking for the option to have the note editor to not pop out into a new editing window, and instead stay below the track editor or in the same window.

I made a quick mock up to explain what i mean.

![image](https://user-images.githubusercontent.com/43102583/188261766-d79e0a22-f50b-48b7-a0b9-e372256b1d7a.png)

**Comment by nagotown** [comment]
Added by https://github.com/stakira/OpenUtau/pull/1910
