### ISSUE TITLE
OpenUtau Crashes when opening a UST

### ISSUE THREAD

**Issue by Astel123457** [stakira/OpenUtau#45]
I was trying to load a UST I got and OpenUtau crashes when opening the UST with a System.IndexOutOfRangeException Error

![image](https://user-images.githubusercontent.com/41224955/122448936-4a51de00-cf73-11eb-9924-3c97a819f61b.png)

The singer is Kasane Teto and her voicebank can be found here: http://kasaneteto.jp/en/voicebank.html

The UST I was trying to use:
[UST-Meltdown by Tanjiro Taidana.zip](https://github.com/stakira/OpenUtau/files/6672268/UST-Meltdown.by.Tanjiro.Taidana.zip)

**Comment by LovelyA72** [comment]
Having the same issue, was about to ask

**Comment by stakira** [comment]
Now should be fix for UST-Meltdown by Tanjiro Taidana.zip. Please try.

**Comment by Astel123457** [comment]
Thank you it works now :)
