### ISSUE TITLE
Invalid Key indicator format?

### ISSUE THREAD

**Issue by LeeTeionIRL** [stakira/OpenUtau#454]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

I open a specific ust made in a different version, it was working fine until i opened it in this new update. 
"Invalid key indicator format.
(Line: 3251, Col: 12, Idx: 98219) - (Line: 3251, Col: 12, Idx: 98219): Invalid key indicator format."

### Explains how to reproduce the bug

The voicebank im using can be found [here](https://www.youtube.com/watch?v=2rRehi6SYYE) , the only difference is that the oto has been updated since then. however, I do not believe that this is the problem.
[this is the ust file that i am currently working on,](https://www.mediafire.com/file/tnjrnpx8ay6ovlp/ma+ma+ma+ma+machine+gun+-+lee.ustx/file) i do not know how to recreate the issue.

### OS & Version

Windows 10

### Logs

2022-09-09 11:07:43.721 +10:00 [ERR] Failed to open files C:\Users\[name]\Downloads\Machine Gun\ma ma ma ma machine gun - lee.ustx
(Line: 3251, Col: 12, Idx: 98219) - (Line: 3251, Col: 12, Idx: 98219): Invalid key indicator format.

**Comment by LeeTeionIRL** [comment]
[log20220909.txt](https://github.com/stakira/OpenUtau/files/9532036/log20220909.txt)

**Comment by stakira** [comment]
https://github.com/aaubry/YamlDotNet/issues/719
Downgraded YamlDotNet to fix.
