### ISSUE TITLE
Unable to install Yufu Sekka Sasayaki-Drip VB using "Install Singer" option

### ISSUE THREAD

**Issue by AVK1216** [stakira/OpenUtau#459]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

When using the "install singer" option, it gives me an error saying "Operation is not valid due to the current state of the object." (I've attached the log to this post). It's possible that it's something wrong with this specific voicebank but I thought It'd be useful to report the bug just in case.

The 2 other Yufu VB's I downloaded Installed fine through the "install singers" option. I have tried installing the VB both on an ENG and JP locale, making sure to re-download the file and try extracting it when I changed the locale. During the Singer Setup and using the (Shift-JIS) option, everything looks correct, but when I click "install" it gives me the aforementioned error.

The only files that get extracted are: 
1. the "image" folder, which contains some extra character images and an image readme
2. 2 first 2 wav files and related frq files (_ああいあう.wav, _ああいあう切.wav, _ああいあう_wav.frq, _ああいあう切_wav.frq)
3.  the License.txt
4.  character.txt and character.yaml
5.  the oto.ini
6.  the prefix.map
7.  the preview image
8.  the ReadMe.txt

The file names also show up correctly.

### Explains how to reproduce the bug

1. Select the "install singer" option.
2. Select the Yufu Sekka ZIP file (Name of the ZIP file) -> 歌ユフ連続音04（ささやき‐ドリップ）.zip
3. Click Next on "Singer Setup" with (Shift-JIS) option.
4. Click Install on "Singer Setup" with (Shift-JIS) option.

Voicebank distro: http://sekkayufu.web.fc2.com/

DL instructions if you can't/have trouble reading JP and specifically to DL the VB that relates to this issue.

1. Click on "Library" at the top left of the webpage
2. Download "04（ささやき-ドリップ）", the link on the left is the main DL and the link after the "/" on the right is a mirror
3. The right link will bring you to axfc.net, the password for the file should be automatically applied but if not, it's "sekka"
4. Complete the captcha
5. Click the "Download2648691.zip" button
6. Click the "＜ダウンロードする | click here to start download. ＞" link
7. The download will automatically happen in 5 seconds, but if it doesn't click the blue link that says "こちら" and the DL will start.

### OS & Version

Windows 10

### Logs

[log20220912.txt](https://github.com/stakira/OpenUtau/files/9548336/log20220912.txt)

**Comment by GenroidKwame-Dev** [comment]
Hi. I've downloaded the vb as written here.
After testing on 7zip, there seems to be header and data errors on the zip file.
The mirror link didn't work for me so I couldn't try that so the one on the main link has a broken zip file

**Comment by AVK1216** [comment]
That's good to know, thank you!
