### ISSUE TITLE
Not playing back for some reason

### ISSUE THREAD

**Issue by LovelyA72** [stakira/OpenUtau#46]
On the latest branch, OpenUTAU refuses to playback the audio. I can see that It resamples and load caches just fine.
So my suspicion is that there might be a sound card selection issue when multiple sound cards are present on a system.

A good solution to this issue will be being able to select the desired sound card from a list of installed sound cards.

**Comment by stakira** [comment]
I'd look somewhere else first. I have several sound devices and never had issue with them. It should use the Windows default sound card.

**Comment by Astel123457** [comment]
I also had the same issue I tried multiple resamplers but still won't playback but will work with a VSQX or UST. Seems to be a USTX that causes the issue.

**Comment by 123happily** [comment]
Hi!
Just did a fresh install of OpenUtau and it's not playing back for me either, despite the bank being successfully installed and a correct lyric inputted (using namine ritsu). The playhead just refuses to move. there's no clear attempt to load a cache either

**Comment by Astel123457** [comment]
I think I may have found the issue:
OpenUTAU wants to use the default sound device but the current sound device does not match that so when OpenUTAU tries to play it will try to play through the wrong sound device(Most programs seem to have a way around that) but fail
I found a way to fix it on a user end and set the default sound device and make it work.
Follow these steps 
![image](https://user-images.githubusercontent.com/41224955/124549335-06792880-ddfd-11eb-9d54-e30b50438711.png)
Make sure that you set it to the one that you use the most 


Fyi: this worked for me but i don't know if it will work for you

**Comment by stakira** [comment]
Now it is possible to select playback device in preferences.
