### ISSUE TITLE
OpenUtau Crashes when editing USTX

### ISSUE THREAD

**Issue by Astel123457** [stakira/OpenUtau#47]
I have multiple USTX files that I have saved in an effort to change them from romaji to VCV but both crash when I try to edit them.

Error code:
![image](https://user-images.githubusercontent.com/41224955/123340977-2d8d4b80-d51b-11eb-90f7-c76c566fd47f.png)

I'm using the Kasane Teto voicebank

Here are the USTX's that both do this:
[Songs.zip](https://github.com/stakira/OpenUtau/files/6712458/Songs.zip)

**Comment by overdramatic** [comment]
I think it's because when you open a ustx, OpenUtau don't load the voicebank. You need to manually select the voicebank everytime you open the project

**Comment by Astel123457** [comment]
I made sure to have one selected and it still did that.

**Comment by stakira** [comment]
Ustx has been redesigned, and this issue should be fix now.
