### ISSUE TITLE
Proper release tags

### ISSUE THREAD

**Issue by orowith2os** [stakira/OpenUtau#472]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Currently, the binaries are on a rolling system. This puts a lot of (Linux) packages in a weird place, where no other build has the same package. This is particularly painful for reproducible builds, such as Flatpak, because each binary needs to be the same on all systems. This can't be done with the current release model.

### Explains how to reproduce the bug

There is a lack of numbered tags in the releases page.

### OS & Version

Linux

### Logs

*No response*

**Comment by orowith2os** [comment]
After some discussion on the Discord, release tags could be dealt with, like this:

Set a maximum of three numbered tags, they would go alongside Prerelease and Latest for a total of 5
Have the builds push to a new numbered tag and Latest, deleting the oldest of the numbered tags in the process 

Each numbered tag would only contain a Linux build, just to be sure that it doesn't overdo GitHub's limit on storage, and keep things tidy. Additional builds could be added as things progress, possibly, but there likely isn't much reason for that.

**Comment by stakira** [comment]
solved by 6d174f339a4f44caab5f45fdf8ec1ea364fab6f8 cc02814f7116050f80c74e24718051b35bcc8d80

**Comment by orowith2os** [comment]
A small cherry on top, could you make those tags provide Linux builds? Currently they only do source.
