### ISSUE TITLE
Error Shows Up When Attempting to Play the UST.

### ISSUE THREAD

**Issue by SpaceboyYT** [stakira/OpenUtau#473]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

When I press the play button, I get an error when trying to play the UST.

### Explains how to reproduce the bug

1. Go to the play button.
2. Click it.
3. Error shows up.
4. I used the Ashlyn Wallace 2S CANDYBAR Voicebank.
5. I got it off of this video: [https://www.youtube.com/watch?v=LCE7XTmsJ70](url)

### OS & Version

Windows 10 Version 21H2

### Logs

![Error](https://user-images.githubusercontent.com/78513604/190879980-753f8c9c-06ec-4875-8c0f-d9120e8eef95.png)

**Comment by GenroidKwame-Dev** [comment]
Try to update your OpenUtau. There might be something wrong with the resampler

**Comment by GenroidKwame-Dev** [comment]
Does this happen only with this specific ust and specific utau?

**Comment by SpaceboyYT** [comment]
This happens with any UTAU and any UST. The resampler is the problem. Do you know where to go to change the resampler?

**Comment by GenroidKwame-Dev** [comment]
On the track selection screen next to where you select the singer there is a gear icon where you can change the resampler and wavtool. It is under the S (Solo) icon

**Comment by Roberteto** [comment]
the problem is that it is missing dll.
the solution is to install Visual C++ .redistributable libraries.

https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
