### ISSUE TITLE
Crashes when opening "..." menu in singers (Ubuntu)

### ISSUE THREAD

**Issue by TELEK1NET1C** [stakira/OpenUtau#488]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

i was attempting to set the default phonemizer, but when i selected the "..." menu in the "Singers..." menu, the app entirely crashed. this seems to be an issue regardless of the voicebank used.

[here's a video for reference](https://user-images.githubusercontent.com/89629866/192126315-82df829e-7b2c-4f54-b20e-f2dff50c8172.webm)

### Explains how to reproduce the bug

1. Select "Singers..."
2. Select the "..." menu next to "Location"
3. The app should entirely crash

### OS & Version

Ubuntu 22.04

### Logs

[log20220924.txt](https://github.com/stakira/OpenUtau/files/9639928/log20220924.txt)

**Comment by Astel123457** [comment]
Do you have libfuse2 installed? Openutau expects libfuse2, which by default is no longer included in Ubuntu 22.04.

**Comment by TELEK1NET1C** [comment]
i do not, i'll install it as soon as i can get on my computer and report back.

**Comment by TELEK1NET1C** [comment]
it says i do have it installed? "libfuse2 is already the newest version (2.9.9-5ubuntu3)."
i think maybe another app i installed had it

**Comment by Astel123457** [comment]
Hmmm, it seems to be throwing an error for "libgbiplus". Do you have have that installed? If not, you could try running OpenUtau as administrator by using "sudo" and see if that works.

**Comment by TELEK1NET1C** [comment]
running `sudo ./OpenUtau` seems to run it in a different environment (light theme, no singers installed, nothing personalized), but! it does say libgdiplus is missing where the oto view would be, so i think that's the issue! i'll try to install it and see if that fixes my issues

**Comment by TELEK1NET1C** [comment]
yep, installing libgdiplus fixed it! thank you!!
