### ISSUE TITLE
Support for UTAU's Mode 1 Pitch Editor?

### ISSUE THREAD

**Issue by loidx86** [stakira/OpenUtau#494]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Has implementation of UTAU's Mode1 Pitch Editor (pictured below) been considered? The pitch drawing tool is cool. But, as someone with very shaky hands, free-handing pitches is really frustrating. I end up having to use both classic UTAU and OpenUtau for full tuning. Is it reasonable to ask for the pitch editor's inclusion in Open? Or has it already been added and I'm just missing it?

![jgislenkxk](https://user-images.githubusercontent.com/114616233/192873654-4703ea11-3762-4c36-8f85-948ba408aabd.jpg)

### Explains how to reproduce the bug

-

### OS & Version

-

### Logs

-

**Comment by GenroidKwame-Dev** [comment]
Use the pen tool to draw pitch like Mode2

Simply click on the pitch line to add pitch points

There's a demo on the readme and getting started pages

**Comment by GenroidKwame-Dev** [comment]
You can also pitch edit VOCALOID style using the + symbol

**Comment by loidx86** [comment]
Okay, I understand the example given on the 'getting Started' page. What i was asking about was the inclusion of _Mode 1's_ method. When right-clicking on a note in UTAU, a separate window can be opened by selecting 'Pitch' in Mode 1. This window allows for more precise control of pitch with points already set up. Will that function ever be included in OpenUtau?

**Comment by GenroidKwame-Dev** [comment]
We'll see how demanding it is I guess. I dunno many people who tune with Mode1 especially with differently styles leaning more towards SynthV and VOCALOID style of tuning

**Comment by BagelHero** [comment]
Admittedly, most people just use mode2 pitch bends. It's just less convoluted and it doesn't result in errors when fitting the UST to new singers.

_THAT SAID..._ It has been on the to-do list/requested list for a while to have **line**, **curve** and/or **smoothing/averaging** tools for the pitch drawing tool & PIT expression. Hopefully this will fill a similar need. Are there any specific features of the mode1 window that you really miss other than those 3?
