### ISSUE TITLE
how to select singer once it has been added to the settings ?

### ISSUE THREAD

**Issue by SeleDreams** [stakira/OpenUtau#5]
Hi, i've added a singer in the settings, and i'm currently trying to make it play a ust, but when i try to select a singer, the list is empty even though my utau has been added in the settings
is it a bug or do i have to do something special ?

**Comment by pikachuk** [comment]
i've been able to select a singer this time, but once i try to play a ust, the software crashes with a NULLREFERENCEEXCEPTION

**Comment by stakira** [comment]
OpenUtau was tested with only a few sound libraries. It’s unfortunate I haven't work on OpenUtau for quite a long time. If you can provide me more info about the exception, like which file and line, and which sound library, I may figure out something.

**Comment by pikachuk** [comment]
i'll post the library i tested and the line containing the error soon

**Comment by pikachuk** [comment]
https://www.mediafire.com/file/85gclqvy22ap4he/BugReport%20OpenUTAU.tar.gz
I've uploaded, this archive contains a screenshot of the error line, the ust and the utau

**Comment by pikachuk** [comment]
Did you find the possible problem ?

**Comment by stakira** [comment]
Seems the UST uses hiragana as lyric in the notes. However the singer oto is set up with romaji as alias. Since they don't match, the software cannot find any wav files to use.

**Comment by pikachuk** [comment]
I've tried with a romaji ust it didn't change anything

**Comment by stakira** [comment]
Just made a small change to handle this situation. It should render fine but ignore the missing alias in oto now. Could you please try it? You could check message like `[Error] Cannot find phoneme in note ...` in Visual Studio output to see which notes are missing.

**Comment by pikachuk** [comment]
Ok, thanks, i'll try it

**Comment by pikachuk** [comment]
It took me time but i finally got the time to test, it still doesn't work, but i did some debugging with visual studio and found out the bug is caused by a nullreference exception because RenderAsync is called with a null "IResamplerDriver engine" argument
i could try to fix it but i don't really know the value that it should have
