### ISSUE TITLE
Failed to parse block

### ISSUE THREAD

**Issue by overdramatic** [stakira/OpenUtau#50]
I tryed loading a UST and I got this error
![image](https://user-images.githubusercontent.com/68165064/129367537-2f6d8438-4ffa-46f3-a014-d100d4bf554c.png)

```
[#0042]
Length=240
Lyric=j i
NoteNum=52
PreUtterance=
Velocity=130
Intensity=100
Modulation=10
PBS=-18;
PBW=036,44,34
PBY=-18.6,-21.4,
Envelope=0,10,60,0,100,100,0
```

I think it's the ";" alone on PBS, I have the same problem with another note and I added "0.0" in front of it and it worked.
I tryed removing the ";" on this note and it passed, now the error is on another note with the same PBS (PBS=-18;)

**Comment by stakira** [comment]
Made a fix a little earlier. Could you try the latest build?

**Comment by overdramatic** [comment]
Oh yeah. I already tried, it's working now. Thanks!
