### ISSUE TITLE
new vb does'nt appear on the list of voices

### ISSUE THREAD

**Issue by FloraRenji** [stakira/OpenUtau#509]
### new voice desapear on the list

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Hey, 
for a while I can not add new vb on openutau, at least it installs but does'nt appear in the program. 
-I did the manipulation from the singer folder to the program window, the vb is installed, normal, but is'nt displayed in the list... I restart the program, the same, I can't find it..
-I did a sorting to see if it was because I had a lot of voices (40~), nothing changed... 
-I tried with other voicebanks, the same error...
Also, a friend told me that having duplicate names on the list was not normal, I don't know if the source of the problem is the same, but here it's less disturbing.

I hope you can help me

### Explains how to reproduce the bug

1- put a "voicebank" in "singer"
2- open "openutau"
3- pick the "Zip file" up and put it in "openutau"
4- "openutau" is working to install the "voicebank"
5- open the "voice liste" and nothing change

### OS & Version

windows 10

### Logs

idk

**Comment by oxygen-dioxide** [comment]
According to openutau's [documantation](https://github.com/stakira/OpenUtau/wiki/FAQ#voicebank-doesnt-show-up-in-openutau-even-if-its-in-the-singer-folder), please make sure the voicebank includes a character.txt file with a line starting with "name=(voicebank's name)".

However, I think that Openutau should check if the voicebank contains a character.txt. If it doesn't, Openutau should either warn the user or automatically add a character.txt.
