### ISSUE TITLE
If resamples crashes, OpenUtau stucks on "isPlaying" and won't render anything untill reopen the program

### ISSUE THREAD

**Issue by HeidenBZR** [stakira/OpenUtau#52]
If resampler crashes (easy way to break it is to make oto with no white space), then resampler gives no result

here Data is not null, but empty:
![image](https://user-images.githubusercontent.com/32395982/130138017-332cc584-c2e3-4dbf-b620-7073eb827e43.png)
The render stucks, and pressing Play again won't do a thing, because PlaybackManager.renderTask still exists and does nothing.

**Comment by stakira** [comment]
Now playback shows exception to user.
