### ISSUE TITLE
OpenUTAU won't open up on Mac since its "Damaged"

### ISSUE THREAD

**Issue by FuminP** [stakira/OpenUtau#522]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Hello, so i tried to download OpenUTAU after i cleaned up storage but this time when i try to open the app it says "OpenUtau"  is damaged and cannot be opened. You should move it to the garbage", i tried with older versions i had on my old drive of OpenUTAU but the same error popped up

(Here's the message but its in spanish-)
![image](https://user-images.githubusercontent.com/115967557/196088557-f780a199-41cc-4f17-9063-13ea8bc8a09e.png)

I honestly don't know if its an error because of my system version or is the .dmg itself

Thanks.

### Explains how to reproduce the bug

1- Copy the app to "Applications" folders
2- Try to launch it
3- Error message pop up

### OS & Version

MacOS Big Sur 11.6.8

### Logs

(idk where is it on macos sorry T^T)

**Comment by nagotown** [comment]
https://github.com/stakira/OpenUtau/wiki/FAQ#macos-error-this-app-is-damaged-
