### ISSUE TITLE
What is Audio Backend ?

### ISSUE THREAD

**Issue by SybaycatV5** [stakira/OpenUtau#523]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

It is not a bug - or maybe there is some - I would like to know what that feature does. It contains 2 parameters, which are Automatic and PortAudio.

### Explains how to reproduce the bug

That one Audio Backend is located in OpenUtau, Tools, Preferences.

### OS & Version

Windows 10

### Logs

_

**Comment by sdercolin** [comment]
It handles your audio output,
select one, and click the audio test button, if it is plays the sound then it's okay
