### ISSUE TITLE
OpenUtau Cant Play,

### ISSUE THREAD

**Issue by ImLoadingUuU** [stakira/OpenUtau#529]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

OpenUtau Play Button not working

### Explains how to reproduce the bug

Go to >
Click >
Nothing Happend

### OS & Version

OS X Ventura

### Logs

10/22/2022 09:00:32 +08:00 : Information : StartPlayback at 00:00:00
10/22/2022 09:00:31 +08:00 : Information : StartPlayback at 00:00:00
10/22/2022 09:00:31 +08:00 : Information : StartPlayback at 00:00:00

**Comment by sdercolin** [comment]
Tested with Ventura and it's working.
Please check
1. Audio settings in preferences
2. Singer/Engine is correctly set
3. There are valid notes to be played

**Comment by ImLoadingUuU** [comment]
yes,
audio backend
"PortAudio"
singer/engine is correctly seted
Renderer is CLASSIc.

**Comment by Just-a-silly-guy** [comment]
Yea same. Does anyone know what causes this?

**Comment by LichArklow** [comment]
same, does anyone have a solution?
