### ISSUE TITLE
AUR installer not working

### ISSUE THREAD

**Issue by todthetoad** [stakira/OpenUtau#538]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

I keep trying to use the aur installer but it keeps failing downloading the package

### Explains how to reproduce the bug

Go to Terminal
type yay -S openutau-installer

### OS & Version

arch 6.0.2

### Logs

curl: (22) The requested URL returned error: 404
===> ERROR: Failure while downloading https://github.com/stakira/OpenUtau/releases/download/OpenUtau-Latest/OpenUtau-linux-x64.tar.gz
Aborting...

**Comment by stakira** [comment]
Not officially supported. Please contact whoever did that.
