### ISSUE TITLE
Add the ability to set preview stereo pan

### ISSUE THREAD

**Issue by nfrid** [stakira/OpenUtau#543]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Not a bug but a feature request. I've never written a C# code so I can't just go right in to implement it myself, but I'd really love to have it. 👽

Add a setting for a track (singer) or part to change its preview stereo panorama, so we can for example make one singer go only to the left channel or 50% to the right (i.e. 0.5 volume to the left and 1.5 to the right). It would drastically improve the experience making back vocals and stuff.

### Explains how to reproduce the bug

--

### OS & Version

i use Arch btw 🤡

### Logs

--

**Comment by stakira** [comment]
Thanks for contributing!
