### ISSUE TITLE
OpenUtau file dialogs use a preferred GTK filepicker rather than portals

### ISSUE THREAD

**Issue by orowith2os** [stakira/OpenUtau#548]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

When doing an action that requires file dialogs, OpenUtau opens up a GTK file dialog, not using a portal. This can break the experience inside of Flatpak, and other sandboxed environments. 

### Explains how to reproduce the bug

Run OpenUtau inside of a flatpak or any other environment and open a file dialog with it.

### OS & Version

Linux

### Logs

N/A

**Comment by stakira** [comment]
File dialog is provided by Avalonia, OpenUtau has no direct control of what is used.
