### ISSUE TITLE
Opening OpenUTAU gives out an error, exe file is deleted instantly

### ISSUE THREAD

**Issue by LeeTeionIRL** [stakira/OpenUtau#555]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

I open OpenUtau.exe, and it pulls up
![this error message](https://user-images.githubusercontent.com/104409047/202813671-e20c0fc0-95a2-4fa4-b75a-42b22eacb7ac.PNG)
The exe then immediately deletes itself. 

### Explains how to reproduce the bug

Running open utau?!?!?

### OS & Version

Windows 10

### Logs

No logs available. It's a brand new download of openutau

**Comment by magenefanz** [comment]
i had delt with that issue before . idkvhow to fix it tho :(

**Comment by sleepy7777** [comment]
I just ran into this issue myself after updating to .991. Mine was do to my antivirus thinking OpenUTAU was maleware. You may need to go into your antivirus and put in an exception.

**Comment by eetazeeba** [comment]
Sounds like Windows 'Reputaion-based protection'. I've had issues with torrent clients being removed in a similar fashion before. Short term solution is disabling "Potentially unwanted app blocking" if you are on Windows 11.

![image](https://user-images.githubusercontent.com/46096410/208572874-64440e7e-2c1f-4f49-93bc-4f4c9eca6c45.png)
