### ISSUE TITLE
Provide AppImage builds for linux?

### ISSUE THREAD

**Issue by m1karii** [stakira/OpenUtau#566]
I think it 'd be nice to have AppImage builds as they are more user friendly / easier to integrate into the system and are what people are used to among other reasons

As a side note: ability to create blank issues on github would be appreciated as not everything is a bug

**Comment by Vector-frame** [comment]
But an installation version was created in AppImage, I just don't remember where to download it, I even suggested it myself. The issue is that nowadays I find it more advantageous to use Flatpak due to the issue of security and almost automatic updating of the responsible user's linux distribution.

**Comment by Vector-frame** [comment]
One user even went so far as to say that they were creating a manifest and things that Flathub asks them to add software to them but I don't know how they are currently proceeding with this issue.

**Comment by m1karii** [comment]
hi @Vector-frame 
i personally find flatpak bloated. i have 3 apps installed through it and its almost 8 gigs.
although i acknowledge that each distribution method has its advantages (perhaps except snaps) and disadvantages and should be used by users accordingly (thats why i have those 3 flatpak apps - all gaming related)
another reason i suggested appimage is because like you said StAkira has already read on appimage and did required steps to produce builds in that format at some point, whereas in case of flatpaks they would have to read on it and start implementing it from scratch so it should be far easier to get appimages, which i also prefer

**Comment by KawaneRio** [comment]
I would love to have an AppImage as well, since OpenUTAU just fails to build on my system...

**Comment by Vector-frame** [comment]
An Arch Linux user developed this method to install the program (and its logo) for the terminal:

https://hitcoder.tubs.wtf/Posts/openutau/

**Comment by Vector-frame** [comment]
> Oi@Vector-frame Eu pessoalmente acho flatpak inchado. Eu tenho 3 aplicativos instalados por ele e seus quase 8 shows. embora eu reconheça que cada método de distribuição tem suas vantagens (talvez exceto snaps) e desvantagens e deve ser usado pelos usuários de acordo (é por isso que tenho esses 3 aplicativos flatpak - todos relacionados a jogos) , outro motivo pelo qual sugeri appimage é porque, como você disse, StAkira tem já li sobre appimage e fiz as etapas necessárias para produzir compilações nesse formato em algum momento, enquanto no caso de flatpaks eles teriam que ler e começar a implementá-lo do zero, então deve ser muito mais fácil obter appimages, que eu também prefiro

A pricípio Flatpak pode causar irritações por supostamente consumir mais espaço em disco mas é muito além disso, inclusive os programas nessa forma de instalação nem sempre consomem mais espaço, uma vez que as bibliotecas de alguns componentes são compartilhadas porque na maioria das vezes um programa é executado com os mesmos componentes que outros baixados. Esse artigo explica bem as diferenças entre os formatos e explica bem o que é e como funciona de fato o formato flatpak: 

https://theevilskeleton.gitlab.io/2022/05/16/response-to-flatpak-is-not-the-future.html

**Comment by m1karii** [comment]
>
