### ISSUE TITLE
What the heck happened

### ISSUE THREAD

**Issue by CloudyLikesVocal-Synths** [stakira/OpenUtau#595]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Whenever I try to press the space bar in the OpenUTAU editor, the note wont play.

### Explains how to reproduce the bug

idk

### OS & Version

Mac OS Ventura

### Logs

[log20221218.txt](https://github.com/stakira/OpenUtau/files/10726914/log20221218.txt)

**Comment by restedwaves** [comment]
you sure you're using the right phonemizer?
