### ISSUE TITLE
Can't change lyrics

### ISSUE THREAD

**Issue by HeidenBZR** [stakira/OpenUtau#6]
In the midi editor, after I open this lyric input, I still can't change it: it just ignores my keyboard input, i can't write anything in it; what do I do wrong? (this is an imported ust)
![image](https://user-images.githubusercontent.com/32395982/37297276-43ff2af4-262e-11e8-93f3-e462ff5e8bfa.png)

**Comment by stakira** [comment]
You did nothing wrong. It worked before but after some time, maybe because of .net version change, it doesn't work anymore. I couldn't figure out why yet. Meanwhile ctrl+c and ctrl+v works in that input box.

**Comment by stakira** [comment]
Should be fixed now.
