### ISSUE TITLE
my chinese voicebank doesnt work with the ZH CVVC phonemizer???

### ISSUE THREAD

**Issue by buffin-muffin** [stakira/OpenUtau#616]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

ive been having this problem when i record a chinese CVVC voicebank where no matter what reclist i use my voicebank never works with the phonemizer??? ive been using haru.jpgs reclist and i dont think it's that because other chinese utaus use the same reclist and work perfectly fine with the phonemizer so if anyone could help me with this issue that would be much appreciated!

### Explains how to reproduce the bug

N/A
![Capture](https://user-images.githubusercontent.com/108843311/221332135-cceb56d5-a2ed-4c75-a70f-aa9551e07094.PNG)

### OS & Version

windows 10 and version 1.36.0

### Logs

N/A

**Comment by lottev1991** [comment]
Does your voicebank have a presamp.ini file? If not, you could copy it from another Chinese CVVC voicebank if necessary. The phonemizer relies on this presamp.ini file.
