### ISSUE TITLE
An error about not finding the voicebank files.

### ISSUE THREAD

**Issue by aocriup233** [stakira/OpenUtau#624]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

After installing an UTAU voicebank like Getting-Started pages , I tryed to make the first project of openUtau. When I pressed the play button, I got an error about not finding the voicebank files. I tryed to unistall the voicebank (delete the file folder in the Singers) and reinstalled the voicebank. There was no error reported this time, but my voicebank still didn't work.

### Explains how to reproduce the bug

1. install a voicebank
2. create the tracks and add notes
3. press the space bar to play the notes
4. error shows up

### OS & Version

Windows 11

### Logs

![FF016135AE79933A9B12EA3454C0B8AF](https://user-images.githubusercontent.com/108775587/222943942-03c34d16-6bd3-4ba1-82e6-96bc4c17e9a1.jpg)

**Comment by oxygen-dioxide** [comment]
Open file explorer and check if "E:\openutau\Singers\new OTTO\NEW OTTO\a.wav" exists

**Comment by aocriup233** [comment]
> Open file explorer and check if "E:\openutau\Singers\new OTTO\NEW OTTO\a.wav" exists

yes,i checked it.it's over there.
