### ISSUE TITLE
It doesn't play. Even if I hit the play button or space

### ISSUE THREAD

**Issue by LichArklow** [stakira/OpenUtau#625]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

I've tried to use open utau for the first time and no matter which voicebank I use it never plays the song. I've put the resampler and wavtool but they couldn't make it play neither. I'm indeed stuck at this moment and don't know what to do.

### Explains how to reproduce the bug

I just can't make it play.
I tried Matsudoppoiyo and Sukane Tei's voicebanks.

### OS & Version

Windows 10

### Logs

.

**Comment by LichArklow** [comment]
![image](https://user-images.githubusercontent.com/127043553/222975810-12d36528-b33e-4610-9fda-48a3d4746f57.png)

**Comment by oxygen-dioxide** [comment]
Could you provide a full screenshot of your main window and piano roll, and openutau's log file? (Help → Open Logs Location)

**Comment by LichArklow** [comment]
![image](https://user-images.githubusercontent.com/127043553/224493733-19556d68-e716-4dc8-b227-0417ea13e498.png)
![image](https://user-images.githubusercontent.com/127043553/224493758-6a0edd29-eb87-4b2f-b4dd-d30f85bdd52e.png)

**Comment by LichArklow** [comment]
aaa it's fixed with Tei, but guess Matsudoppoiyo's voicebank contains katakana rather than hiragana..

**Comment by LichArklow** [comment]
Though I cannot play the sound of my own utau :(

**Comment by Lauren042** [comment]
To convert katakana to hiragana or romaji, try using one of the tools explained [here](https://github.com/stakira/OpenUtau/wiki/Phonemizers#ja-vcv-japanese-vcv). Are you able to upload the logs themselves?

**Comment by Lauren042** [comment]
Also, could we get a screenshot of the piano roll? (Double click on the main arrangement, which is the blue rectangle with white MIDI notes in it)
