### ISSUE TITLE
Failed to Render.Index was outside the bounds of array.

### ISSUE THREAD

**Issue by hacheeseeater** [stakira/OpenUtau#637]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Just updated open utau today and I think the update fucked my ust.
![atch](https://user-images.githubusercontent.com/129284226/228519579-59deae26-a0ca-44ec-bc34-515dcdc54157.png)

### Explains how to reproduce the bug

1.Update open utau to the newest version.
2.Load your ust.
3. ????
4. PROFIT!!!

### OS & Version

Windows 10

### Logs

[log20230329.txt](https://github.com/stakira/OpenUtau/files/11100075/log20230329.txt)

**Comment by wistpotion** [comment]
This is probably fixed by PR #636. Or what do you think @lennyservant?
