### ISSUE TITLE
wordliner.lib not there?

### ISSUE THREAD

**Issue by NANAEKO** [stakira/OpenUtau#643]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

hello! ive come across a bug that has something to do with the file wordliner.lib or something, it seems like its missing. i checked the files and there's no file there! please help

### Explains how to reproduce the bug

1. open already existing project
2. press play

### OS & Version

macOS 12.6.4

### Logs

[log20230405.txt](https://github.com/stakira/OpenUtau/files/11163447/log20230405.txt)

**Comment by BagelHero** [comment]
Apologies for the inconvenience, this bug should now be fixed. Please try the latest version and let us know if you still encounter this issue!
