### ISSUE TITLE
Damaged .DMG?

### ISSUE THREAD

**Issue by sour-supreme** [stakira/OpenUtau#654]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

First time posting here + using GitHub, but I tried opening a .UST and noticed that OpenUTAU would close every time I did that. So I uninstalled it and installed the latest version (0.1.56), but with this new install I am unable to open OpenUTAU at all.

I use a M1 Max MacBook Pro, and have not had any issues prior to this. I know that new versions come out rather frequently so hopefully this issue is resolved in the next version.

Thank you for all your hard work on this amazing program! :^)

### Explains how to reproduce the bug

1. Installed latest version of OpenUTAU from Github (v0.1.56).
2. Opened it.
3. It doesn't open and I get the error message.

### OS & Version

macOS Ventura 13.2.1

### Logs

"OpenUtau.app" is damaged and can't be opened. You should move it to Trash.

**Comment by OfficialCRUGG** [comment]
Try opening a terminal and running the following two commands:
```
cd /Applications
xattr -cr OpenUtau.app
```
Not entirely sure why, but this issue happens with a lot of apps and this command usually fixes it. At least it did for me.

**Comment by sour-supreme** [comment]
> Try opening a terminal and running the following two commands:
> 
> ```
> cd /Applications
> xattr -cr OpenUtau.app
> ```
> 
> Not entirely sure why, but this issue happens with a lot of apps and this command usually fixes it. At least it did for me.

Okay, so that helped me open it! But now I have a different seemingly unrelated problem (which I actually noticed happening the last time I opened v0.1.55 before updating to 0.1.56 the first time):

I open OpenUTAU, drag in a .UST file, and then after a few seconds it closes unexpectedly. Alternatively if I just start a new track and start drawing notes, it will stay open a little longer, but as soon as I try and play them back it will close.

From my limited knowledge, that tells me that something might be wrong with the resampler somehow? I didn't mess with anything outside of updating OpenUTAU though so I'm not sure what happened.

At this point I have uninstalled and reinstalled OpenUTAU v0.1.55 and v0.1.56 and after using your code I get it open but it eventually closes.

**Comment by lottev1991** [comment]
There's a solution for this on the [FAQ](https://github.com/stakira/OpenUtau/wiki/FAQ).

**Comment by zephyraowl** [comment]
i have the same issue but instead of wanting me to move it to trash, it wants me to eject the disc image.
I've tried running the terminal commands that people tell me to use, but they do not work. maybe im not running them correctly because I've never tried to run a command before.
