### ISSUE TITLE
Voice Color (CLR) does not work

### ISSUE THREAD

**Issue by sieconlake** [stakira/OpenUtau#660]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Hello. I have been using OpenUTAU for close to five months now, and every single time I have tried using the Voice Color feature it has not worked as intended. I would set everything up per the tutorial, and then once I tried selecting the specific voice color in the piano roll it simply would not do anything at all - the note still sounded the same. This error has persisted across many different UTAU voicebanks and .ust/.ustx files. A short list of voicebanks I have tried (and failed) to use voice color with:

- Kasane Teto (all voicebanks)
- VAI (Normal/Soft)
- Gekiyaku (all voicebanks)
- MAGPIE (DEATH/BRAIN)
- Tohoku Kiritan (Normal/Soft)
- Matsudappoiyo (Retake heart, Retake normal, Retake quiet, Retake sing)
- Namae Shirezu (Normal/18-37)

I do not know what I am doing wrong or why it is not working. Any help would be appreciated.

### Explains how to reproduce the bug

1. Open OpenUtau
2. Follow the steps to use voice color as indicated in the many tutorials available online
3. Open the Piano Roll
4. Change the Voice Color by switching, for example, from "" to DEATH (in MAGPIE's case)
5. Play the note
6. No change at all is applied

### OS & Version

Windows 10

### Logs

[log20230416.txt](https://github.com/stakira/OpenUtau/files/11243083/log20230416.txt)

**Comment by BagelHero** [comment]
If you are still encountering this issue, it may help to attach a screenshot of your voice color windows as well as your piano roll where the option to change voice color on some notes is on, and perhaps your track header.

Thank you in advance.

**Comment by lottev1991** [comment]
Which phonemizer are you using?
