### ISSUE TITLE
Singers won't load after updating to v0.1.90.0

### ISSUE THREAD

**Issue by aerodynamxx** [stakira/OpenUtau#694]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

After updating OpenUtau to v0.1.90.0, hen I open a USTX or UST, the song loads, but when I try to select the singer, nothing happens. When I go to the 'Singers' window, none of the singers appear. In the files, the singer files are untouched. The preferences window also does not work as it just crashes the application once I click on it.

### Explains how to reproduce the bug

1. Update OpenUtau to v0.1.90.0 via the startup prompt
2. Open a USTX/UST (or just open the application)
3. Try to select a singer (or open the singer window)

### OS & Version

Windows 11

### Logs

[log20230514.txt](https://github.com/stakira/OpenUtau/files/11472468/log20230514.txt)
^^^

**Comment by BagelHero** [comment]
Sorry, this likely has to do with the bug mentioned at the top of the [Release Notes](https://github.com/stakira/OpenUtau/wiki/Release-Notes). The likely fix has been addressed, it just needs to be merged. Sorry for the inconvenience.
