### ISSUE TITLE
singers wont load in ( v0.1.90.0)

### ISSUE THREAD

**Issue by kislet** [stakira/OpenUtau#695]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

When i open a USTX none of the singers load, and when i try to upload more they dont show up in the singers tab.
![image](https://github.com/stakira/OpenUtau/assets/133595412/94532a6a-7c94-460a-8565-2e16a70dd4c7)
![image](https://github.com/stakira/OpenUtau/assets/133595412/2ae218bd-3058-4997-9568-3c1f8c11fc22)

### Explains how to reproduce the bug

Update OpenUtau to v0.1.90.0 via the startup prompt
Open the application
Open a UST or USTX
Try to select a singer (or open the singer window)

### OS & Version

Windows 10

### Logs

[log20230514.txt](https://github.com/stakira/OpenUtau/files/11472524/log20230514.txt)

**Comment by BagelHero** [comment]
Sorry, this likely has to do with the bug mentioned at the top of the [Release Notes](https://github.com/stakira/OpenUtau/wiki/Release-Notes). The likely fix has been addressed, it just needs to be merged. Sorry for the inconvenience.
