### ISSUE TITLE
singers not loading in

### ISSUE THREAD

**Issue by ineedusts** [stakira/OpenUtau#696]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

when i updated to the newest OU ver., my sigers did not load in.

### Explains how to reproduce the bug

1 update to new ver.
2 open OU
3 try to select singer

### OS & Version

windows 10

### Logs

[log20230514.txt](https://github.com/stakira/OpenUtau/files/11472796/log20230514.txt)

**Comment by BagelHero** [comment]
This likely has to do with the bug mentioned at the top of the [Release Notes](https://github.com/stakira/OpenUtau/wiki/Release-Notes). The fix has been addressed, it just needs to be merged, but sorry for any inconvenience this has caused.
