### ISSUE TITLE
singers not loading

### ISSUE THREAD

**Issue by Fish-Alicious** [stakira/OpenUtau#697]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

after updating to v0.1.90.0 when i try to select a singer, it doesnt show up
all the singers i already had installed were still in the singer folder but do not show up as a selectable singer
i have also tried re-installing them and this did not work
when i installing a new singer that i didnt previously have, it shows up in the singers folder but isnt selectable

### Explains how to reproduce the bug

1. update openutau to v0.1.90.0
2. add a track
3. click "select singer"

### OS & Version

Windows 10

### Logs

[log20230514.txt](https://github.com/stakira/OpenUtau/files/11473001/log20230514.txt)

**Comment by BagelHero** [comment]
This likely has to do with the bug mentioned at the top of the [Release Notes](https://github.com/stakira/OpenUtau/wiki/Release-Notes). I'm pretty certain the fix has been addressed, it just needs to be merged. Sorry for the inconvenience.
