### ISSUE TITLE
Problem with NETFramework Version

### ISSUE THREAD

**Issue by RaynerHandrian** [stakira/OpenUtau#7]
I get a little error when opening your project in Visual Studio 2017,, it says.

`The reference assemblies for framework ".NETFramework,Version=v4.6.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.`

Well, I have installed the .NETframework, but version 4.7.2, I can't install version 4.6.1 because I already use the latest version.

**Comment by stakira** [comment]
.Net frameworks should be able to co-exist. Try install 4.6.1 from [here](https://www.microsoft.com/net/download/dotnet-framework-runtime)
As an alternative, you may try to target 4.7.2, which I never tried.
