### ISSUE TITLE
Singers will not load, Preferences menu will not open and crash open utau, and render button will not appear after update 1.90

### ISSUE THREAD

**Issue by sleepy7777** [stakira/OpenUtau#701]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

When opening up Open UTAU you will not be able to select a singer from the main screen or in the singer menu. When you try to open preferences menu open UTAU will spin for a moment then crash. When you are in the main screen the render button will not show or let you change the render engine. 

### Explains how to reproduce the bug

Singer will not load error 1

1. Open open utau
2. Click the plus button on the main screen 
3. Click on select singer, nothing happens

Singer will not load error 2
1. Open open utau
2. Select Tools
3. Select singer, Singers will not show up and the drop down and locatin button will not work

Preferences menu crash
1. Open open utau
2.  Select Tools
3. Select the Preferences menu. system spins then closes

Render will not show up
1. Open open utau
2. Click the plus button on the main screen 
3. Hover over blank section and select render appears but when you click on it or the gear next to the location nothing happens. 

### OS & Version

Windows 10 version 22H2

### Logs

[log20230514.txt](https://github.com/stakira/OpenUtau/files/11473131/log20230514.txt)

**Comment by Decocana** [comment]
ive been having the same issues too

**Comment by BagelHero** [comment]
This likely has to do with the bug mentioned at the top of the [Release Notes](https://github.com/stakira/OpenUtau/wiki/Release-Notes). Someone has patched it and compiling from source now functions as expected for users in the discord, it just needs to be merged. Sorry for the inconvenience.
