### ISSUE TITLE
OpenUtau don't read the oto.ini right

### ISSUE THREAD

**Issue by JorgeTS20** [stakira/OpenUtau#703]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

When I write a word or a phoneme and I press play, the synth makes other sound example I write [ma] and the synth say [a m]. I check the oto.ini configurations and its right and I test the voicebank in the classic UTAU and the word sounds right, I try to use the CVVC phonemizer for japanese. Please help me 7u7

### Explains how to reproduce the bug

1.- Use OpenUtau v0.1.90.0
2.-Choose an japanese voicebank
3.-put a phoneme [ma, ba, da,] or two like [ba ba, ma e, a u, etc.]
4.-Play it

### OS & Version

OS: Windows 10 Home Single Language Version: 21H2

### Logs

05/14/2023 21:32:54 -06:00 : Information : Publish notification Part rendered.
05/14/2023 21:32:52 -06:00 : Information : StartPlayback at 00:00:01.1875000
05/14/2023 21:32:50 -06:00 : Information : Publish notification Phonemized
05/14/2023 21:32:50 -06:00 : Information : Publish notification Pre-render notification.
05/14/2023 21:32:50 -06:00 : Information : undoGroup ended
05/14/2023 21:32:50 -06:00 : Information : ExecuteCmd Change notes lyric
05/14/2023 21:32:50 -06:00 : Information : undoGroup started
05/14/2023 21:32:50 -06:00 : Information : ま
05/14/2023 21:32:49 -06:00 : Information : [ま]
05/14/2023 21:32:47 -06:00 : Information : Publish notification Pre-render notification.
05/14/2023 21:32:47 -06:00 : Information : undoGroup ended
05/14/2023 21:32:47 -06:00 : Information : undoGroup started
05/14/2023 21:32:47 -06:00 : Information : Publish notification Pre-render notification.
05/14/2023 21:32:47 -06:00 : Information : undoGroup ended
05/14/2023 21:32:47 -06:00 : Information : undoGroup started
05/14/2023 21:32:46 -06:00 : Information : Publish notification Pre-render notification.
05/14/2023 21:32:46 -06:00 : Information : undoGroup ended
05/14/2023 21:32:46 -06:00 : Information : Publish notification Phonemized
05/14/2023 21:32:46 -06:00 : Information : ExecuteCmd Change vibrato length
05/14/2023 21:32:46 -06:00 : Information : ExecuteCmd Change 1 notes duration
05/14/2023 21:32:46 -06:00 : Information : Publish notification Phonemized
05/14/2023 21:32:46 -06:00 : Information : ExecuteCmd Change vibrato length
05/14/2023 21:32:46 -06:00 : Information : ExecuteCmd Change 1 notes duration
05/14/2023 21:32:46 -06:00 : Information : Publish notification Phonemized
05/14/2023 21:32:46 -06:00 : Information : ExecuteCmd Change vibrato length
05/14/2023 21:32:46 -06:00 : Information : ExecuteCmd Change 1 notes duration
05/14/2023 21:32:46 -06:00 : Information : Publish notification Phonemized
05/14/2023 21:32:46 -06:00 : Information : ExecuteCmd Change vibrato length
05/14/2023 21:32:46 -06:00 : Information : ExecuteCmd Change 1 notes duration
05/14/2023 21:32:46 -06:00 : Information : Publish notification Phonemized
05/14/2023 21:32:46 -06:00 : Information : ExecuteCmd Change vibrato length
05/14/2023 21:32:46 -06:00 : Information : ExecuteCmd Change 1 notes duration
05/14/2023 21:32:46 -06:00 : Information : Publish notification Phonemized
05/14/2023 21:32:46 -06:00 : Information : ExecuteCmd Change vibrato length
05/14/2023 21:32:46 -06:00 : Information : ExecuteCmd Change 1 notes duration
05/14/2023 21:32:46 -06:00 : Information : ExecuteCmd Move 1 notes
05/14/2023 21:32:45 -06:00 : Information : Publish notification Phonemized
05/14/2023 21:32:45 -06:00 : Information : ExecuteCmd Change vibrato length
05/14/2023 21:32:45 -06:00 : Information : ExecuteCmd Change 1 notes duration
05/14/2023 21:32:45 -06:00 : Information : Publish notification Phonemized
05/14/2023 21:32:45 -06:00 : Information : ExecuteCmd Change vibrato length
05/14/2023 21:32:45 -06:00 : Information : ExecuteCmd Change 1 notes duration
05/14/2023 21:32:45 -06:00 : Information : Publish notification Phonemized
05/14/2023 21:32:45 -06:00 : Information : ExecuteCmd Change vibrato length
05/14/2023 21:32:45 -06:00 : Information : ExecuteCmd Change 1 notes duration
05/14/2023 21:32:45 -06:00 : Information : Publish notification Phonemized
05/14/2023 21:32:45 -06:00 : Information : ExecuteCmd Change vibrato length
05/14/2023 21:32:45 -06:00 : Information : ExecuteCmd Change 1 notes duration
05/14/2023 21:32:45 -06:00 : Information : Publish notification Phonemized
05/14/2023 21:32:45 -06:00 : Information : ExecuteCmd Change vibrato length
05/14/2023 21:32:45 -06:00 : Information : ExecuteCmd Change 1 notes duration
05/14/2023 21:32:45 -06:00 : Information : Publish notification Phonemized
05/14/2023 21:32:45 -06:00 : Information : ExecuteCmd Change vibrato length
05/14/2023 21:32:45 -06:00 : Information : ExecuteCmd Change 1 notes duration
05/14/2023 21:32:45 -06:00 : Information : Publish notification Phonemized
05/14/2023 21:32:45 -06:00 : Information : ExecuteCmd Change vibrato length
05/14/2023 21:32:45 -06:00 : Information : ExecuteCmd Change 1 notes duration
05/14/2023 21:32:45 -06:00 : Information : Publish notification Phonemized
05/14/2023 21:32:45 -06:00 : Information : ExecuteCmd Change vibrato length
05/14/2023 21:32:45 -06:00 : Information : ExecuteCmd Change 1 notes duration
05/14/2023 21:32:45 -06:00 : Information : Publish notification Phonemized
05/14/2023 21:32:45 -06:00 : Information : ExecuteCmd Change vibrato length
05/14/2023 21:32:45 -06:00 : Information : ExecuteCmd Change 1 notes duration
05/14/2023 21:32:45 -06:00 : Information : Publish notification Phonemized
05/14/2023 21:32:45 -06:00 : Information : Publish notification Phonemized
05/14/2023 21:32:45 -06:00 : Information : ExecuteCmd Change vibrato length
05/14/2023 21:32:45 -06:00 : Information : ExecuteCmd Change 1 notes duration
05/14/2023 21:32:45 -06:00 : Information : ExecuteCmd Add note
05/14/2023 21:32:44 -06:00 : Information : undoGroup started
05/14/2023 21:32:43 -06:00 : Information : Created bitmap 925, 60
05/14/2023 21:32:43 -06:00 : Information : Publish notification Pre-render notification.
05/14/2023 21:32:43 -06:00 : Information : undoGroup ended
05/14/2023 21:32:43 -06:00 : Information : Publish notification Load part
05/14/2023 21:32:43 -06:00 : Information : Publish notification Select expression vel
05/14/2023 21:32:43 -06:00 : Information : Publish notification Select expression eng
05/14/2023 21:32:43 -06:00 : Information : Publish notification Select expression clr
05/14/2023 21:32:43 -06:00 : Information : Publish notification Select expression pitd
05/14/2023 21:32:43 -06:00 : Information : Publish notification Select expression dyn
05/14/2023 21:32:42 -06:00 : Information : Publish notification Select expression vel
05/14/2023 21:32:42 -06:00 : Information : Publish notification Select expression dyn
05/14/2023 21:32:42 -06:00 : Information : Publish notification Select expression eng
05/14/2023 21:32:42 -06:00 : Information : Publish notification Select expression dyn
05/14/2023 21:32:42 -06:00 : Information : Publish notification Select expression clr
05/14/2023 21:32:42 -06:00 : Information : Publish notification Select expression dyn
05/14/2023 21:32:42 -06:00 : Information : Publish notification Select expression pitd
05/14/2023 21:32:42 -06:00 : Information : Publish notification Select expression dyn
05/14/2023 21:32:42 -06:00 : Information : Publish notification Select expression dyn
05/14/2023 21:32:42 -06:00 : Information : undoGroup started
05/14/2023 21:32:42 -06:00 : Information : Publish notification Pre-render notification.
05/14/2023 21:32:42 -06:00 : Information : undoGroup ended
05/14/2023 21:32:42 -06:00 : Information : undoGroup started
05/14/2023 21:32:41 -06:00 : Information : Publish notification Pre-render notification.
05/14/2023 21:32:41 -06:00 : Information : undoGroup ended
05/14/2023 21:32:41 -06:00 : Information : Publish notification Phonemized
05/14/2023 21:32:41 -06:00 : Information : undoGroup started
05/14/2023 21:32:41 -06:00 : Information : Publish notification Pre-render notification.
05/14/2023 21:32:41 -06:00 : Information : undoGroup ended
05/14/2023 21:32:41 -06:00 : Information : ExecuteCmd Add part
05/14/2023 21:32:41 -06:00 : Information : undoGroup started
05/14/2023 21:32:40 -06:00 : Information : Publish notification Pre-render notification.
05/14/2023 21:32:40 -06:00 : Information : undoGroup ended
05/14/2023 21:32:40 -06:00 : Information : ExecuteCmd Change phonemizer
05/14/2023 21:32:40 -06:00 : Information : ExecuteCmd Change singer
05/14/2023 21:32:40 -06:00 : Information : undoGroup started
05/14/2023 21:32:36 -06:00 : Information : Publish notification Pre-render notification.
05/14/2023 21:32:36 -06:00 : Information : undoGroup ended
05/14/2023 21:32:36 -06:00 : Information : Publish notification Set track 0 panning to 0
05/14/2023 21:32:36 -06:00 : Information : ExecuteCmd Add track
05/14/2023 21:32:36 -06:00 : Information : undoGroup started
05/14/2023 21:32:18 -06:00 : Error : Failed to connect domain https://hub.fastgit.xyz

**Comment by BagelHero** [comment]
This likely has to do with the bug mentioned at the top of the [Release Notes](https://github.com/stakira/OpenUtau/wiki/Release-Notes). The fix has been addressed, it just needs to be merged. 

Please update with the full .txt file attached if this continues after going back a version or once this bug has been patched. Sorry for the inconvenience!
