### ISSUE TITLE
Order of expressions is not remembered once OpenUtau is closed

### ISSUE THREAD

**Issue by garlicbreadislife** [stakira/OpenUtau#717]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

The five expressions which are found in the piano roll menu remain as I had set them after the program is initialized, even when I choose a different file. However, if I close and reopen the program, the default order is restored.

I understand the Getting Started page states that expressions are saved per-project, but what I don't understand is why the program can't allow me to remember the exact order of the expressions I wish to use in the piano roll menu, even after closing OpenUtau and opening it again.

I see that the 5 expressions at the top of the list correspond with the 5 in the piano roll. I would love nothing more than to be able to rearrange items in the list found in Tools>Expressions to my liking. This is honestly my biggest pet peeve about OpenUtau; I would use the software a lot more if I didn't have to set my preferences every time I start it.

### Explains how to reproduce the bug

n/a

### OS & Version

win10

### Logs

n/a

**Comment by garlicbreadislife** [comment]
Found a workaround by using templates, but it's still a bit annoying compared to just clicking "new."

(and one more idea... don't know where to put feature requests, sorry) I find myself making empty tracks and parts on the timeline to use as .txt notes, but this looks awfully sloppy. Would it be possible to implement a feature which allows one to write text notes on a per-track basis?

**Comment by lottev1991** [comment]
For now, expressions are saved per USTX file rather than globally.

**Comment by BagelHero** [comment]
Yes, currently it is not possible to keep visible expressions persistent. We do have both these features suggested as feature requests on the discord I believe. Both would be good, even if keeping expressions per USTx remains.
