### ISSUE TITLE
Program just won't open no matter how many times I try

### ISSUE THREAD

**Issue by Jooters** [stakira/OpenUtau#721]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Worked fine before but then one day just wouldn't open. When I check task manager, it shows openutau for a second and then it shows windows problem reporting and they both vanish from the manager.

### Explains how to reproduce the bug

no clue

### OS & Version

windows 10

### Logs

doesnt generate any new logs

**Comment by lottev1991** [comment]
Delete ``prefs.json`` and try again.
