### ISSUE TITLE
Pitches are not reproduced accurately

### ISSUE THREAD

**Issue by maiko3tattun** [stakira/OpenUtau#729]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

There is an ustx that plays at a different pitch than the one shown in the piano roll.
And the problematic note and the next note often generate different pitches.

Sorry for the machine translation.

### Explains how to reproduce the bug

- This ustx is an import of ust.
- No matter how many times I play it back, I get the same result.
Also, changing the phonemizer gives the same result.
- It only happens with classic renderer, third party resampler and does not reproduce with worldline.
- If I change the voice bank, the pitch changes a little, but it is still strange.
- Adding points may somehow improve the situation. (The points were added at voiceless consonants, so the result shouldn't be much different.)
- I don't know if this is related, but the problematic pitch parameters are different in the original ust and in the imported ustx.
![image](https://github.com/stakira/OpenUtau/assets/130257355/0a62a312-4c2f-485b-bfb0-412ab88d95fc)
The left is ust and the right is ustx.
Shouldn't the x in ustx be 105?
- The problem occurred in the first [さ].
![image](https://github.com/stakira/OpenUtau/assets/130257355/5cf72d21-35ca-437b-9d3e-00caf0d27d9a)
[ブーゲンビリア test.zip](https://github.com/stakira/OpenUtau/files/11600452/test.zip) ust and ustx included

### OS & Version

Win10Home, OU 0.1.126 and before

### Logs

[log20230530.txt](https://github.com/stakira/OpenUtau/files/11600445/log20230530.txt)

**Comment by sunnyhenry123** [comment]
me too. it's a serious problem that made me can't use it
