### ISSUE TITLE
preference option crashes the program

### ISSUE THREAD

**Issue by vapayt** [stakira/OpenUtau#754]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Wanted to change preference and it just crashed.

### Explains how to reproduce the bug

1.Go to "Tools" tab
2.Click on "Preferences..."

### OS & Version

Windows 10

### Logs

[log20230623.txt](https://github.com/stakira/OpenUtau/files/11844359/log20230623.txt)

**Comment by oxygen-dioxide** [comment]
Navigate to the `prefs.json` file in your OpenUtau folder structure, and remove the line `"language": "axaml"`, and save.

This is a bug when upgrading from version 0.1.90. See [Release Notes](https://github.com/stakira/OpenUtau/wiki/Release-Notes#0191-05-15-2023) for more details.
