### ISSUE TITLE
WORLDLINE-R audio distortion when changing gender factor curve's default value

### ISSUE THREAD

**Issue by SeleDreams** [stakira/OpenUtau#756]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

i am working on a project using Hitsuboku Kumi french. when setting the gender factor default value to a negative value like -15, it seems like the audio gets heavily distorted. I think something wrong happens in the function that adjusts the gender factor in worldline.

https://github.com/stakira/OpenUtau/assets/16335601/e8c256b0-a6e6-4c07-a67c-35fd69d68201

This bug does not occur when the gender factor value is set to 0

### Explains how to reproduce the bug

[ChordProg.ustx.zip](https://github.com/stakira/OpenUtau/files/11856070/ChordProg.ustx.zip)
- Download the project
- open the project in openutau (with the french dictionary and hitsuboku kumi french set for all tracks)
- make sure the default gender expression value is -15 for the curve and that all tracks use worldline-r

### OS & Version

MacOS 13.4

### Logs

[log20230624.txt](https://github.com/stakira/OpenUtau/files/11856082/log20230624.txt)

**Comment by 0x24a** [comment]
<img width="1775" alt="Screenshot 2024-06-29 11 36 29" src="https://github.com/stakira/OpenUtau/assets/96947247/2400d7e2-efb3-4628-8a23-5fa3089c740c">

it still exists

**Comment by JMii63** [comment]
it still hasn’t been fixed lol

**Comment by 0x24a** [comment]
please reopen this, my eardrums are keep getting destroyed randomly

**Comment by SeleDreams** [comment]
the worst part is that although it's an open source project, for some reason, WORLDLINE-R is NOT open source. Only the owner @stakira has the actual ability to fix this

**Comment by JMii63** [comment]
@stakira please fix this
