### ISSUE TITLE
'Failed to render" issue

### ISSUE THREAD

**Issue by margaretjoynson706** [stakira/OpenUtau#770]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

![Bug](https://github.com/stakira/OpenUtau/assets/121367479/dc11bb98-8f19-4ff8-85c9-86fd0b1301be)

### Explains how to reproduce the bug

1. Download KII 2.0 (https://www.youtube.com/watch?v=IY0j18nhB28).
2. Move the voicebank into the Singers folder and unzip it. 
3. Tried using this voicebank with this UST: .
[OverMeError.zip](https://github.com/stakira/OpenUtau/files/11995715/OverMeError.zip)
4. Used the Default setting with Worldline resampler and convergence wavtools. I also tried different resamplers and phenomizers, but this did not resolve the issue. 
5. Error message is displayed.
6. The voicebank works in UTAU, so I'm assuming the issue is with OpenUTAU. 

### OS & Version

Windows 10

### Logs

[log20230709.txt](https://github.com/stakira/OpenUtau/files/11995720/log20230709.txt)

**Comment by oxygen-dioxide** [comment]
Don't directly unzip the file into the singers folder. Please delete the voicebank and install by dragging the voicebank .zip file into the openutau window. See https://github.com/stakira/OpenUtau/wiki/FAQ#singer-installation--share-voicebanks-with-utau
