### ISSUE TITLE
OpenUtau won't open on Macos Ventura

### ISSUE THREAD

**Issue by MastermindR** [stakira/OpenUtau#786]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Upon trying to install OpenUTAU, the file states that: “OpenUtau” is damaged and can’t be opened. You should move it to the Trash. File was opened on Ventura Beta Version 13.5

### Explains how to reproduce the bug

1. Download the OSx file
2. Open the file
3. Was told that "Cannot open due to unidentified developer" and go into settings to allow permission
4. Try to open the file again
5. Be told: “OpenUtau” is damaged and can’t be opened. You should move it to the Trash."
6. File is moved to trash

### OS & Version

Ventura Beta Version 13.5

### Logs

There are no logs, I can't open the app

**Comment by oxygen-dioxide** [comment]
Try running `xattr -rc /Applications/OpenUtau.app` in terminal. See https://github.com/stakira/OpenUtau/wiki/FAQ#macos-error-this-app-is-damaged- for detail.
