### ISSUE TITLE
No note-level pitch

### ISSUE THREAD

**Issue by JapanYoshi** [stakira/OpenUtau#812]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

For example, on FL Studio, you can change the pitch of the whole note from the bottom of the piano roll.
![image](https://github.com/stakira/OpenUtau/assets/8707990/120fe1f6-874f-4a3a-aee1-c7c1f3272357)

However, all I can find on OpenUtau is an imprecise curve editor.
![image](https://github.com/stakira/OpenUtau/assets/8707990/992ee9d2-914e-4741-ae9d-b23d9f0b2973)

Due to the song being in a different tuning other than 12-tone equal temperament, I want to, for example, select all B notes and lower it down by 16 cents, or even lower the entire song by a few cents because the instrumental isn't in A440.

### Explains how to reproduce the bug

1. Create an UTAU track
2. Add a melody
3. Try to lower an entire note evenly by a set number of cents

### OS & Version

Windows 10

### Logs

[log20230828.txt](https://github.com/stakira/OpenUtau/files/12450762/log20230828.txt)

**Comment by JapanYoshi** [comment]
I've tried editing the "Pitch deviation (PITD)" expression to stop it from being of type "Curve", but it could not be edited. I created a new expression with the same abbreviation but as "Numeric", but the editor errored out and stopped me from editing it further or deleting it.

**Comment by oxygen-dioxide** [comment]
You can add a t flag which is supported by moresampler, tn_fnds and f2resamp:
<img width="447" alt="image" src="https://github.com/stakira/OpenUtau/assets/54425948/92f466fe-f876-447b-94ce-c7d3835b3945">

---

OpenUtau (and the other singing voice synthesizers) don't support non-12-tone equal temperament natively, because the pitch curves of real-world human singing voices already have a uncertainty larger than the difference of various tuning systems, so tuning system switching isn't needed.

**Comment by oxygen-dioxide** [comment]
Human voice is different from musical instrument. There are complex singing techniques in each note. That's why the PITD should be curve

**Comment by JapanYoshi** [comment]
The thing about human voice is that there’s nothing keeping it stuck to 12TET. Well-trained singers can entrain themselves to the harmonics of the instrumentals, which OpenUTAU can make easier to simulate by making it possible to set a fine pitch value to every note.

Currently, OpenUTAU sounds more out of tune than a human singer would with my instrumental, because a computer needs to be told that it’s not in A440, while a human doesn’t know what an A sounds like without a reference pitch.

Yes, I understand your point that PITD should be a curve to account for the most possibilities, but I haven’t touched it in any of my songs so far, only the pitch bend/ease controls between notes. For my workflow, it is a much cleaner method to retune the vocals to match the instrumental than to try to draw as steady and flat a line as I can with my mouse, starting and ending exactly where the notes do, at the exact height representing the number of cents I want to tune each note, one by one.

**Comment by JapanYoshi** [comment]
Update: The renderer I'm using doesn't support the T expression.

This would've been such a non-issue if 1) I could zoom into the expression bar and 2) I had a hotkey to prevent the mouse cursor from moving up and down (i.e. holding the same expression value as the mouse moves left and right).
![image](https://github.com/stakira/OpenUtau/assets/8707990/5eecdd9f-a512-4dd5-9df2-a4c2a52bd871)

**Comment by lottev1991** [comment]
Make sure to select the Classic renderer on the left, instead of Worldline-R. Then click on the gear icon to change the resampler to a compatible one (aka TIPS or f2resamp, as mentioned).

**Comment by JapanYoshi** [comment]
So no fine pitch control, then.

**Comment by lottev1991** [comment]
It seems you haven't read my comment.

**Comment by oxygen-dioxide** [comment]
I think this is indeed an unsolved issue.
We don't really have note-level fine pitch. We only have phoneme-level one.

**Comment by oxygen-dioxide** [comment]
https://github.com/stakira/OpenUtau/discussions/921
