### ISSUE TITLE
Moresampler does not make any sound (not rly a bug, i'm just dumb)

### ISSUE THREAD

**Issue by Adumbwithnoknowledge** [stakira/OpenUtau#814]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

So. i did everything as required. moresampler.exe in Resamplers and Wavtools folders and moreconfig.txt in the Wavtools folder. I chose Classic and put moresampler as resampler and wavtool. It shows some rendering process and piano roll scrolls, but is silent. Wordline is working. Audio tracks are playing and i hear the beep in the sound test. so there is no problem with audio devices. Cache is literally just Teto's samples from her voicebank, not sure if that's okay. Aaaaand there is bunch of errors in the log files
Moresampler ver. 0.8.4

Maybe i'm just stupid and did smth wrong? i read the FAQ and the getting started, but i see nothing from there what i could did wrong. I tried creating new projects, still wasn't working so there is no issue with the ustx...
BTW if i set the Wavtool as simple, it works, which is weird
 

### Explains how to reproduce the bug

1. select moresampler as resampler AND wavtool
2. enjoy the silence lol

### OS & Version

windows10

### Logs

[log20230830.txt](https://github.com/stakira/OpenUtau/files/12474738/log20230830.txt)

**Comment by lottev1991** [comment]
It's probably not related to this issue, but you should put moreconfig.txt in the Resamplers folder. Make sure ``resampler-compatibility`` is set to ``on``.

Also, please do not install OpenUtau on your desktop, this will cause permission issues.

**Comment by Adumbwithnoknowledge** [comment]
Sorry for late answer; 
So, i reinstalled utau directly on C: (not sure if that was clever lol), moved moreconfig in the resamplers folder, also tried to put moreconfig in both folders, - nothing changed

**Comment by lottev1991** [comment]
I'd either install OpenUtau in the Documents folder or on a different drive if available. The C drive in general has a lot of  permission issues, so what you did now does not solve your problem.
