### ISSUE TITLE
Suggestions Regarding Arpasing & Suffixes

### ISSUE THREAD

**Issue by Eternal-Aurath** [stakira/OpenUtau#87]
Just found this engine and I'm super duper impressed with it! I've been hoping for community vocal synth stuff to advance to the point of just inputting English lyrics for years now, and it's super cool to see it happen finally!

I made some replies on UtaForum with these suggestions, but I'm not sure if you'll see them there so I'll drop them here too. My first suggestion is adding native support for the numbered duplicates that Arpasing banks sort of rely on. I was able to get some of them working by making an edited dictionary, but some issues with that still cropped up.

For instance, if I used "ih2" and wanted to follow it with an "n" sound, it refused to use the "ih n" transition, instead using "- n" which of course sounded choppy. One of the banks I tested with also doesn't have a lot of VV because he was recorded with an older Arpasing list. 

So adding support for the numbered duplicates and letting us choose from them in the phoneme editor would be super cool, maybe read the duplicates from the oto, since all banks might not be the same. 

I also think letting us change the phonemes selected in general would be cool, beyond being able to input them. Such as selecting a "V" configuration instead of "- V" or visa versa. Allowing for CV crossfades with "V" or "CV" configurations would be cool too, if a bank doesn't have certain transitions, again like the one I tested with.

I'd also like to suggest a "suffix" support of some kind, for banks that have extra expressions/pitches that are activated by a unique character, like Teto's WHISPER or SAKEBI voicebanks. It'd be cool if we could pick from those in the phoneme editor too, or have some other way of assigning a suffix to a note. 

Being able to assign a specific pitch to a place it wouldn't normally be used would be cool, too, again maybe through the phoneme editor or some other menu. A lot of people like to do that for more flexibility and whatnot.

And my final suggestion is being able to select a region and then play only that region. My computer seems to render in real-time pretty slowly, so I often wind up with the vocals lagging a lot as they try to play, so working more in "chunks" would be cool.

All in all, I'm really excited to see where this project goes! It's so cool!

**Comment by stakira** [comment]
These are know issues. Will work on them once cross-platform version is complete.

**Comment by Eternal-Aurath** [comment]
Awesome! I'm excited to see where this goes!
