### ISSUE TITLE
OpenUTAU crashes opening certain USTs

### ISSUE THREAD

**Issue by GamerzHell9137** [stakira/OpenUtau#884]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

For whatever reason some USTs crash the application when they are opened.

### Explains how to reproduce the bug

1. Drag and Drop UST to OpenUTAU
2. Change UTAU
3. Crash

### OS & Version

Windows 10 64bit

### Logs
[log20231011.txt](https://github.com/stakira/OpenUtau/files/12870548/log20231011.txt)

**Comment by oxygen-dioxide** [comment]
Could you provide a ust file that makes your OpenUtau crash?

**Comment by pseudo-producer** [comment]
What types of ust crash? Are they USTs with lots of Plug-ins, portamentos and other features?

**Comment by GamerzHell9137** [comment]
@pseudo-producer @oxygen-dioxide Here's the UST in question.

I've seen a lot more USTs just outright crash whenever the voicer is changed but dont remember which one's were, if i find any more i'll report back.

[Crash.zip](https://github.com/stakira/OpenUtau/files/12907409/Crash.zip)

**Comment by GamerzHell9137** [comment]
No updates on this one i guess?
