### ISSUE TITLE
Nothing plays

### ISSUE THREAD

**Issue by janSuta01** [stakira/OpenUtau#891]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Suddenly, OpenUtau won't play anything. Everything has worked normally in the past. If I press space, or click play, nothing happens. I know it is trying to play, since I can't scroll (like when it is actually playing). I have tried using different usts that have worked before, and creating new ones. But nothing will work. 

### Explains how to reproduce the bug

I don't know how to replicate this bug. I have tried to get rid of it using different voicebanks, different usts, and I have tried to reinstall the program. None of these changed anything.

### OS & Version

macOS 10.14, OpenUtau v0.1.158.0

### Logs

[log20231018.txt](https://github.com/stakira/OpenUtau/files/13045403/log20231018.txt)

**Comment by lottev1991** [comment]
Did you select the correct audio output device in Settings?

**Comment by Postconceptlab** [comment]
me too the play button doens't work when i clikc play nothing happens

**Comment by lottev1991** [comment]
I will say it agaib: make sure you have the correct audio device selected.

**Comment by janSuta01** [comment]
> I will say it again: make sure you have the correct audio device selected.

Sorry, I didn't see your response. I had selected the correct audio device, and the audio test was working as normal. The arrow that normally moves when playing didn't move, so I think there was another issue going on. But the problem is somehow fixed now. Not sure how, as I haven't touched the program in a week. Thanks for the advice anyways!

**Comment by lottev1991** [comment]
Oh don't worry about it, that second message wasn't really aimed at you. I'm happy the problem got solved though!

**Comment by IsmailMid** [comment]
> > I will say it again: make sure you have the correct audio device selected.
> 
> Sorry, I didn't see your response. I had selected the correct audio device, and the audio test was working as normal. The arrow that normally moves when playing didn't move, so I think there was another issue going on. But the problem is somehow fixed now. Not sure how, as I haven't touched the program in a week. Thanks for the advice anyways!

Haven't touched thee program in a week and it works? I have the same issue! I'll try that too.
