### ISSUE TITLE
会添加 Linux 发行版与便携设备的支持吗？

### ISSUE THREAD

**Issue by funnypro** [stakira/OpenUtau#9]
其实 Linux 是重点了，似乎那上面没一个原生支持的

**Comment by tcyrus** [comment]
The main issue is that this application uses WPF, which is not implemented in Mono or .NET Core (for Linux).

**Comment by Phundrak** [comment]
As explained in issue #4 in details, no GNU/Linux support is planned. Wine might work, I wonder if it is possible to use Steam’s proton too. In any case, binaries should be compiled on Windows.

**Comment by stakira** [comment]
Unfortunately no
