### ISSUE TITLE
Doesn't work on M2 Mac, Ventura.

### ISSUE THREAD

**Issue by everythingability** [stakira/OpenUtau#914]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Hi, after stepping around Apple's Security nonsense, I ran the app from my /Applications folder and got this.

<img width="319" alt="image" src="https://github.com/stakira/OpenUtau/assets/96276/425ac632-9601-43f1-8ca8-f94622438db0">

### Explains how to reproduce the bug

Run app

### OS & Version

13.5.1

### Logs

nope

**Comment by oxygen-dioxide** [comment]
https://github.com/stakira/OpenUtau/wiki/FAQ#on-macos-when-i-try-to-run-openutau-it-says-this-app-is-damaged

**Comment by everythingability** [comment]
Thank you.
