### ISSUE TITLE
Humming voicebanks don't install properly

### ISSUE THREAD

**Issue by orangecarnation** [stakira/OpenUtau#919]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

When trying to install a humming voicebank, comprised of ん at various pitches, none of them are showing up in OpenUtau.  They are shown in the Singer Install menu when selecting the right encoding, the Singer folder has all the audio files in it, but the program doesn't pull any of them, in the editor or in the Singers menu.

### Explains how to reproduce the bug

The voicebank I'm trying to use is the Momone Momo "hanauta" one [here](http://st-zako.la.coocan.jp/momomirror/).

### OS & Version

Windows 10

### Logs

[log20231111.txt](https://github.com/stakira/OpenUtau/files/13326903/log20231111.txt)

**Comment by lottev1991** [comment]
Does the oto have aliases? If not, I believe there's now a function that you can enable which makes OpenUtau read directly from the filenames instead.
