### ISSUE TITLE
Render/Resampler bug

### ISSUE THREAD

**Issue by AKKIKKIRA** [stakira/OpenUtau#920]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

When using more than one resampler, an error appears with the following information:
Worldline.dll
This file does not have an application associated with it to perform this action.
![image](https://github.com/stakira/OpenUtau/assets/150820773/c946542b-46d4-43bd-8dfc-61ab5e1e905a)

### Explains how to reproduce the bug

1- Use moresampler in classic mode;
2- Use resampler in engine selection.

### OS & Version

Windows 11

### Logs

11/14/2023 11:19:48 -03:00 : Error :  >>> [thread-11] O sistema nao pode executar o programa especificado.
11/14/2023 11:19:47 -03:00 : Error :  >>> [thread-11] O sistema nao pode executar o programa especificado.
11/14/2023 11:19:47 -03:00 : Error :  >>> [thread-11] O sistema nao pode executar o programa especificado.
11/14/2023 11:19:27 -03:00 : Error :  >>> [thread-11] O sistema nao pode executar o programa especificado.
11/14/2023 11:19:26 -03:00 : Error :  >>> [thread-11] O sistema nao pode executar o programa especificado.
11/14/2023 11:18:51 -03:00 : Error :  >>> [thread-11] O sistema nao pode executar o programa especificado.
11/14/2023 11:18:50 -03:00 : Error :  >>> [thread-11] O sistema nao pode executar o programa especificado.
11/14/2023 11:18:50 -03:00 : Error :  >>> [thread-11] O sistema nao pode executar o programa especificado.
11/14/2023 11:18:49 -03:00 : Error :  >>> [thread-11] O sistema nao pode executar o programa especificado.
11/14/2023 11:18:49 -03:00 : Error :  >>> [thread-11] O sistema nao pode executar o programa especificado.
11/14/2023 11:18:48 -03:00 : Error :  >>> [thread-11] O sistema nao pode executar o programa especificado.
11/14/2023 11:18:48 -03:00 : Error :  >>> [thread-11] O sistema nao pode executar o programa especificado.
11/14/2023 11:18:48 -03:00 : Error :  >>> [thread-11] O sistema nao pode executar o programa especificado.
11/14/2023 11:18:48 -03:00 : Error :  >>> [thread-11] O sistema nao pode executar o programa especificado.
11/14/2023 11:18:48 -03:00 : Error :  >>> [thread-11] O sistema nao pode executar o programa especificado.
11/14/2023 11:18:48 -03:00 : Error :  >>> [thread-11] O sistema nao pode executar o programa especificado.
11/14/2023 11:18:47 -03:00 : Error :  >>> [thread-11] O sistema nao pode executar o programa especificado.
11/14/2023 11:18:47 -03:00 : Error :  >>> [thread-11] O sistema nao pode executar o programa especificado.
11/14/2023 11:18:46 -03:00 : Error :  >>> [thread-11] O sistema nao pode executar o programa especificado.
11/14/2023 11:18:46 -03:00 : Error :  >>> [thread-11] O sistema nao pode executar o programa especificado.
11/14/2023 11:18:31 -03:00 : Error : Failed to render.
11/14/2023 11:17:42 -03:00 : Error :  >>> [thread-16] O sistema nao pode executar o programa especificado.
11/14/2023 11:17:41 -03:00 : Error :  >>> [thread-16] O sistema nao pode executar o programa especificado.
11/14/2023 11:17:41 -03:00 : Error :  >>> [thread-16] O sistema nao pode executar o programa especificado.
11/14/2023 11:17:29 -03:00 : Error : Failed to render.
11/14/2023 11:17:27 -03:00 : Error :  >>> [thread-16] O sistema nao pode executar o programa especificado.
11/14/2023 11:17:27 -03:00 : Error :  >>> [thread-16] O sistema nao pode executar o programa especificado.
11/14/2023 11:17:27 -03:00 : Error :  >>> [thread-16] O sistema nao pode executar o programa especificado.
11/14/2023 11:17:26 -03:00 : Error :  >>> [thread-16] O sistema nao pode executar o programa especificado.
11/14/2023 11:17:26 -03:00 : Error :  >>> [thread-16] O sistema nao pode executar o programa especificado.
11/14/2023 11:17:26 -03:00 : Error :  >>> [thread-16] O sistema nao pode executar o programa especificado.
11/14/2023 11:17:25 -03:00 : Error :  >>> [thread-16] O sistema nao pode executar o programa especificado.
11/14/2023 11:17:25 -03:00 : Error :  >>> [thread-16] O sistema nao pode executar o programa especificado.
11/14/2023 11:17:25 -03:00 : Error :  >>> [thread-16] O sistema nao pode executar o programa especificado.
11/14/2023 11:17:24 -03:00 : Error :  >>> [thread-16] O sistema nao pode executar o programa especificado.
11/14/2023 11:17:24 -03:00 : Error :  >>> [thread-16] O sistema nao pode executar o programa especificado.
11/14/2023 11:17:24 -03:00 : Error :  >>> [thread-16] O sistema nao pode executar o programa especificado.
11/14/2023 11:17:23 -03:00 : Error :  >>> [thread-16] O sistema nao pode executar o programa especificado.
11/14/2023 11:17:22 -03:00 : Error :  >>> [thread-16] O sistema nao pode executar o programa especificado.
11/14/2023 11:17:17 -03:00 : Error :  >>> [thread-16] O sistema nao pode executar o programa especificado.
11/14/2023 11:17:15 -03:00 : Error :  >>> [thread-16] O sistema nao pode executar o programa especificado.
11/14/2023 11:17:14 -03:00 : Error :  >>> [thread-16] O sistema nao pode executar o programa especificado.
11/14/2023 11:16:58 -03:00 : Error : Failed to render.
11/14/2023 11:16:53 -03:00 : Error : Failed to render.
11/14/2023 11:16:51 -03:00 : Error : Failed to render.
11/14/2023 10:46:44 -03:00 : Error : Failed to render.
11/14/2023 10:46:35 -03:00 : Error : No active undoGroup to end.
11/14/2023 10:46:35 -03:00 : Error : undoGroup already started

------------

When try to play, apears this:

Failed to render.
Unsupported audio file format.

System.AggregateException: One or more errors occurred. (Unsupported audio file format.)
 ---> System.Exception: Unsupported audio file format.
   at OpenUtau.Core.Format.Wave.OpenFile(String filepath) in C:\projects\openutau\OpenUtau.Core\Format\Wave.cs:line 50
   at OpenUtau.Classic.ExeWavtool.Concatenate(List`1 resamplerItems, String tempPath, CancellationTokenSource cancellation) in C:\projects\openutau\OpenUtau.Core\Classic\ExeWavtool.cs:line 44
   at OpenUtau.Classic.ClassicRenderer.<>c__DisplayClass9_0.<RenderExternal>b__0() in C:\projects\openutau\OpenUtau.Core\Classic\ClassicRenderer.cs:line 118
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---

0.1.282.0
![image](https://github.com/stakira/OpenUtau/assets/150820773/cf97592f-2510-4222-8ea9-a80fa9764fe4)

**Comment by AKKIKKIRA** [comment]
> Imagino que isso tenha acontecido por ser a versão mais atualizada do programa, não? Talvez seja melhor continuar na versão estável, a não ser que o seu objetivo seja ser mais entusiasta mesmo.

Estava na versão normal que estava funcionando, porém, estava com esse problema. Hoje pela manhã atualizei e continuei com o mesmo problema.

**Comment by lottev1991** [comment]
In order to use the worldline resampler, you need to select either convergence or simple as your wavtool. It does not work with any other wavtools. Perhaps I should add this information to the wiki, it seems to be a common occurrence and there's no good information on this yet.

**Comment by AKKIKKIRA** [comment]
Thanks! @lottev1991
