### ISSUE TITLE
Classic Resamplers Issue

### ISSUE THREAD

**Issue by Nexys4t** [stakira/OpenUtau#967]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Using the default WORLDLINE-R resampler works perfectly fine. However, when trying to use the CLASSIC resamplers in any combination possible, it doesn't work properly. No sound is rendered. This happens with any voicebank and classic resamplers.

Pictures showing difference of default resampler and CLASSIC resamplers:
![image](https://github.com/stakira/OpenUtau/assets/140891736/68d99f91-618e-43c3-a7f6-1bd2e993be2a)
![image](https://github.com/stakira/OpenUtau/assets/140891736/bdf001ca-6adf-46b0-b4bb-510cba779aea)

### Explains how to reproduce the bug

1. Click default resampler WORLDLINE-R
2. Change to CLASSIC
3. Select any supported resampler/wavtool
4. It shows process of rendering, but it fails to render everything.

### OS & Version

Windows 11

### Logs

[log20231202.txt](https://github.com/stakira/OpenUtau/files/13537130/log20231202.txt)

**Comment by lottev1991** [comment]
Did you install OpenUtau in Program Files? Doing so may cause permission issues. Try moving it elsewhere and see if that helps, if so.

**Comment by Nexys4t** [comment]
> Did you install OpenUtau in Program Files? Doing so may cause permission issues. Try moving it elsewhere and see if that helps, if so.

As far as I am aware it should be installed outside Program Files just like UTAU (I should have them around my Desktop). I can't check it out right now, sadly, but when I can I will make sure to update this reply.

Quick question. If I had to move it, would it be enough with just moving the entire folder? Some programs don't work like that, sadly. That's why I want to make sure just in case.

**Comment by Nexys4t** [comment]
UPDATE: I have it installed in my Desktop.

**Comment by Nexys4t** [comment]
I tried with another computer, newest version OU, other voicebanks, Windows 10, folder is in Desktop. Same issue. I apologize for so many replies in my own thread, but I want to find a solution since this problem has been bugging me since the first ever moment I tried UTAU on the first releases it had.

I see other people are able to use the classic resamplers with no issues, but the voices in my program never make a sound. Another user said in this thread they have the same problem. I can't join the Discord yet for personal reasons, so I can only ask here.

**Comment by Nexys4t** [comment]
> Me too!: It renders but it won't show me the wavwaves, renders slowly,taking longer, when it end rendering a batch of samples from a complete project, any tracks in classic mode with any resamp /and wavtool out from Worldline,convergence or simple, it comes awfully off timed. Also if I dare render with moresampler, instead of rendering notes normaly, it plays the actual .wav file. I'm same OS & Version btw. Only if it's a new project at least shows rendered wavforms. Last minute Update if I use OU in my D: Driver and not from the external it runs somewhat normally. Guess OU does not like being used externally sort of speaking.

Hello, did you find a solution?

**Comment by Nexys4t** [comment]
The problem still persists. Tried in different machines, both Windows 11 and Windows 10.

The following error is in external drive D :
```
Failed to render

resampler.exe failed to resample "a" at 0:3.180

System.AggregateException: One or more errors occurred. (resampler.exe failed to resample "a" at 0:3.180)
 ---> System.IO.InvalidDataException: resampler.exe failed to resample "a" at 0:3.180
   at OpenUtau.Classic.ClassicRenderer.<>c__DisplayClass8_0.<RenderInternal>b__1(ResamplerItem item) in D:\a\OpenUtau\OpenUtau\OpenUtau.Core\Classic\ClassicRenderer.cs:line 76
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---

0.1.546.0
```

This error is in my main machine, the folder is in C, in Desktop 
```
Failed to render

tn_fnds.exe failed to resample "a" at 1:3.300

System.AggregateException: One or more errors occurred. (tn_fnds.exe failed to resample "a" at 1:3.300)
 ---> System.IO.InvalidDataException: tn_fnds.exe failed to resample "a" at 1:3.300
   at OpenUtau.Classic.ClassicRenderer.<>c__DisplayClass8_0.<RenderInternal>b__1(ResamplerItem item) in D:\a\OpenUtau\OpenUtau\OpenUtau.Core\Classic\ClassicRenderer.cs:line 76
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---

0.1.546.0
```

I tried different resamplers & wavtools.
This error pops up everytime in all the machines, in all OU versions.
I'm getting tired of coming here with the same problem each certain ammount of time, still no solution.
