### ISSUE TITLE
"This app can't run on your pc"

### ISSUE THREAD

**Issue by Cadlaxa** [stakira/OpenUtau#97]
Hello I've just downloaded the latest build but the OpenUtau.exe won't run and I always get the same notification "This app can't run on your PC, To find a version of your PC, check with the software publisher". My computer runs on windows 10 21h1 32 bit, I updated the necessary windows desktop-runtime 3.1.19 but it didn't work. Idk if the app supports 32 bit architecture cause I read the wiki about the installation but it wasn't specified if it's only support 64 bit or both.

**Comment by Astel123457** [comment]
It does support 32 and 64 bit.
Try joining our discord for further help on this matter.
