### ISSUE TITLE
Phonemizer stopped Auto-inputing VCs

### ISSUE THREAD

**Issue by Michelino98** [stakira/OpenUtau#970]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Hello like the title says. OU's Phonemizer stopped automatically input the VCs or even on other banks when they're used as voicecolor. Only if the CVVC VB is stand alone it normally uses it's own VCs multi or monopitch. I remember for example if you bundle and voice color assing'em, normally.
It should be:
 - あ扇風機 a s扇風機 さ扇風機 a k楽 こ楽 i ん扇風機 n ny悲 に悲 i ch楽 ち楽 i w楽 わ楽 
and not as:
 - あ扇風機 a s さ扇風機 a k こ楽 i ん扇風機 n ny に悲 i ch ち楽 i w わ楽.

I notices that when was making a bundle VB for (空音ライ)Sorane Lie using they're other banks made by 三ヶ木ちい(Mikage chii) and color assing each bank.
I wanted to test out they're CVVC append named 贋作 bank, that's the moment I saw for the first time the issue. 
Here some screenshots.
![phoneticnazers are ignoring CVVC's VCs 2](https://github.com/stakira/OpenUtau/assets/137897357/5ee8419f-0faa-4780-846b-54e55de8f370)
***Not only it happens with CVVC*** but with VCVLiteCVVC too (they're rare btw) like Honoka Elie's 女子アナウ(Girl Annoucer)the one with 宣 Suffix. The VCs are needed for the full use.
![phoneticnazers are ignoring CVVC's VCs 1 ver 2](https://github.com/stakira/OpenUtau/assets/137897357/2f41205c-e228-48db-b182-779d7ead6077)
the next example is about not automaticlly inputing the correct VC when it's fully CVVC supported including appends. it's what I wrote earlier.
![phoneticnazers are ignoring CVVC's VCs 3](https://github.com/stakira/OpenUtau/assets/137897357/8e109b37-83f5-4722-ba3b-e029b25ec92b)
not even the EN to JA is safe from the issue.
![Even the Engrish](https://github.com/stakira/OpenUtau/assets/137897357/86d0e45d-fe02-407b-98e4-20adea12daf1)

In short VCV/CVVC VB with any CVVC set as appends/voicecolors VCs will not be inputed or inputed incorrectlly, I don't know if it spreaded even with other Phonemizers, as long there's VCs ver.1.327.0. phonemizers will not auto set the VB even if the notes are in CV format. I mainly use JA Phonemizers I haven't tested with the English ones or the others yet. I dunno they are affected too.

Hope that I fully explained the whole issue, and hope this gets fixed.
P.S. the 3rd and 4th one can be somewhat solved by just using the parameters feature and set at or selecting the desidered color but the 4th one seems to ignore even ending VCs. Please fix it. It might hinder or annoy users. hence why 

P.P.S. Sorry for the last bit in the 2nd log I sended I was fooling around with drawn pitch with another bank an' render settings.
P.P.P.S. the third log was about testing the EN to JA Phonemizer.

### Explains how to reproduce the bug

To reproduce this bug inshort
1.Update OU from 1.158.0. to version 1.327.0.
2.Select any VB or a VB with a voicecolor assinged CVVC.
3.Select either JA CVVC or Presamp based JA VCV&CVVC Phonemizers.
4.Open any ust,ustx or vsqx or new project, draw some notes.

### OS & Version

Windows 11 x64 bit

### Logs

[log20231204.txt](https://github.com/stakira/OpenUtau/files/13544791/log20231204.txt)
[log20231204.txt](https://github.com/stakira/OpenUtau/files/13547569/log20231204.txt)
[log20231204.txt](https://github.com/stakira/OpenUtau/files/13562539/log20231204.txt)

**Comment by Michelino98** [comment]
If the solution is simply redownload/install OU, let me know.

**Comment by Michelino98** [comment]
***UPDATE*** reinstalling did anything unfortunatly.

**Comment by lottev1991** [comment]
> ### 🐛 Describe the bug
> 
> Hello like the title says. OU's Phonemizer stopped automatically input the VCs or even on other banks when they're used as voicecolor. Only if the CVVC VB is stand alone it normally uses it's own VCs multi or monopitch. I remember for example if you bundle and voice color assing'em, normally. It should be:
> 
>     * あ扇風機 a s扇風機 さ扇風機 a k楽 こ楽 i ん扇風機 n ny悲 に悲 i ch楽 ち楽 i w楽 わ楽
>       and not as:
> 
>     * あ扇風機 a s さ扇風機 a k こ楽 i ん扇風機 n ny に悲 i ch ち楽 i w わ楽.
> 
> 
> I notices that when was making a bundle VB for (空音ライ)Sorane Lie using they're other banks made by 三ヶ木ちい(Mikage chii) and color assing each bank. I wanted to test out they're CVVC append named 贋作 bank, that's the moment I saw for the first time the issue. Here some screenshots. ![phoneticnazers are ignoring CVVC's VCs 2](https://private-user-images.githubusercontent.com/137897357/287646797-5ee8419f-0faa-4780-846b-54e55de8f370.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNTE3NTAsIm5iZiI6MTcwMjI1MTQ1MCwicGF0aCI6Ii8xMzc4OTczNTcvMjg3NjQ2Nzk3LTVlZTg0MTlmLTBmYWEtNDc4MC04NDZiLTU0ZTU1ZGU4ZjM3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMFQyMzM3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MzQxMGFiYTIxNDQ4NDRkZDlkNzgyNzZiZTM1OGZlYTEzOWUwZThjNzdiNDExODAwNzJkYzhkZTczMTg0ZDZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QaDhDYzNgOmVQXee2vP0XOnRiO5sJzPMYymUSGpXqYE) _**Not only it happens with CVVC**_ but with VCVLiteCVVC too (they're rare btw) like Honoka Elie's 女子アナウ(Girl Annoucer)the one with 宣 Suffix. The VCs are needed for the full use. ![phoneticnazers are ignoring CVVC's VCs 1 ver 2](https://private-user-images.githubusercontent.com/137897357/287647711-2f41205c-e228-48db-b182-779d7ead6077.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNTE3NTAsIm5iZiI6MTcwMjI1MTQ1MCwicGF0aCI6Ii8xMzc4OTczNTcvMjg3NjQ3NzExLTJmNDEyMDVjLWUyMjgtNDhkYi1iMTgyLTc3OWQ3ZWFkNjA3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMFQyMzM3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMzg2ZGFlMzRhNTQ3YjUzMjk0NDc1ZDJkNDQzNTBlNDcxNGM0ODE2NDBiZDVjZDBiNTZlZDY5YTNmMjFiYmExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Mh3M31J_h-i8kDEihbULQbqOkFUOJocgzP8l0MbBAkA) 

Are you using the Japanese Presamp Phonemizer here? It could be an issue with the presamp.ini file.

>the next example is about not automaticlly inputing the correct VC when it's fully CVVC supported including appends. it's what I wrote earlier. ![phoneticnazers are ignoring CVVC's VCs 3](https://private-user-images.githubusercontent.com/137897357/287648579-8e109b37-83f5-4722-ba3b-e029b25ec92b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNTE3NTAsIm5iZiI6MTcwMjI1MTQ1MCwicGF0aCI6Ii8xMzc4OTczNTcvMjg3NjQ4NTc5LThlMTA5YjM3LTgzZjUtNDcyMi1iYTNiLWUwMjliMjVlYzkyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMFQyMzM3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOGVmZmQ0NGRhODM5YzYyZjUyYzg1ZmY5YmIwNWU3MzRlNjUwN2FiMzQ1YWRkZWZiMTA0YTY5MDNkODYyMzk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D3MOXuFjvmMSQUtjlv0nIXzgqxZ_GtsW3Ay1_YzxmSs) not even the EN to JA is safe from the issue. ![Even the Engrish](https://private-user-images.githubusercontent.com/137897357/287731302-86d0e45d-fe02-407b-98e4-20adea12daf1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNTE3NTAsIm5iZiI6MTcwMjI1MTQ1MCwicGF0aCI6Ii8xMzc4OTczNTcvMjg3NzMxMzAyLTg2ZDBlNDVkLWZlMDItNDA3Yi05OGU0LTIwYWRlYTEyZGFmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMFQyMzM3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NjcwM2M5ZGQwN2I3ZGMyNzcxM2I3OTM2YTQ5ZGJmNzUxY2I1YzI2ODY0NjZiZGE4NGZmYjAwN2I5ZDNjNzYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.utP5rHdvnlLkqx_r6Ew4ICoRdHfx1G5dtJx7Vq8ZGz0)
> 
> In short VCV/CVVC VB with any CVVC set as appends/voicecolors VCs will not be inputed or inputed incorrectlly, I don't know if it spreaded even with other Phonemizers, as long there's VCs ver.1.327.0. phonemizers will not auto set the VB even if the notes are in CV format. I mainly use JA Phonemizers I haven't tested with the English ones or the others yet. I dunno they are affected too.

You have to manually change the voice color of the VC separately from the VC note. If you look closely at the image, you'll see that the correct voice colors are not yet selected on the VC notes.
 
> Hope that I fully explained the whole issue, and hope this gets fixed. P.S. the 3rd and 4th one can be somewhat solved by just using the parameters feature and set at or selecting the desidered color but the 4th one seems to ignore even ending VCs. Please fix it. It might hinder or annoy users. hence why

These aren't bugs, but features, so there's nothing to be fixed here.

**Comment by Michelino98** [comment]
1.Yes I did set the Japanese Presamp Phonemizer here and I even put a premade presamp.ini in Sorane Lie's root folder but still no VC from the CVVC at the end of the notes like previous version of OU how can I fix this? If I put VCs and CV phonemes will it fix?
2. If it in intended then ok.

**Comment by lottev1991** [comment]
Did you perhaps select a voice color before that doesn't have VC transitions, before selecting one that does have them? It's a known bug that VC transitions will disappear in that case. I sadly have yet to find a proper solution for it. The only way right now is to delete the note and re-add it.

**Comment by Michelino98** [comment]
Yes like it the rest of Sorane Lie's banks are all monopitch VCVs, one normal CV and the one on the screenshoot is they're 逸話 which is a VCV 4+1falsetto pitch. At first I trired on re-assamble them from scratch a well few times changing the suffix alias thinking it was the probleam but no, Ok let me try delete and re-add notes worth a try?

**Comment by Michelino98** [comment]
**UPDATE:** Delete and re-adding notes did nothing :(  welp tried everything. I hope there're possibly a solution.

https://github.com/stakira/OpenUtau/assets/137897357/44fb1f11-bd19-429b-9386-b5fe0ad581ac

**Comment by lottev1991** [comment]
Are you sure there are VCs in the oto?

**Comment by Michelino98** [comment]
In the main and the others no VCs, only in 贋作. I tried to make some "fake" ones without suffixes in setparam in attempt to make the phonemizer work. Sometimes it works and input the VCs and other times it doesen't.

**Comment by lottev1991** [comment]
If the main color does not have VC's, then currently there will be no VC's inserted, no. I'll try to look for a fix for this; it's not really convenient this way.

**Comment by Michelino98** [comment]
Bump to keep it active.
