### ISSUE TITLE
On Mac (Latest OS), 

### ISSUE THREAD

**Issue by Bubalo1234** [stakira/OpenUtau#998]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

I use an intel MacBook Pro and OpenUtau keeps crashing by going to a blank gray screen.

<img width="1456" alt="Screenshot 2023-12-31 at 2 59 47 PM" src="https://github.com/stakira/OpenUtau/assets/80659275/04b47242-10fd-4ddc-922e-18cad449fb56">

### Explains how to reproduce the bug

1. Open the app on a MacBook.
2. Try to open the note editor.
3. It crashes

### OS & Version

macOS Sonoma 14.1.1

### Logs

[log20231231.txt](https://github.com/stakira/OpenUtau/files/13802335/log20231231.txt)

**Comment by sexy-Chen** [comment]
I've got the same problem.   Apple M1 Max,  macOS sonoma 14.2.1

**Comment by bigtendons8** [comment]
Think I may be having the same issue. However, when I resize the note editor window, the editor shows and the grey screen goes away. Apple M1, Sonoma 14.0.

**Comment by Astel123457** [comment]
This is a known issue, resizing is known to fix.
